# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "demoSheetFold2"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_demoSheetFold2_facePattern_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 100.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_facePattern_Fa0_Ctr1():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(37.5668, 162.7198, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_facePattern_Fa0_Ctr2():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(82.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(37.5668, 162.7198, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_facePattern_Fa0_Ctr3():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(82.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(65.4940, 44.1762, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_facePattern_Fa0_Ctr4():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(100.0000, 79.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 79.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_facePattern_Fa0():
	FC000 = ctr_face_demoSheetFold2_facePattern_Fa0_Ctr0()
	FC001 = ctr_face_demoSheetFold2_facePattern_Fa0_Ctr1()
	FC002 = ctr_face_demoSheetFold2_facePattern_Fa0_Ctr2()
	FC003 = ctr_face_demoSheetFold2_facePattern_Fa0_Ctr3()
	FC004 = ctr_face_demoSheetFold2_facePattern_Fa0_Ctr4()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004])
	rOneFace.check()
	return rOneFace

def demoSheetFold2_facePattern():
	FA000 = face_demoSheetFold2_facePattern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 100.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f00_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f00():
	FA000 = face_demoSheetFold2_SFG_f00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 100.0000, 0)
	P001 = App.Vector(0.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(162.7198, 62.4332, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f01_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f01():
	FA000 = face_demoSheetFold2_SFG_f01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(79.8983, 18.4460, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.0000, 167.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f02_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f02():
	FA000 = face_demoSheetFold2_SFG_f02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 82.0000, 0)
	P001 = App.Vector(0.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(44.1762, 16.5060, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 82.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f03_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f03():
	FA000 = face_demoSheetFold2_SFG_f03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f04_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(100.0000, 79.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.0000, 79.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f04_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f04_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f04():
	FA000 = face_demoSheetFold2_SFG_f04_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(3.2632, 0.2139, 0)
	P002 = App.Vector(6.4705, 0.8519, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.8823, 10.5111, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1.9579, 10.1283, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj00_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj00():
	FA000 = face_demoSheetFold2_SFG_fj00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(23.0126, 15.2317, 0)
	P002 = App.Vector(17.9835, 42.3665, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(10.7901, 35.4199, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(13.8076, 19.1390, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj01_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj01():
	FA000 = face_demoSheetFold2_SFG_fj01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(3.0467, 0.1863, 0)
	P002 = App.Vector(6.0480, 0.7426, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.6288, 10.4456, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1.8280, 10.1118, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj02_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj02():
	FA000 = face_demoSheetFold2_SFG_fj02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(24.0908, 18.3190, 0)
	P002 = App.Vector(12.8760, 46.4292, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(7.7256, 37.8575, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(14.4545, 20.9914, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj03_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj03():
	FA000 = face_demoSheetFold2_SFG_fj03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_SFG_f00():
	FIG = demoSheetFold2_SFG_f00()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_SFG_f00 = fex_subpax_SFG_f00()

def fex_subpax_SFG_f01():
	FIG = demoSheetFold2_SFG_f01()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -15.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(206.4705, -0.0000, 0.8519))
	return VFP
subpax_SFG_f01 = fex_subpax_SFG_f01()

def fex_subpax_SFG_f02():
	FIG = demoSheetFold2_SFG_f02()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -160.5182)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -40.8730)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -116.4764)
	VFP = VR3.translate(App.Vector(356.5880, 79.9558, 84.9367))
	return VFP
subpax_SFG_f02 = fex_subpax_SFG_f02()

def fex_subpax_SFG_f03():
	FIG = demoSheetFold2_SFG_f03()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 143.5604)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -12.0518)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -32.8144)
	VFP = VR3.translate(App.Vector(361.6932, 77.1887, 86.7838))
	return VFP
subpax_SFG_f03 = fex_subpax_SFG_f03()

def fex_subpax_SFG_f04():
	FIG = demoSheetFold2_SFG_f04()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 41.1183)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 56.3061)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 138.9269)
	VFP = VR3.translate(App.Vector(385.5790, 6.2808, 75.4787))
	return VFP
subpax_SFG_f04 = fex_subpax_SFG_f04()

def fex_subpax_SFG_fj00():
	FIG = demoSheetFold2_SFG_fj00()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(200.0000, 100.0000, 0.0000))
	return VFP
subpax_SFG_fj00 = fex_subpax_SFG_fj00()

def fex_subpax_SFG_fj01():
	FIG = demoSheetFold2_SFG_fj01()
	VEX = FIG.extrude(App.Vector(0, 0, 167))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 75.3677)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -3.3377)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 77.4286)
	VFP = VR3.translate(App.Vector(206.4705, 100.0000, 0.8519))
	return VFP
subpax_SFG_fj01 = fex_subpax_SFG_fj01()

def fex_subpax_SFG_fj02():
	FIG = demoSheetFold2_SFG_fj02()
	VEX = FIG.extrude(App.Vector(0, 0, 82))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -129.1750)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -23.1367)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -23.8243)
	VFP = VR3.translate(App.Vector(312.2921, 30.0257, 132.5692))
	return VFP
subpax_SFG_fj02 = fex_subpax_SFG_fj02()

def fex_subpax_SFG_fj03():
	FIG = demoSheetFold2_SFG_fj03()
	VEX = FIG.extrude(App.Vector(0, 0, 79))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -114.8772)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -29.8629)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -64.0622)
	VFP = VR3.translate(App.Vector(317.3972, 27.2586, 134.4162))
	return VFP
subpax_SFG_fj03 = fex_subpax_SFG_fj03()

def fvol_pax_demoSheetFold2():
	V000 = subpax_SFG_f00
	V001 = V000.fuse(subpax_SFG_f01)
	V002 = V001.fuse(subpax_SFG_f02)
	V003 = V002.fuse(subpax_SFG_f03)
	V004 = V003.fuse(subpax_SFG_f04)
	V005 = V004.fuse(subpax_SFG_fj00)
	V006 = V005.fuse(subpax_SFG_fj01)
	V007 = V006.fuse(subpax_SFG_fj02)
	V008 = V007.fuse(subpax_SFG_fj03)
	VFC = V008.removeSplitter()
	return VFC
pax_demoSheetFold2 = fvol_pax_demoSheetFold2()


pax_demoSheetFold2.check()
#pax_demoSheetFold2.exportBrep(f"{outFileName}.brep")
#pax_demoSheetFold2.exportIges(f"{outFileName}.igs")
#pax_demoSheetFold2.exportStep(f"{outFileName}.stp")
pax_demoSheetFold2.exportStl(f"{outFileName}.stl")

