# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "cabane"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_cabane_faceTop_Fa0_Ctr0():
	P000 = App.Vector(0.0000, -734.0000, 0)
	P001 = App.Vector(2825.0000, -734.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(3211.0000, 977.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(2125.0000, 1755.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-100.0000, 1755.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-1553.0000, 977.5000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(0.0000, -734.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceTop_Fa0():
	FC000 = ctr_face_cabane_faceTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceTop():
	FA000 = face_cabane_faceTop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_faceFaceFront_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 190.0000, 0)
	P001 = App.Vector(206.5000, 190.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-17.4593, 1445.1052, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-12.4124, 1528.5365, 0)
	P004 = App.Vector(30.1600, 1600.4659, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(489.9375, 2073.2868, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(647.9924, 2124.5718, 0)
	P007 = App.Vector(779.5181, 2023.0214, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(1321.6876, 833.5681, 0)
	S005 = Part.LineSegment(P007, P008)
	P009 = App.Vector(1337.6687, 755.4754, 0)
	P010 = App.Vector(1317.9642, 678.2381, 0)
	S006 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(1066.5000, 190.0000, 0)
	S007 = Part.LineSegment(P010, P011)
	P012 = App.Vector(1401.0000, 190.0000, 0)
	S008 = Part.LineSegment(P011, P012)
	P013 = App.Vector(1545.0000, 1989.4643, 0)
	S009 = Part.LineSegment(P012, P013)
	P014 = App.Vector(977.5000, 2620.1009, 0)
	S010 = Part.LineSegment(P013, P014)
	P015 = App.Vector(977.5000, 2626.4810, 0)
	S011 = Part.LineSegment(P014, P015)
	P016 = App.Vector(-295.0000, 1839.1147, 0)
	S012 = Part.LineSegment(P015, P016)
	P017 = App.Vector(0.0000, 190.0000, 0)
	S013 = Part.LineSegment(P016, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceFront_Fa0():
	FC000 = ctr_face_cabane_faceFaceFront_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceFaceFront():
	FA000 = face_cabane_faceFaceFront_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_faceFaceBack_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 190.0000, 0)
	P001 = App.Vector(1401.0000, 190.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1545.0000, 1989.4643, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(977.5000, 2620.1009, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(977.5000, 2626.4810, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-295.0000, 1839.1147, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(0.0000, 190.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceBack_Fa0():
	FC000 = ctr_face_cabane_faceFaceBack_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_faceFaceBack_Fa1_Ctr0():
	P000 = App.Vector(155.1618, 334.0000, 0)
	P001 = App.Vector(709.8910, 334.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(745.1668, 345.4653, 0)
	P003 = App.Vector(766.9611, 375.4794, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(1256.0182, 1882.4794, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(1247.4829, 1936.2758, 0)
	P006 = App.Vector(1198.9482, 1961.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(336.7058, 1961.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(296.8973, 1945.8919, 0)
	P009 = App.Vector(277.1365, 1908.1761, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(95.5925, 401.1761, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(110.2699, 354.1915, 0)
	P012 = App.Vector(155.1618, 334.0000, 0)
	S007 = Part.Arc(P010, P011, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceBack_Fa1():
	FC000 = ctr_face_cabane_faceFaceBack_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceFaceBack():
	FA000 = face_cabane_faceFaceBack_Fa0()
	FA001 = face_cabane_faceFaceBack_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_faceFaceRoof_Fa0_Ctr0():
	P000 = App.Vector(977.5000, 2650.0000, 0)
	P001 = App.Vector(-734.0000, 1591.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-723.4765, 1573.9925, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(977.5000, 2626.4810, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(977.5000, 2620.1009, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(1740.1333, 1772.6217, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(1755.0000, 1786.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(977.5000, 2650.0000, 0)
	S006 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceRoof_Fa0():
	FC000 = ctr_face_cabane_faceFaceRoof_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceFaceRoof():
	FA000 = face_cabane_faceFaceRoof_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_faceFaceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 190.0000, 0)
	P001 = App.Vector(20.3175, 190.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-276.7073, 1850.4334, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-295.0000, 1839.1147, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 190.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceSide_Fa0():
	FC000 = ctr_face_cabane_faceFaceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_faceFaceSide_Fa1_Ctr0():
	P000 = App.Vector(1401.0000, 190.0000, 0)
	P001 = App.Vector(1545.0000, 1989.4643, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1526.5746, 2009.9396, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1380.9361, 190.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1401.0000, 190.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceSide_Fa1():
	FC000 = ctr_face_cabane_faceFaceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceFaceSide():
	FA000 = face_cabane_faceFaceSide_Fa0()
	FA001 = face_cabane_faceFaceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 190.0000, 0)
	P001 = App.Vector(1958.0000, 190.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1958.0000, 1839.1147, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1839.1147, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 190.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceSide_Fa0():
	FC000 = ctr_face_cabane_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_faceSide_Fa1_Ctr0():
	P000 = App.Vector(-1553.0000, 2650.0000, 0)
	P001 = App.Vector(0.0000, 1591.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2825.0000, 1591.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(3211.0000, 2650.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-1553.0000, 2650.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceSide_Fa1():
	FC000 = ctr_face_cabane_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceSide():
	FA000 = face_cabane_faceSide_Fa0()
	FA001 = face_cabane_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_facePlancherTop_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(1958.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1958.0000, 174.9500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 174.9500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa0():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa1_Ctr0():
	P000 = App.Vector(0.0000, 175.1500, 0)
	P001 = App.Vector(1958.0000, 175.1500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1958.0000, 350.1000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 350.1000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 175.1500, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa1():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa2_Ctr0():
	P000 = App.Vector(0.0000, 350.3000, 0)
	P001 = App.Vector(1958.0000, 350.3000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1958.0000, 525.2500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 525.2500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 350.3000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa2():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa3_Ctr0():
	P000 = App.Vector(0.0000, 525.4500, 0)
	P001 = App.Vector(1958.0000, 525.4500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1958.0000, 700.4000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 700.4000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 525.4500, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa3():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa4_Ctr0():
	P000 = App.Vector(0.0000, 700.6000, 0)
	P001 = App.Vector(1958.0000, 700.6000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1958.0000, 875.5500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 875.5500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 700.6000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa4():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa5_Ctr0():
	P000 = App.Vector(0.0000, 875.7500, 0)
	P001 = App.Vector(1958.0000, 875.7500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1958.0000, 1050.7000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1050.7000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 875.7500, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa5():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa6_Ctr0():
	P000 = App.Vector(0.0000, 1050.9000, 0)
	P001 = App.Vector(1958.0000, 1050.9000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1958.0000, 1225.8500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1225.8500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 1050.9000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa6():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa7_Ctr0():
	P000 = App.Vector(0.0000, 1226.0500, 0)
	P001 = App.Vector(1958.0000, 1226.0500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1958.0000, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 1226.0500, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa7():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_facePlancherTop():
	FA000 = face_cabane_plancher_facePlancherTop_Fa0()
	FA001 = face_cabane_plancher_facePlancherTop_Fa1()
	FA002 = face_cabane_plancher_facePlancherTop_Fa2()
	FA003 = face_cabane_plancher_facePlancherTop_Fa3()
	FA004 = face_cabane_plancher_facePlancherTop_Fa4()
	FA005 = face_cabane_plancher_facePlancherTop_Fa5()
	FA006 = face_cabane_plancher_facePlancherTop_Fa6()
	FA007 = face_cabane_plancher_facePlancherTop_Fa7()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_facePlancherBottom_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(150.4308, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(150.4308, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa0():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa1_Ctr0():
	P000 = App.Vector(150.6308, 0.0000, 0)
	P001 = App.Vector(301.0615, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(301.0615, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(150.6308, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(150.6308, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa1():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa2_Ctr0():
	P000 = App.Vector(301.2615, 0.0000, 0)
	P001 = App.Vector(451.6923, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(451.6923, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(301.2615, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(301.2615, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa2():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa3_Ctr0():
	P000 = App.Vector(451.8923, 0.0000, 0)
	P001 = App.Vector(602.3231, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(602.3231, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(451.8923, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(451.8923, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa3():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa4_Ctr0():
	P000 = App.Vector(602.5231, 0.0000, 0)
	P001 = App.Vector(752.9538, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(752.9538, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(602.5231, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(602.5231, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa4():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa5_Ctr0():
	P000 = App.Vector(753.1538, 0.0000, 0)
	P001 = App.Vector(903.5846, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(903.5846, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(753.1538, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(753.1538, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa5():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa6_Ctr0():
	P000 = App.Vector(903.7846, 0.0000, 0)
	P001 = App.Vector(1054.2154, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1054.2154, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(903.7846, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(903.7846, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa6():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa7_Ctr0():
	P000 = App.Vector(1054.4154, 0.0000, 0)
	P001 = App.Vector(1204.8462, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1204.8462, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1054.4154, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1054.4154, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa7():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa8_Ctr0():
	P000 = App.Vector(1205.0462, 0.0000, 0)
	P001 = App.Vector(1355.4769, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1355.4769, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1205.0462, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1205.0462, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa8():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa9_Ctr0():
	P000 = App.Vector(1355.6769, 0.0000, 0)
	P001 = App.Vector(1506.1077, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1506.1077, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1355.6769, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1355.6769, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa9():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa10_Ctr0():
	P000 = App.Vector(1506.3077, 0.0000, 0)
	P001 = App.Vector(1656.7385, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1656.7385, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1506.3077, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1506.3077, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa10():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa11_Ctr0():
	P000 = App.Vector(1656.9385, 0.0000, 0)
	P001 = App.Vector(1807.3692, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1807.3692, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1656.9385, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1656.9385, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa11():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa12_Ctr0():
	P000 = App.Vector(1807.5692, 0.0000, 0)
	P001 = App.Vector(1958.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1958.0000, 1401.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1807.5692, 1401.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1807.5692, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa12():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa12_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_facePlancherBottom():
	FA000 = face_cabane_plancher_facePlancherBottom_Fa0()
	FA001 = face_cabane_plancher_facePlancherBottom_Fa1()
	FA002 = face_cabane_plancher_facePlancherBottom_Fa2()
	FA003 = face_cabane_plancher_facePlancherBottom_Fa3()
	FA004 = face_cabane_plancher_facePlancherBottom_Fa4()
	FA005 = face_cabane_plancher_facePlancherBottom_Fa5()
	FA006 = face_cabane_plancher_facePlancherBottom_Fa6()
	FA007 = face_cabane_plancher_facePlancherBottom_Fa7()
	FA008 = face_cabane_plancher_facePlancherBottom_Fa8()
	FA009 = face_cabane_plancher_facePlancherBottom_Fa9()
	FA010 = face_cabane_plancher_facePlancherBottom_Fa10()
	FA011 = face_cabane_plancher_facePlancherBottom_Fa11()
	FA012 = face_cabane_plancher_facePlancherBottom_Fa12()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011, FA012])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceBeam_Fa0_Ctr0():
	P000 = App.Vector(70.0500, 150.0000, 0)
	P001 = App.Vector(140.1000, 150.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(140.1000, 85.6213, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(139.1000, 79.9500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(70.0500, 79.9500, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(70.0500, 150.0000, 0)
	S004 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceBeam_Fa0():
	FC000 = ctr_face_cabane_plancher_faceBeam_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_faceBeam_Fa1_Ctr0():
	P000 = App.Vector(1330.9500, 150.0000, 0)
	P001 = App.Vector(1260.9000, 150.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1260.9000, 85.6213, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1261.9000, 79.9500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1330.9500, 79.9500, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(1330.9500, 150.0000, 0)
	S004 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceBeam_Fa1():
	FC000 = ctr_face_cabane_plancher_faceBeam_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceBeam():
	FA000 = face_cabane_plancher_faceBeam_Fa0()
	FA001 = face_cabane_plancher_faceBeam_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceLeg_Fa0_Ctr0():
	P000 = App.Vector(222.5823, 150.0000, 0)
	P001 = App.Vector(151.4517, 150.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(125.0027, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(196.1333, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(222.5823, 150.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceLeg_Fa0():
	FC000 = ctr_face_cabane_plancher_faceLeg_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_faceLeg_Fa1_Ctr0():
	P000 = App.Vector(1178.4177, 150.0000, 0)
	P001 = App.Vector(1249.5483, 150.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1275.9973, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1204.8667, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1178.4177, 150.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceLeg_Fa1():
	FC000 = ctr_face_cabane_plancher_faceLeg_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceLeg():
	FA000 = face_cabane_plancher_faceLeg_Fa0()
	FA001 = face_cabane_plancher_faceLeg_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceButtress_Fa0_Ctr0():
	P000 = App.Vector(222.5823, 150.0000, 0)
	P001 = App.Vector(1178.4177, 150.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1190.7694, 79.9500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(210.2306, 79.9500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(222.5823, 150.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceButtress_Fa0():
	FC000 = ctr_face_cabane_plancher_faceButtress_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceButtress():
	FA000 = face_cabane_plancher_faceButtress_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceSide_Fa0_Ctr0():
	P000 = App.Vector(140.1000, 0.0000, 0)
	P001 = App.Vector(210.1500, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(210.1500, 150.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(140.1000, 150.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(140.1000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceSide_Fa0():
	FC000 = ctr_face_cabane_plancher_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_faceSide_Fa1_Ctr0():
	P000 = App.Vector(1747.8500, 0.0000, 0)
	P001 = App.Vector(1817.9000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1817.9000, 150.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1747.8500, 150.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1747.8500, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceSide_Fa1():
	FC000 = ctr_face_cabane_plancher_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceSide():
	FA000 = face_cabane_plancher_faceSide_Fa0()
	FA001 = face_cabane_plancher_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_cabane_plancher_plancherTop():
	FIG = cabane_plancher_facePlancherTop()
	VEX = FIG.extrude(App.Vector(0, 0, 20))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 170.0000))
	return VFP
subpax_cabane_plancher_plancherTop = fex_subpax_cabane_plancher_plancherTop()

def fex_subpax_cabane_plancher_plancherBottom():
	FIG = cabane_plancher_facePlancherBottom()
	VEX = FIG.extrude(App.Vector(0, 0, 20))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 150.0000))
	return VFP
subpax_cabane_plancher_plancherBottom = fex_subpax_cabane_plancher_plancherBottom()

def fex_subpax_cabane_plancher_beam():
	FIG = cabane_plancher_faceBeam()
	VEX = FIG.extrude(App.Vector(0, 0, 1958))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(1958.0000, 1401.0000, 0.0000))
	return VFP
subpax_cabane_plancher_beam = fex_subpax_cabane_plancher_beam()

def fex_subpax_cabane_plancher_leg1():
	FIG = cabane_plancher_faceLeg()
	VEX = FIG.extrude(App.Vector(0, 0, 70.05))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(210.1500, 1401.0000, 0.0000))
	return VFP
subpax_cabane_plancher_leg1 = fex_subpax_cabane_plancher_leg1()

def fex_subpax_cabane_plancher_leg2():
	FIG = cabane_plancher_faceLeg()
	VEX = FIG.extrude(App.Vector(0, 0, 70.05))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(1817.9000, 1401.0000, 0.0000))
	return VFP
subpax_cabane_plancher_leg2 = fex_subpax_cabane_plancher_leg2()

def fex_subpax_cabane_plancher_buttress1():
	FIG = cabane_plancher_faceButtress()
	VEX = FIG.extrude(App.Vector(0, 0, 70.05))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(210.1500, 1401.0000, 0.0000))
	return VFP
subpax_cabane_plancher_buttress1 = fex_subpax_cabane_plancher_buttress1()

def fex_subpax_cabane_plancher_buttress2():
	FIG = cabane_plancher_faceButtress()
	VEX = FIG.extrude(App.Vector(0, 0, 70.05))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(1817.9000, 1401.0000, 0.0000))
	return VFP
subpax_cabane_plancher_buttress2 = fex_subpax_cabane_plancher_buttress2()

def fvol_pax_cabane_plancher():
	V000 = subpax_cabane_plancher_plancherTop
	V001 = V000.fuse(subpax_cabane_plancher_plancherBottom)
	V002 = V001.fuse(subpax_cabane_plancher_beam)
	V003 = V002.fuse(subpax_cabane_plancher_leg1)
	V004 = V003.fuse(subpax_cabane_plancher_leg2)
	V005 = V004.fuse(subpax_cabane_plancher_buttress1)
	V006 = V005.fuse(subpax_cabane_plancher_buttress2)
	VFC = V006.removeSplitter()
	return VFC
pax_cabane_plancher = fvol_pax_cabane_plancher()

def finh_inpax_cabane_plancher():
	IVR1 = pax_cabane_plancher.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return IVF
inpax_cabane_plancher = finh_inpax_cabane_plancher()

def fex_subpax_cabane_roofTop():
	FIG = cabane_faceTop()
	VEX = FIG.extrude(App.Vector(0, 0, 2650))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_cabane_roofTop = fex_subpax_cabane_roofTop()

def fex_subpax_cabane_roofMax():
	FIG = cabane_faceFaceRoof()
	VEX = FIG.extrude(App.Vector(0, 0, 4764))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(-1553.0000, 0.0000, 0.0000))
	return VFP
subpax_cabane_roofMax = fex_subpax_cabane_roofMax()

def fex_subpax_cabane_Wfront():
	FIG = cabane_faceFaceFront()
	VEX = FIG.extrude(App.Vector(0, 0, 20))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(1938.0000, 0.0000, 0.0000))
	return VFP
subpax_cabane_Wfront = fex_subpax_cabane_Wfront()

def fex_subpax_cabane_Wback():
	FIG = cabane_faceFaceBack()
	VEX = FIG.extrude(App.Vector(0, 0, 20))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_cabane_Wback = fex_subpax_cabane_Wback()

def fex_subpax_cabane_Wside():
	FIG = cabane_faceFaceSide()
	VEX = FIG.extrude(App.Vector(0, 0, 1958))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_cabane_Wside = fex_subpax_cabane_Wside()

def fvol_ipax_cabane_roof():
	V000 = subpax_cabane_roofMax
	V001 = V000.common(subpax_cabane_roofTop)
	VFC = V001.removeSplitter()
	return VFC
ipax_cabane_roof = fvol_ipax_cabane_roof()

def fvol_pax_cabane():
	V000 = inpax_cabane_plancher
	V001 = V000.fuse(ipax_cabane_roof)
	V002 = V001.fuse(subpax_cabane_Wfront)
	V003 = V002.fuse(subpax_cabane_Wback)
	V004 = V003.fuse(subpax_cabane_Wside)
	VFC = V004.removeSplitter()
	return VFC
pax_cabane = fvol_pax_cabane()


pax_cabane.check()
#pax_cabane.exportBrep(f"{outFileName}.brep")
#pax_cabane.exportIges(f"{outFileName}.igs")
#pax_cabane.exportStep(f"{outFileName}.stp")
pax_cabane.exportStl(f"{outFileName}.stl")

