# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "armJoint"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_armJoint_faceSide_Fa0_Ctr0():
	P000 = App.Vector(-43.5000, 0.0000, 0)
	P001 = App.Vector(43.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(43.5000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(90.2595, 117.1253, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 290.0000, 0)
	P005 = App.Vector(-90.2595, 117.1253, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-43.5000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-43.5000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armJoint_faceSide_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armJoint_faceSide_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armJoint_faceSide_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 65.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armJoint_faceSide_Fa0():
	FC000 = ctr_face_armJoint_faceSide_Fa0_Ctr0()
	FC001 = ctr_face_armJoint_faceSide_Fa0_Ctr1()
	FC002 = ctr_face_armJoint_faceSide_Fa0_Ctr2()
	FC003 = ctr_face_armJoint_faceSide_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSide_Fa1_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armJoint_faceSide_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(97.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armJoint_faceSide_Fa1():
	FC000 = ctr_face_armJoint_faceSide_Fa1_Ctr0()
	FC001 = ctr_face_armJoint_faceSide_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSide_Fa2_Ctr0():
	P000 = App.Vector(-86.2473, 330.2786, 0)
	P001 = App.Vector(-136.8128, 286.3227, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-104.0099, 248.5872, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-109.5123, 190.3465, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(72.1665, 96.9819, 0)
	P005 = App.Vector(4.9953, 289.8865, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-53.4443, 292.5431, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-86.2473, 330.2786, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armJoint_faceSide_Fa2_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(-95.1286, 289.4329, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armJoint_faceSide_Fa2_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armJoint_faceSide_Fa2_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(-72.1665, 263.0181, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armJoint_faceSide_Fa2():
	FC000 = ctr_face_armJoint_faceSide_Fa2_Ctr0()
	FC001 = ctr_face_armJoint_faceSide_Fa2_Ctr1()
	FC002 = ctr_face_armJoint_faceSide_Fa2_Ctr2()
	FC003 = ctr_face_armJoint_faceSide_Fa2_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armJoint_faceSide():
	FA000 = face_armJoint_faceSide_Fa0()
	FA001 = face_armJoint_faceSide_Fa1()
	FA002 = face_armJoint_faceSide_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_armJoint_faceTop_Fa0_Ctr0():
	P000 = App.Vector(-23.5000, 0.0000, 0)
	P001 = App.Vector(23.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(23.5000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-23.5000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-23.5000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armJoint_faceTop_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armJoint_faceTop_Fa0():
	FC000 = ctr_face_armJoint_faceTop_Fa0_Ctr0()
	FC001 = ctr_face_armJoint_faceTop_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceTop_Fa1_Ctr0():
	P000 = App.Vector(-30.0000, 0.0000, 0)
	P001 = App.Vector(-27.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-27.0000, 290.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-30.0000, 290.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-30.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceTop_Fa1():
	FC000 = ctr_face_armJoint_faceTop_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceTop_Fa2_Ctr0():
	P000 = App.Vector(27.0000, 0.0000, 0)
	P001 = App.Vector(30.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(30.0000, 290.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(27.0000, 290.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(27.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceTop_Fa2():
	FC000 = ctr_face_armJoint_faceTop_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceTop_Fa3_Ctr0():
	P000 = App.Vector(19.5000, 350.0000, 0)
	P001 = App.Vector(-19.5000, 350.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-19.5000, 300.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(19.5000, 300.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(19.5000, 350.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armJoint_faceTop_Fa3_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(-0.0000, 325.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armJoint_faceTop_Fa3():
	FC000 = ctr_face_armJoint_faceTop_Fa3_Ctr0()
	FC001 = ctr_face_armJoint_faceTop_Fa3_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceTop_Fa4_Ctr0():
	P000 = App.Vector(26.0000, 350.0000, 0)
	P001 = App.Vector(23.0000, 350.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(23.0000, 70.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(26.0000, 70.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(26.0000, 350.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceTop_Fa4():
	FC000 = ctr_face_armJoint_faceTop_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceTop_Fa5_Ctr0():
	P000 = App.Vector(-23.0000, 350.0000, 0)
	P001 = App.Vector(-26.0000, 350.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-26.0000, 70.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-23.0000, 70.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-23.0000, 350.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceTop_Fa5():
	FC000 = ctr_face_armJoint_faceTop_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceTop_Fa6_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armJoint_faceTop_Fa6():
	FC000 = ctr_face_armJoint_faceTop_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armJoint_faceTop():
	FA000 = face_armJoint_faceTop_Fa0()
	FA001 = face_armJoint_faceTop_Fa1()
	FA002 = face_armJoint_faceTop_Fa2()
	FA003 = face_armJoint_faceTop_Fa3()
	FA004 = face_armJoint_faceTop_Fa4()
	FA005 = face_armJoint_faceTop_Fa5()
	FA006 = face_armJoint_faceTop_Fa6()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006])
	rOneFig.check()
	return rOneFig

def ctr_face_armJoint_faceSection_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armJoint_faceSection_Fa0():
	FC000 = ctr_face_armJoint_faceSection_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa1_Ctr0():
	P000 = App.Vector(-43.5000, -30.0000, 0)
	P001 = App.Vector(43.5000, -30.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(43.5000, -27.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-43.5000, -27.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-43.5000, -30.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa1():
	FC000 = ctr_face_armJoint_faceSection_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa2_Ctr0():
	P000 = App.Vector(43.5000, -30.0000, 0)
	P001 = App.Vector(48.0962, -28.0962, 0)
	P002 = App.Vector(50.0000, -23.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(47.0000, -23.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(45.9749, -25.9749, 0)
	P005 = App.Vector(43.5000, -27.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(43.5000, -30.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa2():
	FC000 = ctr_face_armJoint_faceSection_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa3_Ctr0():
	P000 = App.Vector(50.0000, -23.5000, 0)
	P001 = App.Vector(50.0000, 23.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(47.0000, 23.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(47.0000, -23.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(50.0000, -23.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa3():
	FC000 = ctr_face_armJoint_faceSection_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa4_Ctr0():
	P000 = App.Vector(50.0000, 23.5000, 0)
	P001 = App.Vector(48.0962, 28.0962, 0)
	P002 = App.Vector(43.5000, 30.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(43.5000, 27.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(45.9749, 25.9749, 0)
	P005 = App.Vector(47.0000, 23.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(50.0000, 23.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa4():
	FC000 = ctr_face_armJoint_faceSection_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa5_Ctr0():
	P000 = App.Vector(43.5000, 30.0000, 0)
	P001 = App.Vector(-43.5000, 30.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-43.5000, 27.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(43.5000, 27.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(43.5000, 30.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa5():
	FC000 = ctr_face_armJoint_faceSection_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa6_Ctr0():
	P000 = App.Vector(-43.5000, 30.0000, 0)
	P001 = App.Vector(-48.0962, 28.0962, 0)
	P002 = App.Vector(-50.0000, 23.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-47.0000, 23.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-45.9749, 25.9749, 0)
	P005 = App.Vector(-43.5000, 27.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-43.5000, 30.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa6():
	FC000 = ctr_face_armJoint_faceSection_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa7_Ctr0():
	P000 = App.Vector(-50.0000, 23.5000, 0)
	P001 = App.Vector(-50.0000, -23.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-47.0000, -23.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-47.0000, 23.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-50.0000, 23.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa7():
	FC000 = ctr_face_armJoint_faceSection_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa8_Ctr0():
	P000 = App.Vector(-50.0000, -23.5000, 0)
	P001 = App.Vector(-48.0962, -28.0962, 0)
	P002 = App.Vector(-43.5000, -30.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-43.5000, -27.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-45.9749, -25.9749, 0)
	P005 = App.Vector(-47.0000, -23.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-50.0000, -23.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa8():
	FC000 = ctr_face_armJoint_faceSection_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa9_Ctr0():
	P000 = App.Vector(-33.5000, -26.0000, 0)
	P001 = App.Vector(33.5000, -26.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(33.5000, -23.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-33.5000, -23.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-33.5000, -26.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa9():
	FC000 = ctr_face_armJoint_faceSection_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa10_Ctr0():
	P000 = App.Vector(33.5000, -26.0000, 0)
	P001 = App.Vector(38.0962, -24.0962, 0)
	P002 = App.Vector(40.0000, -19.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(37.0000, -19.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(35.9749, -21.9749, 0)
	P005 = App.Vector(33.5000, -23.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(33.5000, -26.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa10():
	FC000 = ctr_face_armJoint_faceSection_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa11_Ctr0():
	P000 = App.Vector(40.0000, -19.5000, 0)
	P001 = App.Vector(40.0000, 19.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(37.0000, 19.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(37.0000, -19.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(40.0000, -19.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa11():
	FC000 = ctr_face_armJoint_faceSection_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa12_Ctr0():
	P000 = App.Vector(40.0000, 19.5000, 0)
	P001 = App.Vector(38.0962, 24.0962, 0)
	P002 = App.Vector(33.5000, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(33.5000, 23.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(35.9749, 21.9749, 0)
	P005 = App.Vector(37.0000, 19.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(40.0000, 19.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa12():
	FC000 = ctr_face_armJoint_faceSection_Fa12_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa13_Ctr0():
	P000 = App.Vector(33.5000, 26.0000, 0)
	P001 = App.Vector(-33.5000, 26.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-33.5000, 23.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(33.5000, 23.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(33.5000, 26.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa13():
	FC000 = ctr_face_armJoint_faceSection_Fa13_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa14_Ctr0():
	P000 = App.Vector(-33.5000, 26.0000, 0)
	P001 = App.Vector(-38.0962, 24.0962, 0)
	P002 = App.Vector(-40.0000, 19.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-37.0000, 19.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-35.9749, 21.9749, 0)
	P005 = App.Vector(-33.5000, 23.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-33.5000, 26.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa14():
	FC000 = ctr_face_armJoint_faceSection_Fa14_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa15_Ctr0():
	P000 = App.Vector(-40.0000, 19.5000, 0)
	P001 = App.Vector(-40.0000, -19.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-37.0000, -19.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-37.0000, 19.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, 19.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa15():
	FC000 = ctr_face_armJoint_faceSection_Fa15_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armJoint_faceSection_Fa16_Ctr0():
	P000 = App.Vector(-40.0000, -19.5000, 0)
	P001 = App.Vector(-38.0962, -24.0962, 0)
	P002 = App.Vector(-33.5000, -26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-33.5000, -23.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-35.9749, -21.9749, 0)
	P005 = App.Vector(-37.0000, -19.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-40.0000, -19.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armJoint_faceSection_Fa16():
	FC000 = ctr_face_armJoint_faceSection_Fa16_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armJoint_faceSection():
	FA000 = face_armJoint_faceSection_Fa0()
	FA001 = face_armJoint_faceSection_Fa1()
	FA002 = face_armJoint_faceSection_Fa2()
	FA003 = face_armJoint_faceSection_Fa3()
	FA004 = face_armJoint_faceSection_Fa4()
	FA005 = face_armJoint_faceSection_Fa5()
	FA006 = face_armJoint_faceSection_Fa6()
	FA007 = face_armJoint_faceSection_Fa7()
	FA008 = face_armJoint_faceSection_Fa8()
	FA009 = face_armJoint_faceSection_Fa9()
	FA010 = face_armJoint_faceSection_Fa10()
	FA011 = face_armJoint_faceSection_Fa11()
	FA012 = face_armJoint_faceSection_Fa12()
	FA013 = face_armJoint_faceSection_Fa13()
	FA014 = face_armJoint_faceSection_Fa14()
	FA015 = face_armJoint_faceSection_Fa15()
	FA016 = face_armJoint_faceSection_Fa16()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011, FA012, FA013, FA014, FA015, FA016])
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_faceSide_Fa0_Ctr0():
	P000 = App.Vector(-43.5000, 0.0000, 0)
	P001 = App.Vector(43.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(43.5000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(90.2595, 117.1253, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 290.0000, 0)
	P005 = App.Vector(-90.2595, 117.1253, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-43.5000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-43.5000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_faceSide_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_faceSide_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_faceSide_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 65.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd1_faceSide_Fa0():
	FC000 = ctr_face_armEnd1_faceSide_Fa0_Ctr0()
	FC001 = ctr_face_armEnd1_faceSide_Fa0_Ctr1()
	FC002 = ctr_face_armEnd1_faceSide_Fa0_Ctr2()
	FC003 = ctr_face_armEnd1_faceSide_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armEnd1_faceSide():
	FA000 = face_armEnd1_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_faceTop_Fa0_Ctr0():
	P000 = App.Vector(-23.5000, 0.0000, 0)
	P001 = App.Vector(23.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(23.5000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-23.5000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-23.5000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_faceTop_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd1_faceTop_Fa0():
	FC000 = ctr_face_armEnd1_faceTop_Fa0_Ctr0()
	FC001 = ctr_face_armEnd1_faceTop_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd1_faceTop_Fa1_Ctr0():
	P000 = App.Vector(-30.0000, 0.0000, 0)
	P001 = App.Vector(-27.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-27.0000, 290.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-30.0000, 290.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-30.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_faceTop_Fa1():
	FC000 = ctr_face_armEnd1_faceTop_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd1_faceTop_Fa2_Ctr0():
	P000 = App.Vector(27.0000, 0.0000, 0)
	P001 = App.Vector(30.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(30.0000, 290.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(27.0000, 290.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(27.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_faceTop_Fa2():
	FC000 = ctr_face_armEnd1_faceTop_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd1_faceTop():
	FA000 = face_armEnd1_faceTop_Fa0()
	FA001 = face_armEnd1_faceTop_Fa1()
	FA002 = face_armEnd1_faceTop_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr0():
	P000 = App.Vector(-43.5000, 0.0000, 0)
	P001 = App.Vector(43.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(51.3540, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(98.3540, -0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(106.2080, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(193.2080, -0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(201.0619, 0.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(248.0619, -0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(255.9159, -0.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(255.9159, 50.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(248.0619, 50.0000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(201.0619, 50.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(193.2080, 50.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(239.9674, 117.1253, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(149.7080, 290.0000, 0)
	P015 = App.Vector(59.4485, 117.1253, 0)
	S013 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(106.2080, 50.0000, 0)
	S014 = Part.LineSegment(P015, P016)
	P017 = App.Vector(98.3540, 50.0000, 0)
	S015 = Part.LineSegment(P016, P017)
	P018 = App.Vector(51.3540, 50.0000, 0)
	S016 = Part.LineSegment(P017, P018)
	P019 = App.Vector(43.5000, 50.0000, 0)
	S017 = Part.LineSegment(P018, P019)
	P020 = App.Vector(90.2595, 117.1253, 0)
	S018 = Part.LineSegment(P019, P020)
	P021 = App.Vector(0.0000, 290.0000, 0)
	P022 = App.Vector(-90.2595, 117.1253, 0)
	S019 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-43.5000, 50.0000, 0)
	S020 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-43.5000, 0.0000, 0)
	S021 = Part.LineSegment(P023, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr1():
	P000 = App.Vector(-43.5000, 0.0000, 0)
	P001 = App.Vector(43.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(51.3540, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(98.3540, -0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(106.2080, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(193.2080, -0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(201.0619, 0.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(248.0619, -0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(255.9159, -0.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(255.9159, 50.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(248.0619, 50.0000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(201.0619, 50.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(193.2080, 50.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(239.9674, 117.1253, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(149.7080, 290.0000, 0)
	P015 = App.Vector(59.4485, 117.1253, 0)
	S013 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(106.2080, 50.0000, 0)
	S014 = Part.LineSegment(P015, P016)
	P017 = App.Vector(98.3540, 50.0000, 0)
	S015 = Part.LineSegment(P016, P017)
	P018 = App.Vector(51.3540, 50.0000, 0)
	S016 = Part.LineSegment(P017, P018)
	P019 = App.Vector(43.5000, 50.0000, 0)
	S017 = Part.LineSegment(P018, P019)
	P020 = App.Vector(90.2595, 117.1253, 0)
	S018 = Part.LineSegment(P019, P020)
	P021 = App.Vector(0.0000, 290.0000, 0)
	P022 = App.Vector(-90.2595, 117.1253, 0)
	S019 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-43.5000, 50.0000, 0)
	S020 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-43.5000, 0.0000, 0)
	S021 = Part.LineSegment(P023, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 65.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(74.8540, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(149.7080, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(149.7080, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(149.7080, 65.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(224.5619, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr10():
	P000 = App.Vector(50.3540, 24.0000, 0)
	P001 = App.Vector(51.3540, 25.0000, 0)
	P002 = App.Vector(50.3540, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(44.5000, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(43.5000, 25.0000, 0)
	P005 = App.Vector(44.5000, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(50.3540, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr11():
	P000 = App.Vector(105.2080, 24.0000, 0)
	P001 = App.Vector(106.2080, 25.0000, 0)
	P002 = App.Vector(105.2080, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(99.3540, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(98.3540, 25.0000, 0)
	P005 = App.Vector(99.3540, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(105.2080, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr12():
	P000 = App.Vector(200.0619, 24.0000, 0)
	P001 = App.Vector(201.0619, 25.0000, 0)
	P002 = App.Vector(200.0619, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(194.2080, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(193.2080, 25.0000, 0)
	P005 = App.Vector(194.2080, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(200.0619, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_SFG_pattern_Fa0_Ctr13():
	P000 = App.Vector(254.9159, 24.0000, 0)
	P001 = App.Vector(255.9159, 25.0000, 0)
	P002 = App.Vector(254.9159, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(249.0619, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(248.0619, 25.0000, 0)
	P005 = App.Vector(249.0619, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(254.9159, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_pattern_Fa0():
	FC000 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr0()
	FC001 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr1()
	FC002 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr2()
	FC003 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr3()
	FC004 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr4()
	FC005 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr5()
	FC006 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr6()
	FC007 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr7()
	FC008 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr8()
	FC009 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr9()
	FC010 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr10()
	FC011 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr11()
	FC012 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr12()
	FC013 = ctr_face_armEnd1_SFG_pattern_Fa0_Ctr13()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013])
	rOneFace.check()
	return rOneFace

def armEnd1_SFG_pattern():
	FA000 = face_armEnd1_SFG_pattern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_SFG_profiles_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(87.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(87.0000, 3.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_profiles_Fa0():
	FC000 = ctr_face_armEnd1_SFG_profiles_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd1_SFG_profiles_Fa1_Ctr0():
	P000 = App.Vector(87.0000, 0.0000, 0)
	P001 = App.Vector(91.5962, 1.9038, 0)
	P002 = App.Vector(93.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(90.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(89.4749, 4.0251, 0)
	P005 = App.Vector(87.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(87.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_profiles_Fa1():
	FC000 = ctr_face_armEnd1_SFG_profiles_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd1_SFG_profiles_Fa2_Ctr0():
	P000 = App.Vector(93.5000, 6.5000, 0)
	P001 = App.Vector(93.5000, 53.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(90.5000, 53.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(90.5000, 6.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(93.5000, 6.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_profiles_Fa2():
	FC000 = ctr_face_armEnd1_SFG_profiles_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd1_SFG_profiles_Fa3_Ctr0():
	P000 = App.Vector(93.5000, 53.5000, 0)
	P001 = App.Vector(91.5962, 58.0962, 0)
	P002 = App.Vector(87.0000, 60.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(87.0000, 57.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(89.4749, 55.9749, 0)
	P005 = App.Vector(90.5000, 53.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(93.5000, 53.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_profiles_Fa3():
	FC000 = ctr_face_armEnd1_SFG_profiles_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd1_SFG_profiles_Fa4_Ctr0():
	P000 = App.Vector(87.0000, 60.0000, 0)
	P001 = App.Vector(0.0000, 60.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 57.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(87.0000, 57.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(87.0000, 60.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_profiles_Fa4():
	FC000 = ctr_face_armEnd1_SFG_profiles_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd1_SFG_profiles_Fa5_Ctr0():
	P000 = App.Vector(0.0000, 60.0000, 0)
	P001 = App.Vector(-4.5962, 58.0962, 0)
	P002 = App.Vector(-6.5000, 53.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-3.5000, 53.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-2.4749, 55.9749, 0)
	P005 = App.Vector(-0.0000, 57.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 60.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_profiles_Fa5():
	FC000 = ctr_face_armEnd1_SFG_profiles_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd1_SFG_profiles_Fa6_Ctr0():
	P000 = App.Vector(-6.5000, 53.5000, 0)
	P001 = App.Vector(-6.5000, 6.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-3.5000, 53.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-6.5000, 53.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_profiles_Fa6():
	FC000 = ctr_face_armEnd1_SFG_profiles_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd1_SFG_profiles_Fa7_Ctr0():
	P000 = App.Vector(-6.5000, 6.5000, 0)
	P001 = App.Vector(-4.5962, 1.9038, 0)
	P002 = App.Vector(-0.0000, 0.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-0.0000, 3.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-2.4749, 4.0251, 0)
	P005 = App.Vector(-3.5000, 6.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-6.5000, 6.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_profiles_Fa7():
	FC000 = ctr_face_armEnd1_SFG_profiles_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd1_SFG_profiles():
	FA000 = face_armEnd1_SFG_profiles_Fa0()
	FA001 = face_armEnd1_SFG_profiles_Fa1()
	FA002 = face_armEnd1_SFG_profiles_Fa2()
	FA003 = face_armEnd1_SFG_profiles_Fa3()
	FA004 = face_armEnd1_SFG_profiles_Fa4()
	FA005 = face_armEnd1_SFG_profiles_Fa5()
	FA006 = face_armEnd1_SFG_profiles_Fa6()
	FA007 = face_armEnd1_SFG_profiles_Fa7()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007])
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_SFG_f00_Fa0_Ctr0():
	P000 = App.Vector(-43.5000, 0.0000, 0)
	P001 = App.Vector(43.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(43.5000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(90.2595, 117.1253, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 290.0000, 0)
	P005 = App.Vector(-90.2595, 117.1253, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-43.5000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-43.5000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_SFG_f00_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_f00_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(0.0000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_f00_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 65.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd1_SFG_f00_Fa0():
	FC000 = ctr_face_armEnd1_SFG_f00_Fa0_Ctr0()
	FC001 = ctr_face_armEnd1_SFG_f00_Fa0_Ctr1()
	FC002 = ctr_face_armEnd1_SFG_f00_Fa0_Ctr2()
	FC003 = ctr_face_armEnd1_SFG_f00_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armEnd1_SFG_f00():
	FA000 = face_armEnd1_SFG_f00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_SFG_f01_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(47.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(47.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_SFG_f01_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(23.5000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd1_SFG_f01_Fa0():
	FC000 = ctr_face_armEnd1_SFG_f01_Fa0_Ctr0()
	FC001 = ctr_face_armEnd1_SFG_f01_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def armEnd1_SFG_f01():
	FA000 = face_armEnd1_SFG_f01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_SFG_f02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(87.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(87.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(133.7595, 117.1253, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(43.5000, 290.0000, 0)
	P005 = App.Vector(-46.7595, 117.1253, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(0.0000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_SFG_f02_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(43.5000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_f02_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(43.5000, 180.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd1_SFG_f02_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(43.5000, 65.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd1_SFG_f02_Fa0():
	FC000 = ctr_face_armEnd1_SFG_f02_Fa0_Ctr0()
	FC001 = ctr_face_armEnd1_SFG_f02_Fa0_Ctr1()
	FC002 = ctr_face_armEnd1_SFG_f02_Fa0_Ctr2()
	FC003 = ctr_face_armEnd1_SFG_f02_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armEnd1_SFG_f02():
	FA000 = face_armEnd1_SFG_f02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_SFG_f03_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(47.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(47.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd1_SFG_f03_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(23.5000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd1_SFG_f03_Fa0():
	FC000 = ctr_face_armEnd1_SFG_f03_Fa0_Ctr0()
	FC001 = ctr_face_armEnd1_SFG_f03_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def armEnd1_SFG_f03():
	FA000 = face_armEnd1_SFG_f03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_SFG_fj00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_fj00_Fa0():
	FC000 = ctr_face_armEnd1_SFG_fj00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd1_SFG_fj00():
	FA000 = face_armEnd1_SFG_fj00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_SFG_fj01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_fj01_Fa0():
	FC000 = ctr_face_armEnd1_SFG_fj01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd1_SFG_fj01():
	FA000 = face_armEnd1_SFG_fj01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_SFG_fj02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_fj02_Fa0():
	FC000 = ctr_face_armEnd1_SFG_fj02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd1_SFG_fj02():
	FA000 = face_armEnd1_SFG_fj02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd1_SFG_fj03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd1_SFG_fj03_Fa0():
	FC000 = ctr_face_armEnd1_SFG_fj03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd1_SFG_fj03():
	FA000 = face_armEnd1_SFG_fj03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_armEnd1_SFG_f00():
	FIG = armEnd1_SFG_f00()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_armEnd1_SFG_f00 = fex_subpax_armEnd1_SFG_f00()

def fex_subpax_armEnd1_SFG_f01():
	FIG = armEnd1_SFG_f01()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(50.0000, -0.0000, 6.5000))
	return VFP
subpax_armEnd1_SFG_f01 = fex_subpax_armEnd1_SFG_f01()

def fex_subpax_armEnd1_SFG_f02():
	FIG = armEnd1_SFG_f02()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -180.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(43.5000, 0.0000, 60.0000))
	return VFP
subpax_armEnd1_SFG_f02 = fex_subpax_armEnd1_SFG_f02()

def fex_subpax_armEnd1_SFG_f03():
	FIG = armEnd1_SFG_f03()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-50.0000, 0.0000, 53.5000))
	return VFP
subpax_armEnd1_SFG_f03 = fex_subpax_armEnd1_SFG_f03()

def fex_subpax_armEnd1_SFG_fj00():
	FIG = armEnd1_SFG_fj00()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(43.5000, 50.0000, 0.0000))
	return VFP
subpax_armEnd1_SFG_fj00 = fex_subpax_armEnd1_SFG_fj00()

def fex_subpax_armEnd1_SFG_fj01():
	FIG = armEnd1_SFG_fj01()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(50.0000, 50.0000, 53.5000))
	return VFP
subpax_armEnd1_SFG_fj01 = fex_subpax_armEnd1_SFG_fj01()

def fex_subpax_armEnd1_SFG_fj02():
	FIG = armEnd1_SFG_fj02()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(-43.5000, 50.0000, 60.0000))
	return VFP
subpax_armEnd1_SFG_fj02 = fex_subpax_armEnd1_SFG_fj02()

def fex_subpax_armEnd1_SFG_fj03():
	FIG = armEnd1_SFG_fj03()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-50.0000, 50.0000, 6.5000))
	return VFP
subpax_armEnd1_SFG_fj03 = fex_subpax_armEnd1_SFG_fj03()

def fvol_pax_armEnd1():
	V000 = subpax_armEnd1_SFG_f00
	V001 = V000.fuse(subpax_armEnd1_SFG_f01)
	V002 = V001.fuse(subpax_armEnd1_SFG_f02)
	V003 = V002.fuse(subpax_armEnd1_SFG_f03)
	V004 = V003.fuse(subpax_armEnd1_SFG_fj00)
	V005 = V004.fuse(subpax_armEnd1_SFG_fj01)
	V006 = V005.fuse(subpax_armEnd1_SFG_fj02)
	V007 = V006.fuse(subpax_armEnd1_SFG_fj03)
	VFC = V007.removeSplitter()
	return VFC
pax_armEnd1 = fvol_pax_armEnd1()

def ctr_face_armEnd2_faceSide_Fa0_Ctr0():
	P000 = App.Vector(-33.5000, 0.0000, 0)
	P001 = App.Vector(33.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(33.5000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(75.8621, 90.3448, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 280.0000, 0)
	P005 = App.Vector(-75.8621, 90.3448, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-33.5000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-33.5000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_faceSide_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_faceSide_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(0.0000, 170.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_faceSide_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 60.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd2_faceSide_Fa0():
	FC000 = ctr_face_armEnd2_faceSide_Fa0_Ctr0()
	FC001 = ctr_face_armEnd2_faceSide_Fa0_Ctr1()
	FC002 = ctr_face_armEnd2_faceSide_Fa0_Ctr2()
	FC003 = ctr_face_armEnd2_faceSide_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armEnd2_faceSide():
	FA000 = face_armEnd2_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_faceTop_Fa0_Ctr0():
	P000 = App.Vector(-19.5000, 0.0000, 0)
	P001 = App.Vector(19.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(19.5000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-19.5000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-19.5000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_faceTop_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd2_faceTop_Fa0():
	FC000 = ctr_face_armEnd2_faceTop_Fa0_Ctr0()
	FC001 = ctr_face_armEnd2_faceTop_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd2_faceTop_Fa1_Ctr0():
	P000 = App.Vector(-26.0000, 0.0000, 0)
	P001 = App.Vector(-23.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-23.0000, 280.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-26.0000, 280.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-26.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_faceTop_Fa1():
	FC000 = ctr_face_armEnd2_faceTop_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd2_faceTop_Fa2_Ctr0():
	P000 = App.Vector(23.0000, 0.0000, 0)
	P001 = App.Vector(26.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(26.0000, 280.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(23.0000, 280.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(23.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_faceTop_Fa2():
	FC000 = ctr_face_armEnd2_faceTop_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd2_faceTop():
	FA000 = face_armEnd2_faceTop_Fa0()
	FA001 = face_armEnd2_faceTop_Fa1()
	FA002 = face_armEnd2_faceTop_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr0():
	P000 = App.Vector(-33.5000, 0.0000, 0)
	P001 = App.Vector(33.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(41.3540, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(80.3540, -0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(88.2080, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(155.2080, -0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(163.0619, 0.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(202.0619, -0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(209.9159, -0.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(209.9159, 50.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(202.0619, 50.0000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(163.0619, 50.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(155.2080, 50.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(197.5700, 90.3448, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(121.7080, 280.0000, 0)
	P015 = App.Vector(45.8459, 90.3448, 0)
	S013 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(88.2080, 50.0000, 0)
	S014 = Part.LineSegment(P015, P016)
	P017 = App.Vector(80.3540, 50.0000, 0)
	S015 = Part.LineSegment(P016, P017)
	P018 = App.Vector(41.3540, 50.0000, 0)
	S016 = Part.LineSegment(P017, P018)
	P019 = App.Vector(33.5000, 50.0000, 0)
	S017 = Part.LineSegment(P018, P019)
	P020 = App.Vector(75.8621, 90.3448, 0)
	S018 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-0.0000, 280.0000, 0)
	P022 = App.Vector(-75.8621, 90.3448, 0)
	S019 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-33.5000, 50.0000, 0)
	S020 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-33.5000, 0.0000, 0)
	S021 = Part.LineSegment(P023, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr1():
	P000 = App.Vector(-33.5000, 0.0000, 0)
	P001 = App.Vector(33.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(41.3540, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(80.3540, -0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(88.2080, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(155.2080, -0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(163.0619, 0.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(202.0619, -0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(209.9159, -0.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(209.9159, 50.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(202.0619, 50.0000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(163.0619, 50.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(155.2080, 50.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(197.5700, 90.3448, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(121.7080, 280.0000, 0)
	P015 = App.Vector(45.8459, 90.3448, 0)
	S013 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(88.2080, 50.0000, 0)
	S014 = Part.LineSegment(P015, P016)
	P017 = App.Vector(80.3540, 50.0000, 0)
	S015 = Part.LineSegment(P016, P017)
	P018 = App.Vector(41.3540, 50.0000, 0)
	S016 = Part.LineSegment(P017, P018)
	P019 = App.Vector(33.5000, 50.0000, 0)
	S017 = Part.LineSegment(P018, P019)
	P020 = App.Vector(75.8621, 90.3448, 0)
	S018 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-0.0000, 280.0000, 0)
	P022 = App.Vector(-75.8621, 90.3448, 0)
	S019 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-33.5000, 50.0000, 0)
	S020 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-33.5000, 0.0000, 0)
	S021 = Part.LineSegment(P023, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(0.0000, 170.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 60.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(60.8540, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(121.7080, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(121.7080, 170.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(121.7080, 60.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(182.5619, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr10():
	P000 = App.Vector(40.3540, 24.0000, 0)
	P001 = App.Vector(41.3540, 25.0000, 0)
	P002 = App.Vector(40.3540, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(34.5000, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(33.5000, 25.0000, 0)
	P005 = App.Vector(34.5000, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(40.3540, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr11():
	P000 = App.Vector(87.2080, 24.0000, 0)
	P001 = App.Vector(88.2080, 25.0000, 0)
	P002 = App.Vector(87.2080, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(81.3540, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(80.3540, 25.0000, 0)
	P005 = App.Vector(81.3540, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(87.2080, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr12():
	P000 = App.Vector(162.0619, 24.0000, 0)
	P001 = App.Vector(163.0619, 25.0000, 0)
	P002 = App.Vector(162.0619, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(156.2080, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(155.2080, 25.0000, 0)
	P005 = App.Vector(156.2080, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(162.0619, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_SFG_pattern_Fa0_Ctr13():
	P000 = App.Vector(208.9159, 24.0000, 0)
	P001 = App.Vector(209.9159, 25.0000, 0)
	P002 = App.Vector(208.9159, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(203.0619, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(202.0619, 25.0000, 0)
	P005 = App.Vector(203.0619, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(208.9159, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_pattern_Fa0():
	FC000 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr0()
	FC001 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr1()
	FC002 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr2()
	FC003 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr3()
	FC004 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr4()
	FC005 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr5()
	FC006 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr6()
	FC007 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr7()
	FC008 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr8()
	FC009 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr9()
	FC010 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr10()
	FC011 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr11()
	FC012 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr12()
	FC013 = ctr_face_armEnd2_SFG_pattern_Fa0_Ctr13()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013])
	rOneFace.check()
	return rOneFace

def armEnd2_SFG_pattern():
	FA000 = face_armEnd2_SFG_pattern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_SFG_profiles_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(67.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(67.0000, 3.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_profiles_Fa0():
	FC000 = ctr_face_armEnd2_SFG_profiles_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd2_SFG_profiles_Fa1_Ctr0():
	P000 = App.Vector(67.0000, 0.0000, 0)
	P001 = App.Vector(71.5962, 1.9038, 0)
	P002 = App.Vector(73.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(70.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(69.4749, 4.0251, 0)
	P005 = App.Vector(67.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(67.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_profiles_Fa1():
	FC000 = ctr_face_armEnd2_SFG_profiles_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd2_SFG_profiles_Fa2_Ctr0():
	P000 = App.Vector(73.5000, 6.5000, 0)
	P001 = App.Vector(73.5000, 45.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(70.5000, 45.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(70.5000, 6.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(73.5000, 6.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_profiles_Fa2():
	FC000 = ctr_face_armEnd2_SFG_profiles_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd2_SFG_profiles_Fa3_Ctr0():
	P000 = App.Vector(73.5000, 45.5000, 0)
	P001 = App.Vector(71.5962, 50.0962, 0)
	P002 = App.Vector(67.0000, 52.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(67.0000, 49.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(69.4749, 47.9749, 0)
	P005 = App.Vector(70.5000, 45.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(73.5000, 45.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_profiles_Fa3():
	FC000 = ctr_face_armEnd2_SFG_profiles_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd2_SFG_profiles_Fa4_Ctr0():
	P000 = App.Vector(67.0000, 52.0000, 0)
	P001 = App.Vector(0.0000, 52.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 49.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(67.0000, 49.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(67.0000, 52.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_profiles_Fa4():
	FC000 = ctr_face_armEnd2_SFG_profiles_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd2_SFG_profiles_Fa5_Ctr0():
	P000 = App.Vector(0.0000, 52.0000, 0)
	P001 = App.Vector(-4.5962, 50.0962, 0)
	P002 = App.Vector(-6.5000, 45.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-3.5000, 45.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-2.4749, 47.9749, 0)
	P005 = App.Vector(-0.0000, 49.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 52.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_profiles_Fa5():
	FC000 = ctr_face_armEnd2_SFG_profiles_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd2_SFG_profiles_Fa6_Ctr0():
	P000 = App.Vector(-6.5000, 45.5000, 0)
	P001 = App.Vector(-6.5000, 6.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-3.5000, 45.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-6.5000, 45.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_profiles_Fa6():
	FC000 = ctr_face_armEnd2_SFG_profiles_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armEnd2_SFG_profiles_Fa7_Ctr0():
	P000 = App.Vector(-6.5000, 6.5000, 0)
	P001 = App.Vector(-4.5962, 1.9038, 0)
	P002 = App.Vector(-0.0000, 0.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-0.0000, 3.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-2.4749, 4.0251, 0)
	P005 = App.Vector(-3.5000, 6.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-6.5000, 6.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_profiles_Fa7():
	FC000 = ctr_face_armEnd2_SFG_profiles_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd2_SFG_profiles():
	FA000 = face_armEnd2_SFG_profiles_Fa0()
	FA001 = face_armEnd2_SFG_profiles_Fa1()
	FA002 = face_armEnd2_SFG_profiles_Fa2()
	FA003 = face_armEnd2_SFG_profiles_Fa3()
	FA004 = face_armEnd2_SFG_profiles_Fa4()
	FA005 = face_armEnd2_SFG_profiles_Fa5()
	FA006 = face_armEnd2_SFG_profiles_Fa6()
	FA007 = face_armEnd2_SFG_profiles_Fa7()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007])
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_SFG_f00_Fa0_Ctr0():
	P000 = App.Vector(-33.5000, 0.0000, 0)
	P001 = App.Vector(33.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(33.5000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(75.8621, 90.3448, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 280.0000, 0)
	P005 = App.Vector(-75.8621, 90.3448, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-33.5000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-33.5000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_SFG_f00_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_f00_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(0.0000, 170.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_f00_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 60.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd2_SFG_f00_Fa0():
	FC000 = ctr_face_armEnd2_SFG_f00_Fa0_Ctr0()
	FC001 = ctr_face_armEnd2_SFG_f00_Fa0_Ctr1()
	FC002 = ctr_face_armEnd2_SFG_f00_Fa0_Ctr2()
	FC003 = ctr_face_armEnd2_SFG_f00_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armEnd2_SFG_f00():
	FA000 = face_armEnd2_SFG_f00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_SFG_f01_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(39.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(39.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_SFG_f01_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(19.5000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd2_SFG_f01_Fa0():
	FC000 = ctr_face_armEnd2_SFG_f01_Fa0_Ctr0()
	FC001 = ctr_face_armEnd2_SFG_f01_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def armEnd2_SFG_f01():
	FA000 = face_armEnd2_SFG_f01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_SFG_f02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(67.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(67.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(109.3621, 90.3448, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(33.5000, 280.0000, 0)
	P005 = App.Vector(-42.3621, 90.3448, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(0.0000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_SFG_f02_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(33.5000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_f02_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(33.5000, 170.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armEnd2_SFG_f02_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(33.5000, 60.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd2_SFG_f02_Fa0():
	FC000 = ctr_face_armEnd2_SFG_f02_Fa0_Ctr0()
	FC001 = ctr_face_armEnd2_SFG_f02_Fa0_Ctr1()
	FC002 = ctr_face_armEnd2_SFG_f02_Fa0_Ctr2()
	FC003 = ctr_face_armEnd2_SFG_f02_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armEnd2_SFG_f02():
	FA000 = face_armEnd2_SFG_f02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_SFG_f03_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(39.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(39.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armEnd2_SFG_f03_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(19.5000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armEnd2_SFG_f03_Fa0():
	FC000 = ctr_face_armEnd2_SFG_f03_Fa0_Ctr0()
	FC001 = ctr_face_armEnd2_SFG_f03_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def armEnd2_SFG_f03():
	FA000 = face_armEnd2_SFG_f03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_SFG_fj00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_fj00_Fa0():
	FC000 = ctr_face_armEnd2_SFG_fj00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd2_SFG_fj00():
	FA000 = face_armEnd2_SFG_fj00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_SFG_fj01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_fj01_Fa0():
	FC000 = ctr_face_armEnd2_SFG_fj01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd2_SFG_fj01():
	FA000 = face_armEnd2_SFG_fj01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_SFG_fj02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_fj02_Fa0():
	FC000 = ctr_face_armEnd2_SFG_fj02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd2_SFG_fj02():
	FA000 = face_armEnd2_SFG_fj02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armEnd2_SFG_fj03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armEnd2_SFG_fj03_Fa0():
	FC000 = ctr_face_armEnd2_SFG_fj03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armEnd2_SFG_fj03():
	FA000 = face_armEnd2_SFG_fj03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_armEnd2_SFG_f00():
	FIG = armEnd2_SFG_f00()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_armEnd2_SFG_f00 = fex_subpax_armEnd2_SFG_f00()

def fex_subpax_armEnd2_SFG_f01():
	FIG = armEnd2_SFG_f01()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(40.0000, -0.0000, 6.5000))
	return VFP
subpax_armEnd2_SFG_f01 = fex_subpax_armEnd2_SFG_f01()

def fex_subpax_armEnd2_SFG_f02():
	FIG = armEnd2_SFG_f02()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -180.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(33.5000, 0.0000, 52.0000))
	return VFP
subpax_armEnd2_SFG_f02 = fex_subpax_armEnd2_SFG_f02()

def fex_subpax_armEnd2_SFG_f03():
	FIG = armEnd2_SFG_f03()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-40.0000, 0.0000, 45.5000))
	return VFP
subpax_armEnd2_SFG_f03 = fex_subpax_armEnd2_SFG_f03()

def fex_subpax_armEnd2_SFG_fj00():
	FIG = armEnd2_SFG_fj00()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(33.5000, 50.0000, 0.0000))
	return VFP
subpax_armEnd2_SFG_fj00 = fex_subpax_armEnd2_SFG_fj00()

def fex_subpax_armEnd2_SFG_fj01():
	FIG = armEnd2_SFG_fj01()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(40.0000, 50.0000, 45.5000))
	return VFP
subpax_armEnd2_SFG_fj01 = fex_subpax_armEnd2_SFG_fj01()

def fex_subpax_armEnd2_SFG_fj02():
	FIG = armEnd2_SFG_fj02()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(-33.5000, 50.0000, 52.0000))
	return VFP
subpax_armEnd2_SFG_fj02 = fex_subpax_armEnd2_SFG_fj02()

def fex_subpax_armEnd2_SFG_fj03():
	FIG = armEnd2_SFG_fj03()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-40.0000, 50.0000, 6.5000))
	return VFP
subpax_armEnd2_SFG_fj03 = fex_subpax_armEnd2_SFG_fj03()

def fvol_pax_armEnd2():
	V000 = subpax_armEnd2_SFG_f00
	V001 = V000.fuse(subpax_armEnd2_SFG_f01)
	V002 = V001.fuse(subpax_armEnd2_SFG_f02)
	V003 = V002.fuse(subpax_armEnd2_SFG_f03)
	V004 = V003.fuse(subpax_armEnd2_SFG_fj00)
	V005 = V004.fuse(subpax_armEnd2_SFG_fj01)
	V006 = V005.fuse(subpax_armEnd2_SFG_fj02)
	V007 = V006.fuse(subpax_armEnd2_SFG_fj03)
	VFC = V007.removeSplitter()
	return VFC
pax_armEnd2 = fvol_pax_armEnd2()

def ctr_face_armAxis_faceAxis_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(100.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armAxis_faceAxis_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(97.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armAxis_faceAxis_Fa0():
	FC000 = ctr_face_armAxis_faceAxis_Fa0_Ctr0()
	FC001 = ctr_face_armAxis_faceAxis_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def armAxis_faceAxis():
	FA000 = face_armAxis_faceAxis_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armAxis_faceHoleS_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armAxis_faceHoleS_Fa0():
	FC000 = ctr_face_armAxis_faceHoleS_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armAxis_faceHoleS():
	FA000 = face_armAxis_faceHoleS_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armAxis_faceHoleL_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armAxis_faceHoleL_Fa0():
	FC000 = ctr_face_armAxis_faceHoleL_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armAxis_faceHoleL():
	FA000 = face_armAxis_faceHoleL_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_armAxis_Axis():
	FIG = armAxis_faceAxis()
	VEX = FIG.extrude(App.Vector(0, 0, 60))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_armAxis_Axis = fex_subpax_armAxis_Axis()

def fex_subpax_armAxis_HoleS():
	FIG = armAxis_faceHoleS()
	VEX = FIG.extrude(App.Vector(0, 0, 400))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 30.0000))
	return VFP
subpax_armAxis_HoleS = fex_subpax_armAxis_HoleS()

def fex_subpax_armAxis_HoleL():
	FIG = armAxis_faceHoleL()
	VEX = FIG.extrude(App.Vector(0, 0, 400))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-100.0000, -200.0000, 30.0000))
	return VFP
subpax_armAxis_HoleL = fex_subpax_armAxis_HoleL()

def fvol_pax_armAxis():
	V000 = subpax_armAxis_Axis
	V001 = V000.cut(subpax_armAxis_HoleS)
	V002 = V001.cut(subpax_armAxis_HoleL)
	VFC = V002.removeSplitter()
	return VFC
pax_armAxis = fvol_pax_armAxis()

def finh_inpax_armJoint_end1():
	IVR1 = pax_armEnd1.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return IVF
inpax_armJoint_end1 = finh_inpax_armJoint_end1()

def finh_inpax_armJoint_end2():
	IVR1 = pax_armEnd2.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -139.0000)
	IVF = IVR3.translate(App.Vector(-111.5300, 308.3006, 4.0000))
	return IVF
inpax_armJoint_end2 = finh_inpax_armJoint_end2()

def finh_inpax_armJoint_axis():
	IVR1 = pax_armAxis.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	IVR2 = IVR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	IVR3 = IVR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 131.0000)
	IVF = IVR3.translate(App.Vector(0.0000, 180.0000, 0.0000))
	return IVF
inpax_armJoint_axis = finh_inpax_armJoint_axis()

def fvol_pax_armJoint():
	V000 = inpax_armJoint_end1
	V001 = V000.fuse(inpax_armJoint_end2)
	V002 = V001.fuse(inpax_armJoint_axis)
	VFC = V002.removeSplitter()
	return VFC
pax_armJoint = fvol_pax_armJoint()


pax_armJoint.check()
#pax_armJoint.exportBrep(f"{outFileName}.brep")
#pax_armJoint.exportIges(f"{outFileName}.igs")
#pax_armJoint.exportStep(f"{outFileName}.stp")
pax_armJoint.exportStl(f"{outFileName}.stl")

