# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "sfCheck"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_sfCheck_SFG_pattern_Fa0_Ctr0():
	P000 = App.Vector(-74.2920, -10.0000, 0)
	P001 = App.Vector(125.7080, -10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(125.7080, 90.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-74.2920, 90.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-74.2920, -10.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfCheck_SFG_pattern_Fa0_Ctr1():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(115.7080, -0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(115.7080, -5.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-64.2920, -5.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-64.2920, -0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-48.5841, 0.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-8.5841, 0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-8.5841, 80.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-48.5841, 80.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-64.2920, 80.0000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-64.2920, 85.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(115.7080, 85.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(115.7080, 80.0000, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(100.0000, 80.0000, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(0.0000, 80.0000, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(0.0000, 0.0000, 0)
	S015 = Part.LineSegment(P015, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfCheck_SFG_pattern_Fa0_Ctr2():
	P000 = App.Vector(10.0000, 5.0000, 0)
	P001 = App.Vector(10.0000, 75.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(90.0000, 75.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(90.0000, 70.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(74.2920, 70.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(34.2920, 70.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(34.2920, 10.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(74.2920, 10.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(90.0000, 10.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(90.0000, 5.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(10.0000, 5.0000, 0)
	S009 = Part.LineSegment(P009, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfCheck_SFG_pattern_Fa0_Ctr3():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(115.7080, -0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(115.7080, -5.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-64.2920, -5.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-64.2920, -0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-48.5841, 0.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-8.5841, 0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-8.5841, 80.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(-48.5841, 80.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-64.2920, 80.0000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-64.2920, 85.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(115.7080, 85.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(115.7080, 80.0000, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(100.0000, 80.0000, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(0.0000, 80.0000, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(0.0000, 0.0000, 0)
	S015 = Part.LineSegment(P015, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfCheck_SFG_pattern_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(-28.5841, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfCheck_SFG_pattern_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(54.2920, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfCheck_SFG_pattern_Fa0_Ctr6():
	P000 = App.Vector(114.7080, 39.0000, 0)
	P001 = App.Vector(115.7080, 40.0000, 0)
	P002 = App.Vector(114.7080, 41.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(101.0000, 41.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(100.0000, 40.0000, 0)
	P005 = App.Vector(101.0000, 39.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(114.7080, 39.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfCheck_SFG_pattern_Fa0_Ctr7():
	P000 = App.Vector(89.0000, 39.0000, 0)
	P001 = App.Vector(90.0000, 40.0000, 0)
	P002 = App.Vector(89.0000, 41.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(75.2920, 41.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(74.2920, 40.0000, 0)
	P005 = App.Vector(75.2920, 39.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(89.0000, 39.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfCheck_SFG_pattern_Fa0_Ctr8():
	P000 = App.Vector(-63.2920, 41.0000, 0)
	P001 = App.Vector(-64.2920, 40.0000, 0)
	P002 = App.Vector(-63.2920, 39.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-49.5841, 39.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-48.5841, 40.0000, 0)
	P005 = App.Vector(-49.5841, 41.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-63.2920, 41.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_pattern_Fa0():
	FC000 = ctr_face_sfCheck_SFG_pattern_Fa0_Ctr0()
	FC001 = ctr_face_sfCheck_SFG_pattern_Fa0_Ctr1()
	FC002 = ctr_face_sfCheck_SFG_pattern_Fa0_Ctr2()
	FC003 = ctr_face_sfCheck_SFG_pattern_Fa0_Ctr3()
	FC004 = ctr_face_sfCheck_SFG_pattern_Fa0_Ctr4()
	FC005 = ctr_face_sfCheck_SFG_pattern_Fa0_Ctr5()
	FC006 = ctr_face_sfCheck_SFG_pattern_Fa0_Ctr6()
	FC007 = ctr_face_sfCheck_SFG_pattern_Fa0_Ctr7()
	FC008 = ctr_face_sfCheck_SFG_pattern_Fa0_Ctr8()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008])
	rOneFace.check()
	return rOneFace

def sfCheck_SFG_pattern():
	FA000 = face_sfCheck_SFG_pattern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfCheck_SFG_profiles_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(10.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(10.0000, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_profiles_Fa0():
	FC000 = ctr_face_sfCheck_SFG_profiles_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfCheck_SFG_profiles_Fa1_Ctr0():
	P000 = App.Vector(10.0000, 0.0000, 0)
	P001 = App.Vector(13.5355, -1.4645, 0)
	P002 = App.Vector(15.0000, -5.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(25.0000, -5.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(20.6066, 5.6066, 0)
	P005 = App.Vector(10.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(10.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_profiles_Fa1():
	FC000 = ctr_face_sfCheck_SFG_profiles_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfCheck_SFG_profiles_Fa2_Ctr0():
	P000 = App.Vector(15.0000, -5.0000, 0)
	P001 = App.Vector(15.0000, -15.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, -15.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(25.0000, -5.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(15.0000, -5.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_profiles_Fa2():
	FC000 = ctr_face_sfCheck_SFG_profiles_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfCheck_SFG_profiles_Fa3_Ctr0():
	P000 = App.Vector(0.0000, 10.0000, 0)
	P001 = App.Vector(-3.5355, 11.4645, 0)
	P002 = App.Vector(-5.0000, 15.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-15.0000, 15.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-10.6066, 4.3934, 0)
	P005 = App.Vector(-0.0000, 0.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 10.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_profiles_Fa3():
	FC000 = ctr_face_sfCheck_SFG_profiles_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfCheck_SFG_profiles_Fa4_Ctr0():
	P000 = App.Vector(-5.0000, 15.0000, 0)
	P001 = App.Vector(-5.0000, 55.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-15.0000, 55.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-15.0000, 15.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-5.0000, 15.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_profiles_Fa4():
	FC000 = ctr_face_sfCheck_SFG_profiles_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfCheck_SFG_profiles_Fa5_Ctr0():
	P000 = App.Vector(0.0000, 400.0000, 0)
	P001 = App.Vector(10.0000, 400.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(10.0000, 410.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 410.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 400.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_profiles_Fa5():
	FC000 = ctr_face_sfCheck_SFG_profiles_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfCheck_SFG_profiles_Fa6_Ctr0():
	P000 = App.Vector(10.0000, 400.0000, 0)
	P001 = App.Vector(13.5355, 398.5355, 0)
	P002 = App.Vector(15.0000, 395.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(25.0000, 395.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(20.6066, 405.6066, 0)
	P005 = App.Vector(10.0000, 410.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(10.0000, 400.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_profiles_Fa6():
	FC000 = ctr_face_sfCheck_SFG_profiles_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfCheck_SFG_profiles_Fa7_Ctr0():
	P000 = App.Vector(15.0000, 395.0000, 0)
	P001 = App.Vector(15.0000, 355.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 355.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(25.0000, 395.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(15.0000, 395.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_profiles_Fa7():
	FC000 = ctr_face_sfCheck_SFG_profiles_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfCheck_SFG_profiles():
	FA000 = face_sfCheck_SFG_profiles_Fa0()
	FA001 = face_sfCheck_SFG_profiles_Fa1()
	FA002 = face_sfCheck_SFG_profiles_Fa2()
	FA003 = face_sfCheck_SFG_profiles_Fa3()
	FA004 = face_sfCheck_SFG_profiles_Fa4()
	FA005 = face_sfCheck_SFG_profiles_Fa5()
	FA006 = face_sfCheck_SFG_profiles_Fa6()
	FA007 = face_sfCheck_SFG_profiles_Fa7()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007])
	rOneFig.check()
	return rOneFig

def ctr_face_sfCheck_SFG_f00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(100.0000, 80.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 80.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfCheck_SFG_f00_Fa0_Ctr1():
	P000 = App.Vector(10.0000, 5.0000, 0)
	P001 = App.Vector(90.0000, 5.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(90.0000, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(90.0000, 70.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(90.0000, 75.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(10.0000, 75.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(10.0000, 5.0000, 0)
	S005 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_f00_Fa0():
	FC000 = ctr_face_sfCheck_SFG_f00_Fa0_Ctr0()
	FC001 = ctr_face_sfCheck_SFG_f00_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def sfCheck_SFG_f00():
	FA000 = face_sfCheck_SFG_f00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfCheck_SFG_f01_Fa0_Ctr0():
	P000 = App.Vector(-190.0000, -10.0000, 0)
	P001 = App.Vector(10.0000, -10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(10.0000, 90.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-190.0000, 90.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-190.0000, -10.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfCheck_SFG_f01_Fa0_Ctr1():
	P000 = App.Vector(-180.0000, -5.0000, 0)
	P001 = App.Vector(0.0000, -5.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 80.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 85.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-180.0000, 85.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-180.0000, 80.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-180.0000, 0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-180.0000, -5.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_f01_Fa0():
	FC000 = ctr_face_sfCheck_SFG_f01_Fa0_Ctr0()
	FC001 = ctr_face_sfCheck_SFG_f01_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def sfCheck_SFG_f01():
	FA000 = face_sfCheck_SFG_f01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfCheck_SFG_f02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 80.0000, 0)
	P001 = App.Vector(-40.0000, 80.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-40.0000, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 80.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfCheck_SFG_f02_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(-20.0000, 40.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_sfCheck_SFG_f02_Fa0():
	FC000 = ctr_face_sfCheck_SFG_f02_Fa0_Ctr0()
	FC001 = ctr_face_sfCheck_SFG_f02_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def sfCheck_SFG_f02():
	FA000 = face_sfCheck_SFG_f02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfCheck_SFG_f03_Fa0_Ctr0():
	P000 = App.Vector(-40.0000, 0.0000, 0)
	P001 = App.Vector(0.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 60.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, 60.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfCheck_SFG_f03_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(-20.0000, 30.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_sfCheck_SFG_f03_Fa0():
	FC000 = ctr_face_sfCheck_SFG_f03_Fa0_Ctr0()
	FC001 = ctr_face_sfCheck_SFG_f03_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def sfCheck_SFG_f03():
	FA000 = face_sfCheck_SFG_f03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfCheck_SFG_fj00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(3.5355, -1.4645, 0)
	P002 = App.Vector(5.0000, -5.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(15.0000, -5.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.6066, 5.6066, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_fj00_Fa0():
	FC000 = ctr_face_sfCheck_SFG_fj00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfCheck_SFG_fj00():
	FA000 = face_sfCheck_SFG_fj00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfCheck_SFG_fj01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(10.6066, 4.3934, 0)
	P002 = App.Vector(15.0000, 15.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(5.0000, 15.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(3.5355, 11.4645, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_fj01_Fa0():
	FC000 = ctr_face_sfCheck_SFG_fj01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfCheck_SFG_fj01():
	FA000 = face_sfCheck_SFG_fj01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfCheck_SFG_fj02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(3.5355, -1.4645, 0)
	P002 = App.Vector(5.0000, -5.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(15.0000, -5.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.6066, 5.6066, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfCheck_SFG_fj02_Fa0():
	FC000 = ctr_face_sfCheck_SFG_fj02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfCheck_SFG_fj02():
	FA000 = face_sfCheck_SFG_fj02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_sfCheck_SFG_f00():
	FIG = sfCheck_SFG_f00()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_sfCheck_SFG_f00 = fex_subpax_sfCheck_SFG_f00()

def fex_subpax_sfCheck_SFG_f01():
	FIG = sfCheck_SFG_f01()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(105.0000, -0.0000, -5.0000))
	return VFP
subpax_sfCheck_SFG_f01 = fex_subpax_sfCheck_SFG_f01()

def fex_subpax_sfCheck_SFG_f02():
	FIG = sfCheck_SFG_f02()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -180.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -0.0000)
	VFP = VR3.translate(App.Vector(100.0000, 80.0000, 170.0000))
	return VFP
subpax_sfCheck_SFG_f02 = fex_subpax_sfCheck_SFG_f02()

def fex_subpax_sfCheck_SFG_f03():
	FIG = sfCheck_SFG_f03()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(75.0000, 10.0000, 15.0000))
	return VFP
subpax_sfCheck_SFG_f03 = fex_subpax_sfCheck_SFG_f03()

def fex_subpax_sfCheck_SFG_fj00():
	FIG = sfCheck_SFG_fj00()
	VEX = FIG.extrude(App.Vector(0, 0, 80))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(100.0000, 80.0000, 0.0000))
	return VFP
subpax_sfCheck_SFG_fj00 = fex_subpax_sfCheck_SFG_fj00()

def fex_subpax_sfCheck_SFG_fj01():
	FIG = sfCheck_SFG_fj01()
	VEX = FIG.extrude(App.Vector(0, 0, 60))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(90.0000, 10.0000, 0.0000))
	return VFP
subpax_sfCheck_SFG_fj01 = fex_subpax_sfCheck_SFG_fj01()

def fex_subpax_sfCheck_SFG_fj02():
	FIG = sfCheck_SFG_fj02()
	VEX = FIG.extrude(App.Vector(0, 0, 80))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(105.0000, 80.0000, 175.0000))
	return VFP
subpax_sfCheck_SFG_fj02 = fex_subpax_sfCheck_SFG_fj02()

def fvol_pax_sfCheck():
	V000 = subpax_sfCheck_SFG_f00
	V001 = V000.fuse(subpax_sfCheck_SFG_f01)
	V002 = V001.fuse(subpax_sfCheck_SFG_f02)
	V003 = V002.fuse(subpax_sfCheck_SFG_f03)
	V004 = V003.fuse(subpax_sfCheck_SFG_fj00)
	V005 = V004.fuse(subpax_sfCheck_SFG_fj01)
	V006 = V005.fuse(subpax_sfCheck_SFG_fj02)
	VFC = V006.removeSplitter()
	return VFC
pax_sfCheck = fvol_pax_sfCheck()


pax_sfCheck.check()
#pax_sfCheck.exportBrep(f"{outFileName}.brep")
#pax_sfCheck.exportIges(f"{outFileName}.igs")
#pax_sfCheck.exportStep(f"{outFileName}.stp")
pax_sfCheck.exportStl(f"{outFileName}.stl")

