# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "demoSheetFold"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_demoSheetFold_faceCut_Fa0_Ctr0():
	P000 = App.Vector(10.0000, 0.0000, 0)
	P001 = App.Vector(60.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(60.0000, 80.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(10.0000, 80.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.9289, 77.0711, 0)
	P005 = App.Vector(0.0000, 70.0000, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 10.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(2.9289, 2.9289, 0)
	P008 = App.Vector(10.0000, 0.0000, 0)
	S005 = Part.Arc(P006, P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_faceCut_Fa0():
	FC000 = ctr_face_demoSheetFold_faceCut_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold_faceCut_Fa1_Ctr0():
	P000 = App.Vector(60.0000, 0.0000, 0)
	P001 = App.Vector(70.4720, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(70.4720, 80.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(60.0000, 80.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(60.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_faceCut_Fa1():
	FC000 = ctr_face_demoSheetFold_faceCut_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold_faceCut_Fa2_Ctr0():
	P000 = App.Vector(70.4720, 0.0000, 0)
	P001 = App.Vector(99.7101, 33.4150, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(102.1843, 40.0000, 0)
	P003 = App.Vector(99.7101, 46.5850, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(70.4720, 80.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(70.4720, 0.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_faceCut_Fa2():
	FC000 = ctr_face_demoSheetFold_faceCut_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold_faceCut():
	FA000 = face_demoSheetFold_faceCut_Fa0()
	FA001 = face_demoSheetFold_faceCut_Fa1()
	FA002 = face_demoSheetFold_faceCut_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold_facet1_Fa0_Ctr0():
	P000 = App.Vector(10.0000, 0.0000, 0)
	P001 = App.Vector(60.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(60.0000, 80.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(10.0000, 80.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.9289, 77.0711, 0)
	P005 = App.Vector(0.0000, 70.0000, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 10.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(2.9289, 2.9289, 0)
	P008 = App.Vector(10.0000, 0.0000, 0)
	S005 = Part.Arc(P006, P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_facet1_Fa0():
	FC000 = ctr_face_demoSheetFold_facet1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold_facet1():
	FA000 = face_demoSheetFold_facet1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold_facet3_Fa0_Ctr0():
	P000 = App.Vector(70.4720, 0.0000, 0)
	P001 = App.Vector(99.7101, 33.4150, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(102.1843, 40.0000, 0)
	P003 = App.Vector(99.7101, 46.5850, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(70.4720, 80.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(70.4720, 0.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_facet3_Fa0():
	FC000 = ctr_face_demoSheetFold_facet3_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold_facet3():
	FA000 = face_demoSheetFold_facet3_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold_SFG_pattern_Fa0_Ctr0():
	P000 = App.Vector(10.0000, 0.0000, 0)
	P001 = App.Vector(60.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(70.4720, -0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(99.7101, 33.4150, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(102.1843, 40.0000, 0)
	P005 = App.Vector(99.7101, 46.5850, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(70.4720, 80.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(60.0000, 80.0000, 0)
	S005 = Part.LineSegment(P006, P007)
	P008 = App.Vector(10.0000, 80.0000, 0)
	S006 = Part.LineSegment(P007, P008)
	P009 = App.Vector(2.9289, 77.0711, 0)
	P010 = App.Vector(0.0000, 70.0000, 0)
	S007 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(0.0000, 10.0000, 0)
	S008 = Part.LineSegment(P010, P011)
	P012 = App.Vector(2.9289, 2.9289, 0)
	P013 = App.Vector(10.0000, 0.0000, 0)
	S009 = Part.Arc(P011, P012, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold_SFG_pattern_Fa0_Ctr1():
	P000 = App.Vector(10.0000, 0.0000, 0)
	P001 = App.Vector(60.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(70.4720, -0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(99.7101, 33.4150, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(102.1843, 40.0000, 0)
	P005 = App.Vector(99.7101, 46.5850, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(70.4720, 80.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(60.0000, 80.0000, 0)
	S005 = Part.LineSegment(P006, P007)
	P008 = App.Vector(10.0000, 80.0000, 0)
	S006 = Part.LineSegment(P007, P008)
	P009 = App.Vector(2.9289, 77.0711, 0)
	P010 = App.Vector(0.0000, 70.0000, 0)
	S007 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(0.0000, 10.0000, 0)
	S008 = Part.LineSegment(P010, P011)
	P012 = App.Vector(2.9289, 2.9289, 0)
	P013 = App.Vector(10.0000, 0.0000, 0)
	S009 = Part.Arc(P011, P012, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold_SFG_pattern_Fa0_Ctr2():
	P000 = App.Vector(69.4720, 39.0000, 0)
	P001 = App.Vector(70.4720, 40.0000, 0)
	P002 = App.Vector(69.4720, 41.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(61.0000, 41.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(60.0000, 40.0000, 0)
	P005 = App.Vector(61.0000, 39.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(69.4720, 39.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_SFG_pattern_Fa0():
	FC000 = ctr_face_demoSheetFold_SFG_pattern_Fa0_Ctr0()
	FC001 = ctr_face_demoSheetFold_SFG_pattern_Fa0_Ctr1()
	FC002 = ctr_face_demoSheetFold_SFG_pattern_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def demoSheetFold_SFG_pattern():
	FA000 = face_demoSheetFold_SFG_pattern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold_SFG_profiles_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(60.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(60.0000, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_SFG_profiles_Fa0():
	FC000 = ctr_face_demoSheetFold_SFG_profiles_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold_SFG_profiles_Fa1_Ctr0():
	P000 = App.Vector(60.0000, 0.0000, 0)
	P001 = App.Vector(67.5000, 2.0096, 0)
	P002 = App.Vector(72.9904, 7.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(64.3301, 12.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(62.5000, 10.6699, 0)
	P005 = App.Vector(60.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(60.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_SFG_profiles_Fa1():
	FC000 = ctr_face_demoSheetFold_SFG_profiles_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold_SFG_profiles_Fa2_Ctr0():
	P000 = App.Vector(72.9904, 7.5000, 0)
	P001 = App.Vector(90.4904, 37.8109, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(81.8301, 42.8109, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(64.3301, 12.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(72.9904, 7.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_SFG_profiles_Fa2():
	FC000 = ctr_face_demoSheetFold_SFG_profiles_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold_SFG_profiles():
	FA000 = face_demoSheetFold_SFG_profiles_Fa0()
	FA001 = face_demoSheetFold_SFG_profiles_Fa1()
	FA002 = face_demoSheetFold_SFG_profiles_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold_SFG_f00_Fa0_Ctr0():
	P000 = App.Vector(10.0000, 0.0000, 0)
	P001 = App.Vector(60.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(60.0000, 80.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(10.0000, 80.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.9289, 77.0711, 0)
	P005 = App.Vector(0.0000, 70.0000, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 10.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(2.9289, 2.9289, 0)
	P008 = App.Vector(10.0000, 0.0000, 0)
	S005 = Part.Arc(P006, P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_SFG_f00_Fa0():
	FC000 = ctr_face_demoSheetFold_SFG_f00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold_SFG_f00():
	FA000 = face_demoSheetFold_SFG_f00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold_SFG_f01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(29.2381, 33.4150, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(31.7123, 40.0000, 0)
	P003 = App.Vector(29.2381, 46.5850, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(0.0000, 80.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_SFG_f01_Fa0():
	FC000 = ctr_face_demoSheetFold_SFG_f01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold_SFG_f01():
	FA000 = face_demoSheetFold_SFG_f01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold_SFG_fj00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(7.5000, 2.0096, 0)
	P002 = App.Vector(12.9904, 7.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(4.3301, 12.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.5000, 10.6699, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold_SFG_fj00_Fa0():
	FC000 = ctr_face_demoSheetFold_SFG_fj00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold_SFG_fj00():
	FA000 = face_demoSheetFold_SFG_fj00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_SFG_f00():
	FIG = demoSheetFold_SFG_f00()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_SFG_f00 = fex_subpax_SFG_f00()

def fex_subpax_SFG_f01():
	FIG = demoSheetFold_SFG_f01()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -60.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(72.9904, -0.0000, 7.5000))
	return VFP
subpax_SFG_f01 = fex_subpax_SFG_f01()

def fex_subpax_SFG_fj00():
	FIG = demoSheetFold_SFG_fj00()
	VEX = FIG.extrude(App.Vector(0, 0, 80))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(60.0000, 80.0000, 0.0000))
	return VFP
subpax_SFG_fj00 = fex_subpax_SFG_fj00()

def fvol_pax_demoSheetFold():
	V000 = subpax_SFG_f00
	V001 = V000.fuse(subpax_SFG_f01)
	V002 = V001.fuse(subpax_SFG_fj00)
	VFC = V002.removeSplitter()
	return VFC
pax_demoSheetFold = fvol_pax_demoSheetFold()


pax_demoSheetFold.check()
#pax_demoSheetFold.exportBrep(f"{outFileName}.brep")
#pax_demoSheetFold.exportIges(f"{outFileName}.igs")
#pax_demoSheetFold.exportStep(f"{outFileName}.stp")
pax_demoSheetFold.exportStl(f"{outFileName}.stl")

