# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "door"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_door_faceDoor_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(350.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(350.0000, 230.7545, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(362.3316, 341.1153, 0)
	P004 = App.Vector(398.7180, 446.0324, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(503.6756, 650.8577, 0)
	P006 = App.Vector(620.1036, 849.3872, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(725.7395, 998.8973, 0)
	P008 = App.Vector(847.5000, 1135.5961, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(972.6240, 1241.9093, 0)
	P010 = App.Vector(1113.5200, 1326.2112, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(1226.1763, 1366.3760, 0)
	P012 = App.Vector(1345.0000, 1380.0000, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(1463.8237, 1366.3760, 0)
	P014 = App.Vector(1576.4800, 1326.2112, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(1717.3760, 1241.9093, 0)
	P016 = App.Vector(1842.5000, 1135.5961, 0)
	S008 = Part.Arc(P014, P015, P016)
	P017 = App.Vector(1964.2605, 998.8973, 0)
	P018 = App.Vector(2069.8964, 849.3872, 0)
	S009 = Part.Arc(P016, P017, P018)
	P019 = App.Vector(2186.3244, 650.8577, 0)
	P020 = App.Vector(2291.2820, 446.0324, 0)
	S010 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(2327.6684, 341.1153, 0)
	P022 = App.Vector(2340.0000, 230.7545, 0)
	S011 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(2340.0000, 0.0000, 0)
	S012 = Part.LineSegment(P022, P023)
	P024 = App.Vector(2690.0000, 0.0000, 0)
	S013 = Part.LineSegment(P023, P024)
	P025 = App.Vector(2690.0000, 61.2108, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(2658.3319, 351.9014, 0)
	P027 = App.Vector(2564.8133, 628.9540, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(2448.6460, 866.2712, 0)
	P029 = App.Vector(2322.5416, 1098.4607, 0)
	S016 = Part.Arc(P027, P028, P029)
	P030 = App.Vector(2181.5584, 1316.6645, 0)
	P031 = App.Vector(2017.5000, 1518.0943, 0)
	S017 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(1847.6570, 1675.5899, 0)
	P033 = App.Vector(1653.7016, 1802.2106, 0)
	S018 = Part.Arc(P031, P032, P033)
	P034 = App.Vector(1504.1759, 1860.2534, 0)
	P035 = App.Vector(1345.0000, 1880.0000, 0)
	S019 = Part.Arc(P033, P034, P035)
	P036 = App.Vector(1185.8241, 1860.2534, 0)
	P037 = App.Vector(1036.2984, 1802.2106, 0)
	S020 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(842.3430, 1675.5899, 0)
	P039 = App.Vector(672.5000, 1518.0943, 0)
	S021 = Part.Arc(P037, P038, P039)
	P040 = App.Vector(508.4416, 1316.6645, 0)
	P041 = App.Vector(367.4584, 1098.4607, 0)
	S022 = Part.Arc(P039, P040, P041)
	P042 = App.Vector(241.3540, 866.2712, 0)
	P043 = App.Vector(125.1867, 628.9540, 0)
	S023 = Part.Arc(P041, P042, P043)
	P044 = App.Vector(31.6681, 351.9014, 0)
	P045 = App.Vector(0.0000, 61.2108, 0)
	S024 = Part.Arc(P043, P044, P045)
	P046 = App.Vector(0.0000, 0.0000, 0)
	S025 = Part.LineSegment(P045, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door_faceDoor_Fa0():
	FC000 = ctr_face_door_faceDoor_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def door_faceDoor():
	FA000 = face_door_faceDoor_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_door_faceTop_Fa0_Ctr0():
	P000 = App.Vector(-1345.0000, 0.0000, 0)
	P001 = App.Vector(-995.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-995.0000, 400.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-1345.0000, 400.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-1345.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door_faceTop_Fa0():
	FC000 = ctr_face_door_faceTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_door_faceTop_Fa1_Ctr0():
	P000 = App.Vector(995.0000, 0.0000, 0)
	P001 = App.Vector(1345.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1345.0000, 400.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(995.0000, 400.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(995.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door_faceTop_Fa1():
	FC000 = ctr_face_door_faceTop_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def door_faceTop():
	FA000 = face_door_faceTop_Fa0()
	FA001 = face_door_faceTop_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_door_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(400.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(400.0000, 1880.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1880.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_door_faceSide_Fa0():
	FC000 = ctr_face_door_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def door_faceSide():
	FA000 = face_door_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_door():
	FIG = door_faceDoor()
	VEX = FIG.extrude(App.Vector(0, 0, 400))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_door = fex_subpax_door()

pax_door = subpax_door

pax_door.check()
#pax_door.exportBrep(f"{outFileName}.brep")
#pax_door.exportIges(f"{outFileName}.igs")
#pax_door.exportStep(f"{outFileName}.stp")
pax_door.exportStl(f"{outFileName}.stl")

