# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "reinforced_tube"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(800.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(790.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_reinforced_tube_faceTopExt_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopExt():
	FA000 = face_reinforced_tube_faceTopExt_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr0():
	P000 = App.Vector(790.0000, 0.0000, 0)
	P001 = App.Vector(751.3346, 244.1234, 0)
	P002 = App.Vector(639.1234, 464.3503, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(582.3266, 504.2037, 0)
	P004 = App.Vector(513.0270, 500.7781, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(445.5383, 473.8210, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(352.6712, 485.4102, 0)
	P007 = App.Vector(312.9516, 570.1508, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(317.7342, 642.6666, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(299.5774, 709.6330, 0)
	P010 = App.Vector(244.1234, 751.3346, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(-0.0000, 790.0000, 0)
	P012 = App.Vector(-244.1234, 751.3346, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-299.5774, 709.6330, 0)
	P014 = App.Vector(-317.7342, 642.6666, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(-312.9516, 570.1508, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(-352.6712, 485.4102, 0)
	P017 = App.Vector(-445.5383, 473.8210, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-513.0270, 500.7781, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(-582.3266, 504.2037, 0)
	P020 = App.Vector(-639.1234, 464.3503, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-751.3346, 244.1234, 0)
	P022 = App.Vector(-790.0000, 0.0000, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-767.4756, -65.6264, 0)
	P024 = App.Vector(-709.3975, -103.5883, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-638.9530, -121.4484, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-570.6339, -185.4102, 0)
	P027 = App.Vector(-588.3095, -277.3134, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-634.8023, -333.1687, 0)
	S016 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-659.4750, -398.0180, 0)
	P030 = App.Vector(-639.1234, -464.3503, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-464.3503, -639.1234, 0)
	P032 = App.Vector(-244.1234, -751.3346, 0)
	S018 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(-174.7486, -750.1924, 0)
	P034 = App.Vector(-120.6976, -706.6877, 0)
	S019 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-81.9431, -645.2101, 0)
	S020 = Part.LineSegment(P034, P035)
	P036 = App.Vector(-0.0000, -600.0000, 0)
	P037 = App.Vector(81.9431, -645.2101, 0)
	S021 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(120.6976, -706.6877, 0)
	S022 = Part.LineSegment(P037, P038)
	P039 = App.Vector(174.7486, -750.1924, 0)
	P040 = App.Vector(244.1234, -751.3346, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(464.3503, -639.1234, 0)
	P042 = App.Vector(639.1234, -464.3503, 0)
	S024 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(659.4750, -398.0180, 0)
	P044 = App.Vector(634.8023, -333.1687, 0)
	S025 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(588.3095, -277.3134, 0)
	S026 = Part.LineSegment(P044, P045)
	P046 = App.Vector(570.6339, -185.4102, 0)
	P047 = App.Vector(638.9530, -121.4484, 0)
	S027 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(709.3975, -103.5883, 0)
	S028 = Part.LineSegment(P047, P048)
	P049 = App.Vector(767.4756, -65.6264, 0)
	P050 = App.Vector(790.0000, -0.0000, 0)
	S029 = Part.Arc(P048, P049, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr1():
	P000 = App.Vector(780.0000, 0.0000, 0)
	P001 = App.Vector(741.8241, 241.0333, 0)
	P002 = App.Vector(631.0333, 458.4725, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(579.5512, 494.5966, 0)
	P004 = App.Vector(516.7363, 491.4915, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(449.2476, 464.5344, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(346.7933, 477.3200, 0)
	P007 = App.Vector(302.9733, 570.8089, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(307.7559, 643.3247, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(291.2981, 704.0247, 0)
	P010 = App.Vector(241.0333, 741.8241, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(-0.0000, 780.0000, 0)
	P012 = App.Vector(-241.0333, 741.8241, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-291.2981, 704.0247, 0)
	P014 = App.Vector(-307.7559, 643.3247, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(-302.9733, 570.8089, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(-346.7933, 477.3200, 0)
	P017 = App.Vector(-449.2476, 464.5344, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-516.7363, 491.4915, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(-579.5512, 494.5966, 0)
	P020 = App.Vector(-631.0333, 458.4725, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(-741.8241, 241.0333, 0)
	P022 = App.Vector(-780.0000, 0.0000, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-759.5833, -59.4854, 0)
	P024 = App.Vector(-706.9399, -93.8950, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-636.4955, -111.7551, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-561.1233, -182.3200, 0)
	P027 = App.Vector(-580.6236, -283.7109, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-627.1165, -339.5662, 0)
	S016 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-649.4805, -398.3472, 0)
	P030 = App.Vector(-631.0333, -458.4725, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-458.4725, -631.0333, 0)
	P032 = App.Vector(-241.0333, -741.8241, 0)
	S018 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(-178.1502, -740.7887, 0)
	P034 = App.Vector(-129.1570, -701.3550, 0)
	S019 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-90.4025, -639.8774, 0)
	S020 = Part.LineSegment(P034, P035)
	P036 = App.Vector(-0.0000, -590.0000, 0)
	P037 = App.Vector(90.4025, -639.8774, 0)
	S021 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(129.1570, -701.3550, 0)
	S022 = Part.LineSegment(P037, P038)
	P039 = App.Vector(178.1502, -740.7887, 0)
	P040 = App.Vector(241.0333, -741.8241, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(458.4725, -631.0333, 0)
	P042 = App.Vector(631.0333, -458.4725, 0)
	S024 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(649.4805, -398.3472, 0)
	P044 = App.Vector(627.1165, -339.5662, 0)
	S025 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(580.6236, -283.7109, 0)
	S026 = Part.LineSegment(P044, P045)
	P046 = App.Vector(561.1233, -182.3200, 0)
	P047 = App.Vector(636.4955, -111.7551, 0)
	S027 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(706.9399, -93.8950, 0)
	S028 = Part.LineSegment(P047, P048)
	P049 = App.Vector(759.5833, -59.4854, 0)
	P050 = App.Vector(780.0000, -0.0000, 0)
	S029 = Part.Arc(P048, P049, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceTopWave_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopWave():
	FA000 = face_reinforced_tube_faceTopWave_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def reinforced_tube_faceTopInt():
	rOneFig = undefined
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceSide_Fa0_Ctr0():
	P000 = App.Vector(-800.0000, 0.0000, 0)
	P001 = App.Vector(-790.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-790.0000, 6000.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-800.0000, 6000.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-800.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa0():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_reinforced_tube_faceSide_Fa1_Ctr0():
	P000 = App.Vector(790.0000, 0.0000, 0)
	P001 = App.Vector(800.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.0000, 6000.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(790.0000, 6000.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(790.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa1():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceSide():
	FA000 = face_reinforced_tube_faceSide_Fa0()
	FA001 = face_reinforced_tube_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_reinforced_tube_topExt():
	FIG = reinforced_tube_faceTopExt()
	VEX = FIG.extrude(App.Vector(0, 0, 6000))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_reinforced_tube_topExt = fex_subpax_reinforced_tube_topExt()

def fex_subpax_reinforced_tube_topWave():
	FIG = reinforced_tube_faceTopWave()
	VEX = FIG.extrude(App.Vector(0, 0, 6000))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_reinforced_tube_topWave = fex_subpax_reinforced_tube_topWave()

def fvol_pax_reinforced_tube():
	V000 = subpax_reinforced_tube_topExt
	V001 = V000.fuse(subpax_reinforced_tube_topWave)
	VFC = V001.removeSplitter()
	return VFC
pax_reinforced_tube = fvol_pax_reinforced_tube()


pax_reinforced_tube.check()
#pax_reinforced_tube.exportBrep(f"{outFileName}.brep")
#pax_reinforced_tube.exportIges(f"{outFileName}.igs")
#pax_reinforced_tube.exportStep(f"{outFileName}.stp")
pax_reinforced_tube.exportStl(f"{outFileName}.stl")

