# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "demoSheetFold2"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_demoSheetFold2_facePattern_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 100.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_facePattern_Fa0_Ctr1():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(50.0000, 86.6025, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_facePattern_Fa0_Ctr2():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(50.0000, 86.6025, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_facePattern_Fa0_Ctr3():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(50.0000, 86.6025, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_facePattern_Fa0_Ctr4():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(100.0000, 100.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_facePattern_Fa0():
	FC000 = ctr_face_demoSheetFold2_facePattern_Fa0_Ctr0()
	FC001 = ctr_face_demoSheetFold2_facePattern_Fa0_Ctr1()
	FC002 = ctr_face_demoSheetFold2_facePattern_Fa0_Ctr2()
	FC003 = ctr_face_demoSheetFold2_facePattern_Fa0_Ctr3()
	FC004 = ctr_face_demoSheetFold2_facePattern_Fa0_Ctr4()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004])
	rOneFace.check()
	return rOneFace

def demoSheetFold2_facePattern():
	FA000 = face_demoSheetFold2_facePattern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 100.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f00_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f00():
	FA000 = face_demoSheetFold2_SFG_f00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 100.0000, 0)
	P001 = App.Vector(0.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(86.6025, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f01_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f01():
	FA000 = face_demoSheetFold2_SFG_f01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(86.6025, 50.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.0000, 100.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f02_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f02():
	FA000 = face_demoSheetFold2_SFG_f02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 100.0000, 0)
	P001 = App.Vector(0.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(86.6025, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f03_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f03():
	FA000 = face_demoSheetFold2_SFG_f03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f04_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(100.0000, 100.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f04_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f04_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f04():
	FA000 = face_demoSheetFold2_SFG_f04_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.5000, 3.3494, 0)
	P002 = App.Vector(21.6506, 12.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(12.9904, 17.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(7.5000, 12.0096, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj00_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj00():
	FA000 = face_demoSheetFold2_SFG_fj00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.5000, 3.3494, 0)
	P002 = App.Vector(21.6506, 12.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(12.9904, 17.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(7.5000, 12.0096, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj01_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj01():
	FA000 = face_demoSheetFold2_SFG_fj01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.5000, 3.3494, 0)
	P002 = App.Vector(21.6506, 12.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(12.9904, 17.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(7.5000, 12.0096, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj02_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj02():
	FA000 = face_demoSheetFold2_SFG_fj02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.5000, 3.3494, 0)
	P002 = App.Vector(21.6506, 12.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(12.9904, 17.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(7.5000, 12.0096, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj03_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj03():
	FA000 = face_demoSheetFold2_SFG_fj03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_SFG_f00():
	FIG = demoSheetFold2_SFG_f00()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_SFG_f00 = fex_subpax_SFG_f00()

def fex_subpax_SFG_f01():
	FIG = demoSheetFold2_SFG_f01()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -60.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(221.6506, -0.0000, 12.5000))
	return VFP
subpax_SFG_f01 = fex_subpax_SFG_f01()

def fex_subpax_SFG_f02():
	FIG = demoSheetFold2_SFG_f02()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -99.4623)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -40.5054)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 145.2850)
	VFP = VR3.translate(App.Vector(259.5392, 68.7500, 103.1250))
	return VFP
subpax_SFG_f02 = fex_subpax_SFG_f02()

def fex_subpax_SFG_f03():
	FIG = demoSheetFold2_SFG_f03()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 168.3106)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -22.2647)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -125.0331)
	VFP = VR3.translate(App.Vector(252.7734, 54.6875, 122.6562))
	return VFP
subpax_SFG_f03 = fex_subpax_SFG_f03()

def fex_subpax_SFG_f04():
	FIG = demoSheetFold2_SFG_f04()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -162.8143)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 37.5117)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -174.1253)
	VFP = VR3.translate(App.Vector(144.1820, 21.4844, 161.1328))
	return VFP
subpax_SFG_f04 = fex_subpax_SFG_f04()

def fex_subpax_SFG_fj00():
	FIG = demoSheetFold2_SFG_fj00()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(200.0000, 100.0000, 0.0000))
	return VFP
subpax_SFG_fj00 = fex_subpax_SFG_fj00()

def fex_subpax_SFG_fj01():
	FIG = demoSheetFold2_SFG_fj01()
	VEX = FIG.extrude(App.Vector(0, 0, 100.00000000000001))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 33.6901)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -25.6589)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 73.8979)
	VFP = VR3.translate(App.Vector(221.6506, 100.0000, 12.5000))
	return VFP
subpax_SFG_fj01 = fex_subpax_SFG_fj01()

def fex_subpax_SFG_fj02():
	FIG = demoSheetFold2_SFG_fj02()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -146.3099)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -76.9767)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -73.8979)
	VFP = VR3.translate(App.Vector(183.7620, 131.2500, 121.8750))
	return VFP
subpax_SFG_fj02 = fex_subpax_SFG_fj02()

def fex_subpax_SFG_fj03():
	FIG = demoSheetFold2_SFG_fj03()
	VEX = FIG.extrude(App.Vector(0, 0, 100.00000000000001))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -75.4998)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -20.5988)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 170.0103)
	VFP = VR3.translate(App.Vector(176.9962, 117.1875, 141.4062))
	return VFP
subpax_SFG_fj03 = fex_subpax_SFG_fj03()

def fvol_pax_demoSheetFold2():
	V000 = subpax_SFG_f00
	V001 = V000.fuse(subpax_SFG_f01)
	V002 = V001.fuse(subpax_SFG_f02)
	V003 = V002.fuse(subpax_SFG_f03)
	V004 = V003.fuse(subpax_SFG_f04)
	V005 = V004.fuse(subpax_SFG_fj00)
	V006 = V005.fuse(subpax_SFG_fj01)
	V007 = V006.fuse(subpax_SFG_fj02)
	V008 = V007.fuse(subpax_SFG_fj03)
	VFC = V008.removeSplitter()
	return VFC
pax_demoSheetFold2 = fvol_pax_demoSheetFold2()


pax_demoSheetFold2.check()
#pax_demoSheetFold2.exportBrep(f"{outFileName}.brep")
#pax_demoSheetFold2.exportIges(f"{outFileName}.igs")
#pax_demoSheetFold2.exportStep(f"{outFileName}.stp")
pax_demoSheetFold2.exportStl(f"{outFileName}.stl")

