# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "armBone"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_armBone_faceA_Fa0_Ctr0():
	P000 = App.Vector(-23.5000, 0.0000, 0)
	P001 = App.Vector(23.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(23.5000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(17.8961, 101.9312, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 118.0000, 0)
	P005 = App.Vector(-17.8961, 101.9312, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-23.5000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-23.5000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_faceA_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.5000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_faceA_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(8.0000, App.Vector(0.0000, 100.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_faceA_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(12.0000, App.Vector(0.0000, 71.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armBone_faceA_Fa0():
	FC000 = ctr_face_armBone_faceA_Fa0_Ctr0()
	FC001 = ctr_face_armBone_faceA_Fa0_Ctr1()
	FC002 = ctr_face_armBone_faceA_Fa0_Ctr2()
	FC003 = ctr_face_armBone_faceA_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_faceA_Fa1_Ctr0():
	P000 = App.Vector(-30.0000, -80.0000, 0)
	P001 = App.Vector(-27.0000, -80.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-27.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-30.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-30.0000, -80.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_faceA_Fa1():
	FC000 = ctr_face_armBone_faceA_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_faceA_Fa2_Ctr0():
	P000 = App.Vector(27.0000, -80.0000, 0)
	P001 = App.Vector(30.0000, -80.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(30.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(27.0000, 50.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(27.0000, -80.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_faceA_Fa2():
	FC000 = ctr_face_armBone_faceA_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armBone_faceA():
	FA000 = face_armBone_faceA_Fa0()
	FA001 = face_armBone_faceA_Fa1()
	FA002 = face_armBone_faceA_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_faceB_Fa0_Ctr0():
	P000 = App.Vector(-13.5000, 0.0000, 0)
	P001 = App.Vector(-28.1387, -39.5975, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-0.0000, -80.0000, 0)
	P003 = App.Vector(28.1387, -39.5975, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(13.5000, 0.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(13.5000, 50.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-13.5000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-13.5000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_faceB_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_faceB_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(0.0000, -50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_faceB_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(0.0000, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armBone_faceB_Fa0():
	FC000 = ctr_face_armBone_faceB_Fa0_Ctr0()
	FC001 = ctr_face_armBone_faceB_Fa0_Ctr1()
	FC002 = ctr_face_armBone_faceB_Fa0_Ctr2()
	FC003 = ctr_face_armBone_faceB_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_faceB_Fa1_Ctr0():
	P000 = App.Vector(-20.0000, 0.0000, 0)
	P001 = App.Vector(-17.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-17.0000, 118.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-20.0000, 118.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-20.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_faceB_Fa1():
	FC000 = ctr_face_armBone_faceB_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_faceB_Fa2_Ctr0():
	P000 = App.Vector(17.0000, 0.0000, 0)
	P001 = App.Vector(20.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(20.0000, 118.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(17.0000, 118.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(17.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_faceB_Fa2():
	FC000 = ctr_face_armBone_faceB_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armBone_faceB():
	FA000 = face_armBone_faceB_Fa0()
	FA001 = face_armBone_faceB_Fa1()
	FA002 = face_armBone_faceB_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_SFG_pattern_Fa0_Ctr0():
	P000 = App.Vector(-23.5000, 0.0000, 0)
	P001 = App.Vector(23.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(31.3540, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(16.7153, -39.5975, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(44.8540, -80.0000, 0)
	P005 = App.Vector(72.9927, -39.5975, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(58.3540, -0.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(66.2080, 0.0000, 0)
	S005 = Part.LineSegment(P006, P007)
	P008 = App.Vector(113.2080, -0.0000, 0)
	S006 = Part.LineSegment(P007, P008)
	P009 = App.Vector(121.0619, 0.0000, 0)
	S007 = Part.LineSegment(P008, P009)
	P010 = App.Vector(106.4232, -39.5975, 0)
	S008 = Part.LineSegment(P009, P010)
	P011 = App.Vector(134.5619, -80.0000, 0)
	P012 = App.Vector(162.7007, -39.5975, 0)
	S009 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(148.0619, -0.0000, 0)
	S010 = Part.LineSegment(P012, P013)
	P014 = App.Vector(155.9159, -0.0000, 0)
	S011 = Part.LineSegment(P013, P014)
	P015 = App.Vector(155.9159, 50.0000, 0)
	S012 = Part.LineSegment(P014, P015)
	P016 = App.Vector(148.0619, 50.0000, 0)
	S013 = Part.LineSegment(P015, P016)
	P017 = App.Vector(121.0619, 50.0000, 0)
	S014 = Part.LineSegment(P016, P017)
	P018 = App.Vector(113.2080, 50.0000, 0)
	S015 = Part.LineSegment(P017, P018)
	P019 = App.Vector(107.6041, 101.9312, 0)
	S016 = Part.LineSegment(P018, P019)
	P020 = App.Vector(89.7080, 118.0000, 0)
	P021 = App.Vector(71.8119, 101.9312, 0)
	S017 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(66.2080, 50.0000, 0)
	S018 = Part.LineSegment(P021, P022)
	P023 = App.Vector(58.3540, 50.0000, 0)
	S019 = Part.LineSegment(P022, P023)
	P024 = App.Vector(31.3540, 50.0000, 0)
	S020 = Part.LineSegment(P023, P024)
	P025 = App.Vector(23.5000, 50.0000, 0)
	S021 = Part.LineSegment(P024, P025)
	P026 = App.Vector(17.8961, 101.9312, 0)
	S022 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-0.0000, 118.0000, 0)
	P028 = App.Vector(-17.8961, 101.9312, 0)
	S023 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-23.5000, 50.0000, 0)
	S024 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-23.5000, 0.0000, 0)
	S025 = Part.LineSegment(P029, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr1():
	P000 = App.Vector(-23.5000, 0.0000, 0)
	P001 = App.Vector(23.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(31.3540, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(16.7153, -39.5975, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(44.8540, -80.0000, 0)
	P005 = App.Vector(72.9927, -39.5975, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(58.3540, -0.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(66.2080, 0.0000, 0)
	S005 = Part.LineSegment(P006, P007)
	P008 = App.Vector(113.2080, -0.0000, 0)
	S006 = Part.LineSegment(P007, P008)
	P009 = App.Vector(121.0619, 0.0000, 0)
	S007 = Part.LineSegment(P008, P009)
	P010 = App.Vector(106.4232, -39.5975, 0)
	S008 = Part.LineSegment(P009, P010)
	P011 = App.Vector(134.5619, -80.0000, 0)
	P012 = App.Vector(162.7007, -39.5975, 0)
	S009 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(148.0619, -0.0000, 0)
	S010 = Part.LineSegment(P012, P013)
	P014 = App.Vector(155.9159, -0.0000, 0)
	S011 = Part.LineSegment(P013, P014)
	P015 = App.Vector(155.9159, 50.0000, 0)
	S012 = Part.LineSegment(P014, P015)
	P016 = App.Vector(148.0619, 50.0000, 0)
	S013 = Part.LineSegment(P015, P016)
	P017 = App.Vector(121.0619, 50.0000, 0)
	S014 = Part.LineSegment(P016, P017)
	P018 = App.Vector(113.2080, 50.0000, 0)
	S015 = Part.LineSegment(P017, P018)
	P019 = App.Vector(107.6041, 101.9312, 0)
	S016 = Part.LineSegment(P018, P019)
	P020 = App.Vector(89.7080, 118.0000, 0)
	P021 = App.Vector(71.8119, 101.9312, 0)
	S017 = Part.Arc(P019, P020, P021)
	P022 = App.Vector(66.2080, 50.0000, 0)
	S018 = Part.LineSegment(P021, P022)
	P023 = App.Vector(58.3540, 50.0000, 0)
	S019 = Part.LineSegment(P022, P023)
	P024 = App.Vector(31.3540, 50.0000, 0)
	S020 = Part.LineSegment(P023, P024)
	P025 = App.Vector(23.5000, 50.0000, 0)
	S021 = Part.LineSegment(P024, P025)
	P026 = App.Vector(17.8961, 101.9312, 0)
	S022 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-0.0000, 118.0000, 0)
	P028 = App.Vector(-17.8961, 101.9312, 0)
	S023 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-23.5000, 50.0000, 0)
	S024 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-23.5000, 0.0000, 0)
	S025 = Part.LineSegment(P029, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.5000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(8.0000, App.Vector(0.0000, 100.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(12.0000, App.Vector(0.0000, 71.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(44.8540, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(44.8540, -50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(44.8540, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.5000, App.Vector(89.7080, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(8.0000, App.Vector(89.7080, 100.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(12.0000, App.Vector(89.7080, 71.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(134.5619, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(134.5619, -50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(134.5619, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr14():
	P000 = App.Vector(30.3540, 24.0000, 0)
	P001 = App.Vector(31.3540, 25.0000, 0)
	P002 = App.Vector(30.3540, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(24.5000, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(23.5000, 25.0000, 0)
	P005 = App.Vector(24.5000, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(30.3540, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr15():
	P000 = App.Vector(65.2080, 24.0000, 0)
	P001 = App.Vector(66.2080, 25.0000, 0)
	P002 = App.Vector(65.2080, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(59.3540, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(58.3540, 25.0000, 0)
	P005 = App.Vector(59.3540, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(65.2080, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr16():
	P000 = App.Vector(120.0619, 24.0000, 0)
	P001 = App.Vector(121.0619, 25.0000, 0)
	P002 = App.Vector(120.0619, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(114.2080, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(113.2080, 25.0000, 0)
	P005 = App.Vector(114.2080, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(120.0619, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_SFG_pattern_Fa0_Ctr17():
	P000 = App.Vector(154.9159, 24.0000, 0)
	P001 = App.Vector(155.9159, 25.0000, 0)
	P002 = App.Vector(154.9159, 26.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(149.0619, 26.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(148.0619, 25.0000, 0)
	P005 = App.Vector(149.0619, 24.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(154.9159, 24.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_pattern_Fa0():
	FC000 = ctr_face_armBone_SFG_pattern_Fa0_Ctr0()
	FC001 = ctr_face_armBone_SFG_pattern_Fa0_Ctr1()
	FC002 = ctr_face_armBone_SFG_pattern_Fa0_Ctr2()
	FC003 = ctr_face_armBone_SFG_pattern_Fa0_Ctr3()
	FC004 = ctr_face_armBone_SFG_pattern_Fa0_Ctr4()
	FC005 = ctr_face_armBone_SFG_pattern_Fa0_Ctr5()
	FC006 = ctr_face_armBone_SFG_pattern_Fa0_Ctr6()
	FC007 = ctr_face_armBone_SFG_pattern_Fa0_Ctr7()
	FC008 = ctr_face_armBone_SFG_pattern_Fa0_Ctr8()
	FC009 = ctr_face_armBone_SFG_pattern_Fa0_Ctr9()
	FC010 = ctr_face_armBone_SFG_pattern_Fa0_Ctr10()
	FC011 = ctr_face_armBone_SFG_pattern_Fa0_Ctr11()
	FC012 = ctr_face_armBone_SFG_pattern_Fa0_Ctr12()
	FC013 = ctr_face_armBone_SFG_pattern_Fa0_Ctr13()
	FC014 = ctr_face_armBone_SFG_pattern_Fa0_Ctr14()
	FC015 = ctr_face_armBone_SFG_pattern_Fa0_Ctr15()
	FC016 = ctr_face_armBone_SFG_pattern_Fa0_Ctr16()
	FC017 = ctr_face_armBone_SFG_pattern_Fa0_Ctr17()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017])
	rOneFace.check()
	return rOneFace

def armBone_SFG_pattern():
	FA000 = face_armBone_SFG_pattern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_SFG_profiles_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(47.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(47.0000, 3.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_profiles_Fa0():
	FC000 = ctr_face_armBone_SFG_profiles_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_SFG_profiles_Fa1_Ctr0():
	P000 = App.Vector(47.0000, 0.0000, 0)
	P001 = App.Vector(51.5962, 1.9038, 0)
	P002 = App.Vector(53.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(50.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(49.4749, 4.0251, 0)
	P005 = App.Vector(47.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(47.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_profiles_Fa1():
	FC000 = ctr_face_armBone_SFG_profiles_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_SFG_profiles_Fa2_Ctr0():
	P000 = App.Vector(53.5000, 6.5000, 0)
	P001 = App.Vector(53.5000, 33.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(50.5000, 33.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(50.5000, 6.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(53.5000, 6.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_profiles_Fa2():
	FC000 = ctr_face_armBone_SFG_profiles_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_SFG_profiles_Fa3_Ctr0():
	P000 = App.Vector(53.5000, 33.5000, 0)
	P001 = App.Vector(51.5962, 38.0962, 0)
	P002 = App.Vector(47.0000, 40.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(47.0000, 37.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(49.4749, 35.9749, 0)
	P005 = App.Vector(50.5000, 33.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(53.5000, 33.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_profiles_Fa3():
	FC000 = ctr_face_armBone_SFG_profiles_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_SFG_profiles_Fa4_Ctr0():
	P000 = App.Vector(47.0000, 40.0000, 0)
	P001 = App.Vector(0.0000, 40.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 37.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(47.0000, 37.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(47.0000, 40.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_profiles_Fa4():
	FC000 = ctr_face_armBone_SFG_profiles_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_SFG_profiles_Fa5_Ctr0():
	P000 = App.Vector(0.0000, 40.0000, 0)
	P001 = App.Vector(-4.5962, 38.0962, 0)
	P002 = App.Vector(-6.5000, 33.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-3.5000, 33.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-2.4749, 35.9749, 0)
	P005 = App.Vector(-0.0000, 37.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 40.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_profiles_Fa5():
	FC000 = ctr_face_armBone_SFG_profiles_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_SFG_profiles_Fa6_Ctr0():
	P000 = App.Vector(-6.5000, 33.5000, 0)
	P001 = App.Vector(-6.5000, 6.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-3.5000, 33.5000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-6.5000, 33.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_profiles_Fa6():
	FC000 = ctr_face_armBone_SFG_profiles_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_armBone_SFG_profiles_Fa7_Ctr0():
	P000 = App.Vector(-6.5000, 6.5000, 0)
	P001 = App.Vector(-4.5962, 1.9038, 0)
	P002 = App.Vector(-0.0000, 0.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-0.0000, 3.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-2.4749, 4.0251, 0)
	P005 = App.Vector(-3.5000, 6.5000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-6.5000, 6.5000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_profiles_Fa7():
	FC000 = ctr_face_armBone_SFG_profiles_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armBone_SFG_profiles():
	FA000 = face_armBone_SFG_profiles_Fa0()
	FA001 = face_armBone_SFG_profiles_Fa1()
	FA002 = face_armBone_SFG_profiles_Fa2()
	FA003 = face_armBone_SFG_profiles_Fa3()
	FA004 = face_armBone_SFG_profiles_Fa4()
	FA005 = face_armBone_SFG_profiles_Fa5()
	FA006 = face_armBone_SFG_profiles_Fa6()
	FA007 = face_armBone_SFG_profiles_Fa7()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007])
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_SFG_f00_Fa0_Ctr0():
	P000 = App.Vector(-23.5000, 0.0000, 0)
	P001 = App.Vector(23.5000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(23.5000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(17.8961, 101.9312, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 118.0000, 0)
	P005 = App.Vector(-17.8961, 101.9312, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-23.5000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-23.5000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_SFG_f00_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.5000, App.Vector(0.0000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_f00_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(8.0000, App.Vector(0.0000, 100.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_f00_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(12.0000, App.Vector(0.0000, 71.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armBone_SFG_f00_Fa0():
	FC000 = ctr_face_armBone_SFG_f00_Fa0_Ctr0()
	FC001 = ctr_face_armBone_SFG_f00_Fa0_Ctr1()
	FC002 = ctr_face_armBone_SFG_f00_Fa0_Ctr2()
	FC003 = ctr_face_armBone_SFG_f00_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armBone_SFG_f00():
	FA000 = face_armBone_SFG_f00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_SFG_f01_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(-14.6387, -39.5975, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(13.5000, -80.0000, 0)
	P003 = App.Vector(41.6387, -39.5975, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(27.0000, 0.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(27.0000, 50.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-0.0000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-0.0000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_SFG_f01_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(13.5000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_f01_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(13.5000, -50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_f01_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(13.5000, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armBone_SFG_f01_Fa0():
	FC000 = ctr_face_armBone_SFG_f01_Fa0_Ctr0()
	FC001 = ctr_face_armBone_SFG_f01_Fa0_Ctr1()
	FC002 = ctr_face_armBone_SFG_f01_Fa0_Ctr2()
	FC003 = ctr_face_armBone_SFG_f01_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armBone_SFG_f01():
	FA000 = face_armBone_SFG_f01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_SFG_f02_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(47.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(47.0000, 50.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(41.3961, 101.9312, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(23.5000, 118.0000, 0)
	P005 = App.Vector(5.6039, 101.9312, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-0.0000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-0.0000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_SFG_f02_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.5000, App.Vector(23.5000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_f02_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(8.0000, App.Vector(23.5000, 100.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_f02_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(12.0000, App.Vector(23.5000, 71.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armBone_SFG_f02_Fa0():
	FC000 = ctr_face_armBone_SFG_f02_Fa0_Ctr0()
	FC001 = ctr_face_armBone_SFG_f02_Fa0_Ctr1()
	FC002 = ctr_face_armBone_SFG_f02_Fa0_Ctr2()
	FC003 = ctr_face_armBone_SFG_f02_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armBone_SFG_f02():
	FA000 = face_armBone_SFG_f02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_SFG_f03_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(-14.6387, -39.5975, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(13.5000, -80.0000, 0)
	P003 = App.Vector(41.6387, -39.5975, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(27.0000, 0.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(27.0000, 50.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-0.0000, 50.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-0.0000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_armBone_SFG_f03_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(5.0000, App.Vector(13.5000, 25.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_f03_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(13.5000, -50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_armBone_SFG_f03_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(13.5000, -15.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_armBone_SFG_f03_Fa0():
	FC000 = ctr_face_armBone_SFG_f03_Fa0_Ctr0()
	FC001 = ctr_face_armBone_SFG_f03_Fa0_Ctr1()
	FC002 = ctr_face_armBone_SFG_f03_Fa0_Ctr2()
	FC003 = ctr_face_armBone_SFG_f03_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def armBone_SFG_f03():
	FA000 = face_armBone_SFG_f03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_SFG_fj00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_fj00_Fa0():
	FC000 = ctr_face_armBone_SFG_fj00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armBone_SFG_fj00():
	FA000 = face_armBone_SFG_fj00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_SFG_fj01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_fj01_Fa0():
	FC000 = ctr_face_armBone_SFG_fj01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armBone_SFG_fj01():
	FA000 = face_armBone_SFG_fj01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_SFG_fj02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_fj02_Fa0():
	FC000 = ctr_face_armBone_SFG_fj02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armBone_SFG_fj02():
	FA000 = face_armBone_SFG_fj02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_armBone_SFG_fj03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(4.5962, 1.9038, 0)
	P002 = App.Vector(6.5000, 6.5000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(3.5000, 6.5000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2.4749, 4.0251, 0)
	P005 = App.Vector(0.0000, 3.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_armBone_SFG_fj03_Fa0():
	FC000 = ctr_face_armBone_SFG_fj03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def armBone_SFG_fj03():
	FA000 = face_armBone_SFG_fj03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_armBone_SFG_f00():
	FIG = armBone_SFG_f00()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_armBone_SFG_f00 = fex_subpax_armBone_SFG_f00()

def fex_subpax_armBone_SFG_f01():
	FIG = armBone_SFG_f01()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(30.0000, -0.0000, 6.5000))
	return VFP
subpax_armBone_SFG_f01 = fex_subpax_armBone_SFG_f01()

def fex_subpax_armBone_SFG_f02():
	FIG = armBone_SFG_f02()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -180.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(23.5000, 0.0000, 40.0000))
	return VFP
subpax_armBone_SFG_f02 = fex_subpax_armBone_SFG_f02()

def fex_subpax_armBone_SFG_f03():
	FIG = armBone_SFG_f03()
	VEX = FIG.extrude(App.Vector(0, 0, 3))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-30.0000, 0.0000, 33.5000))
	return VFP
subpax_armBone_SFG_f03 = fex_subpax_armBone_SFG_f03()

def fex_subpax_armBone_SFG_fj00():
	FIG = armBone_SFG_fj00()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(23.5000, 50.0000, 0.0000))
	return VFP
subpax_armBone_SFG_fj00 = fex_subpax_armBone_SFG_fj00()

def fex_subpax_armBone_SFG_fj01():
	FIG = armBone_SFG_fj01()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(30.0000, 50.0000, 33.5000))
	return VFP
subpax_armBone_SFG_fj01 = fex_subpax_armBone_SFG_fj01()

def fex_subpax_armBone_SFG_fj02():
	FIG = armBone_SFG_fj02()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(-23.5000, 50.0000, 40.0000))
	return VFP
subpax_armBone_SFG_fj02 = fex_subpax_armBone_SFG_fj02()

def fex_subpax_armBone_SFG_fj03():
	FIG = armBone_SFG_fj03()
	VEX = FIG.extrude(App.Vector(0, 0, 50))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-30.0000, 50.0000, 6.5000))
	return VFP
subpax_armBone_SFG_fj03 = fex_subpax_armBone_SFG_fj03()

def fvol_pax_armBone():
	V000 = subpax_armBone_SFG_f00
	V001 = V000.fuse(subpax_armBone_SFG_f01)
	V002 = V001.fuse(subpax_armBone_SFG_f02)
	V003 = V002.fuse(subpax_armBone_SFG_f03)
	V004 = V003.fuse(subpax_armBone_SFG_fj00)
	V005 = V004.fuse(subpax_armBone_SFG_fj01)
	V006 = V005.fuse(subpax_armBone_SFG_fj02)
	V007 = V006.fuse(subpax_armBone_SFG_fj03)
	VFC = V007.removeSplitter()
	return VFC
pax_armBone = fvol_pax_armBone()


pax_armBone.check()
#pax_armBone.exportBrep(f"{outFileName}.brep")
#pax_armBone.exportIges(f"{outFileName}.igs")
#pax_armBone.exportStep(f"{outFileName}.stp")
pax_armBone.exportStl(f"{outFileName}.stl")

