# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "demoSheetFold2"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(235.9538, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(339.0747, 3.8382, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(348.5971, 14.0499, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(375.5018, -1.4836, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(422.0126, -9.2771, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(460.6645, -6.5742, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(560.4209, 0.4014, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(554.9102, 79.2090, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(455.1538, 72.2333, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(416.5018, 69.5305, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(389.5971, 85.0639, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(245.4763, 110.2116, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(235.9538, 100.0000, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(200.0000, 100.0000, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(0.0000, 100.0000, 0)
	S015 = Part.LineSegment(P015, P016)
	P017 = App.Vector(0.0000, 0.0000, 0)
	S016 = Part.LineSegment(P016, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr1():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(235.9538, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(339.0747, 3.8382, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(348.5971, 14.0499, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(375.5018, -1.4836, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(422.0126, -9.2771, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(460.6645, -6.5742, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(560.4209, 0.4014, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(554.9102, 79.2090, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(455.1538, 72.2333, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(416.5018, 69.5305, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(389.5971, 85.0639, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(245.4763, 110.2116, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(235.9538, 100.0000, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(200.0000, 100.0000, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(0.0000, 100.0000, 0)
	S015 = Part.LineSegment(P015, P016)
	P017 = App.Vector(0.0000, 0.0000, 0)
	S016 = Part.LineSegment(P016, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr2():
	P000 = App.Vector(234.9538, 49.0000, 0)
	P001 = App.Vector(235.9538, 50.0000, 0)
	P002 = App.Vector(234.9538, 51.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(201.0000, 51.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0000, 50.0000, 0)
	P005 = App.Vector(201.0000, 49.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(234.9538, 49.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr3():
	P000 = App.Vector(287.4649, 53.3325, 0)
	P001 = App.Vector(287.5142, 51.9191, 0)
	P002 = App.Vector(288.9276, 51.9685, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(297.0861, 60.7174, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(297.0367, 62.1307, 0)
	P005 = App.Vector(295.6234, 62.0814, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(287.4649, 53.3325, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr4():
	P000 = App.Vector(394.6358, 33.6574, 0)
	P001 = App.Vector(396.0018, 34.0235, 0)
	P002 = App.Vector(395.6358, 35.3895, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(370.4632, 49.9229, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(369.0971, 49.5569, 0)
	P005 = App.Vector(369.4632, 48.1909, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(394.6358, 33.6574, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr5():
	P000 = App.Vector(456.9813, 31.7622, 0)
	P001 = App.Vector(457.9091, 32.8295, 0)
	P002 = App.Vector(456.8418, 33.7573, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(420.1850, 31.1940, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(419.2572, 30.1267, 0)
	P005 = App.Vector(420.3245, 29.1989, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(456.9813, 31.7622, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_pattern_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr0()
	FC001 = ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr1()
	FC002 = ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr2()
	FC003 = ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr3()
	FC004 = ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr4()
	FC005 = ctr_face_demoSheetFold2_SFG_pattern_Fa0_Ctr5()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005])
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_pattern():
	FA000 = face_demoSheetFold2_SFG_pattern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_profiles_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa1_Ctr0():
	P000 = App.Vector(200.0000, 0.0000, 0)
	P001 = App.Vector(219.5652, 9.4371, 0)
	P002 = App.Vector(224.3593, 30.6238, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(214.6156, 28.3743, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(211.7391, 15.6623, 0)
	P005 = App.Vector(200.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(200.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa1():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa2_Ctr0():
	P000 = App.Vector(224.3593, 30.6238, 0)
	P001 = App.Vector(201.1460, 131.1712, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(191.4023, 128.9217, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(214.6156, 28.3743, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(224.3593, 30.6238, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa2():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa3_Ctr0():
	P000 = App.Vector(201.1460, 131.1712, 0)
	P001 = App.Vector(200.8734, 136.3735, 0)
	P002 = App.Vector(202.3965, 141.3554, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(193.4864, 145.8953, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(190.9479, 137.5922, 0)
	P005 = App.Vector(191.4023, 128.9217, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(201.1460, 131.1712, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa3():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa4_Ctr0():
	P000 = App.Vector(202.3965, 141.3554, 0)
	P001 = App.Vector(202.8505, 142.2464, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(193.9404, 146.7863, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(193.4864, 145.8953, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(202.3965, 141.3554, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa4():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa5_Ctr0():
	P000 = App.Vector(202.8505, 142.2464, 0)
	P001 = App.Vector(204.4182, 161.1138, 0)
	P002 = App.Vector(192.3121, 175.6698, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(187.6174, 166.8403, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(194.8811, 158.1067, 0)
	P005 = App.Vector(193.9404, 146.7863, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(202.8505, 142.2464, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa5():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa6_Ctr0():
	P000 = App.Vector(192.3121, 175.6698, 0)
	P001 = App.Vector(150.6730, 197.8097, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(145.9783, 188.9802, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(187.6174, 166.8403, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(192.3121, 175.6698, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa6():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa7_Ctr0():
	P000 = App.Vector(150.6730, 197.8097, 0)
	P001 = App.Vector(142.8115, 209.3559, 0)
	P002 = App.Vector(147.8742, 222.3746, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(141.3136, 229.9217, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(132.8758, 208.2239, 0)
	P005 = App.Vector(145.9783, 188.9802, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(150.6730, 197.8097, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa7():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa8_Ctr0():
	P000 = App.Vector(147.8742, 222.3746, 0)
	P001 = App.Vector(223.3452, 287.9805, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(216.7846, 295.5276, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(141.3136, 229.9217, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(147.8742, 222.3746, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa8():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa9_Ctr0():
	P000 = App.Vector(0.0000, 400.0000, 0)
	P001 = App.Vector(200.0000, 400.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 410.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 410.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 400.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa9():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa10_Ctr0():
	P000 = App.Vector(200.0000, 400.0000, 0)
	P001 = App.Vector(219.5652, 409.4371, 0)
	P002 = App.Vector(224.3593, 430.6238, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(214.6156, 428.3743, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(211.7391, 415.6623, 0)
	P005 = App.Vector(200.0000, 410.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(200.0000, 400.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa10():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa11_Ctr0():
	P000 = App.Vector(224.3593, 430.6238, 0)
	P001 = App.Vector(224.1343, 431.5981, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(214.3906, 429.3486, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(214.6156, 428.3743, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(224.3593, 430.6238, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa11():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa12_Ctr0():
	P000 = App.Vector(224.1343, 431.5981, 0)
	P001 = App.Vector(223.8617, 436.8005, 0)
	P002 = App.Vector(225.3848, 441.7823, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(216.4747, 446.3222, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(213.9362, 438.0191, 0)
	P005 = App.Vector(214.3906, 429.3486, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(224.1343, 431.5981, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa12():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa12_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa13_Ctr0():
	P000 = App.Vector(225.3848, 441.7823, 0)
	P001 = App.Vector(291.8029, 572.1351, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(282.8928, 576.6750, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(216.4747, 446.3222, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(225.3848, 441.7823, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa13():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa13_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa14_Ctr0():
	P000 = App.Vector(291.8029, 572.1351, 0)
	P001 = App.Vector(293.3706, 591.0025, 0)
	P002 = App.Vector(281.2645, 605.5586, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(276.5698, 596.7291, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(283.8334, 587.9955, 0)
	P005 = App.Vector(282.8928, 576.6750, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(291.8029, 572.1351, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa14():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa14_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa15_Ctr0():
	P000 = App.Vector(281.2645, 605.5586, 0)
	P001 = App.Vector(280.3815, 606.0281, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(275.6868, 597.1986, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(276.5698, 596.7291, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(281.2645, 605.5586, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa15():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa15_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa16_Ctr0():
	P000 = App.Vector(280.3815, 606.0281, 0)
	P001 = App.Vector(272.5200, 617.5742, 0)
	P002 = App.Vector(277.5827, 630.5929, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(271.0221, 638.1400, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(262.5843, 616.4422, 0)
	P005 = App.Vector(275.6868, 597.1986, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(280.3815, 606.0281, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa16():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa16_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_demoSheetFold2_SFG_profiles_Fa17_Ctr0():
	P000 = App.Vector(277.5827, 630.5929, 0)
	P001 = App.Vector(353.0537, 696.1988, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(346.4931, 703.7459, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(271.0221, 638.1400, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(277.5827, 630.5929, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_profiles_Fa17():
	FC000 = ctr_face_demoSheetFold2_SFG_profiles_Fa17_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_profiles():
	FA000 = face_demoSheetFold2_SFG_profiles_Fa0()
	FA001 = face_demoSheetFold2_SFG_profiles_Fa1()
	FA002 = face_demoSheetFold2_SFG_profiles_Fa2()
	FA003 = face_demoSheetFold2_SFG_profiles_Fa3()
	FA004 = face_demoSheetFold2_SFG_profiles_Fa4()
	FA005 = face_demoSheetFold2_SFG_profiles_Fa5()
	FA006 = face_demoSheetFold2_SFG_profiles_Fa6()
	FA007 = face_demoSheetFold2_SFG_profiles_Fa7()
	FA008 = face_demoSheetFold2_SFG_profiles_Fa8()
	FA009 = face_demoSheetFold2_SFG_profiles_Fa9()
	FA010 = face_demoSheetFold2_SFG_profiles_Fa10()
	FA011 = face_demoSheetFold2_SFG_profiles_Fa11()
	FA012 = face_demoSheetFold2_SFG_profiles_Fa12()
	FA013 = face_demoSheetFold2_SFG_profiles_Fa13()
	FA014 = face_demoSheetFold2_SFG_profiles_Fa14()
	FA015 = face_demoSheetFold2_SFG_profiles_Fa15()
	FA016 = face_demoSheetFold2_SFG_profiles_Fa16()
	FA017 = face_demoSheetFold2_SFG_profiles_Fa17()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011, FA012, FA013, FA014, FA015, FA016, FA017])
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 100.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f00_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f00():
	FA000 = face_demoSheetFold2_SFG_f00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 100.0000, 0)
	P001 = App.Vector(0.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(103.1209, 3.8382, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 100.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f01_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f01():
	FA000 = face_demoSheetFold2_SFG_f01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 141.0000, 0)
	P001 = App.Vector(-79.8983, 122.5540, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 141.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f02_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f02():
	FA000 = face_demoSheetFold2_SFG_f02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 82.0000, 0)
	P001 = App.Vector(0.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(44.1762, 16.5060, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 82.0000, 0)
	S002 = Part.LineSegment(P002, P000)
	aShape = Part.Shape([S000, S001, S002])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f03_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f03():
	FA000 = face_demoSheetFold2_SFG_f03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_f04_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(100.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(100.0000, 79.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.0000, 79.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_f04_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_f04_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_f04():
	FA000 = face_demoSheetFold2_SFG_f04_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(19.5652, 9.4371, 0)
	P002 = App.Vector(24.3593, 30.6238, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(14.6156, 28.3743, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(11.7391, 15.6623, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj00_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj00():
	FA000 = face_demoSheetFold2_SFG_fj00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(5.1303, -0.9046, 0)
	P002 = App.Vector(9.6418, -3.5093, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(16.0697, 4.1511, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(8.5505, 8.4923, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj01_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj01():
	FA000 = face_demoSheetFold2_SFG_fj01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(17.5227, 7.1687, 0)
	P002 = App.Vector(24.9962, 24.5637, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(14.9977, 24.7382, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.5136, 14.3012, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj02_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj02():
	FA000 = face_demoSheetFold2_SFG_fj02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_demoSheetFold2_SFG_fj03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.3619, -6.5039, 0)
	P002 = App.Vector(14.0037, -20.3755, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(23.3395, -23.9592, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(20.6032, -0.8398, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_demoSheetFold2_SFG_fj03_Fa0():
	FC000 = ctr_face_demoSheetFold2_SFG_fj03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def demoSheetFold2_SFG_fj03():
	FA000 = face_demoSheetFold2_SFG_fj03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_demoSheetFold2_SFG_f00():
	FIG = demoSheetFold2_SFG_f00()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_demoSheetFold2_SFG_f00 = fex_subpax_demoSheetFold2_SFG_f00()

def fex_subpax_demoSheetFold2_SFG_f01():
	FIG = demoSheetFold2_SFG_f01()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -180.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -77.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(224.3593, -0.0000, 30.6238))
	return VFP
subpax_demoSheetFold2_SFG_f01 = fex_subpax_demoSheetFold2_SFG_f01()

def fex_subpax_demoSheetFold2_SFG_f02():
	FIG = demoSheetFold2_SFG_f02()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 70.3235)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 40.8171)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -132.2441)
	VFP = VR3.translate(App.Vector(226.2994, 107.0516, 37.8204))
	return VFP
subpax_demoSheetFold2_SFG_f02 = fex_subpax_demoSheetFold2_SFG_f02()

def fex_subpax_demoSheetFold2_SFG_f03():
	FIG = demoSheetFold2_SFG_f03()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 150.3370)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -15.6326)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 151.4237)
	VFP = VR3.translate(App.Vector(181.1993, 8.9771, 165.5890))
	return VFP
subpax_demoSheetFold2_SFG_f03 = fex_subpax_demoSheetFold2_SFG_f03()

def fex_subpax_demoSheetFold2_SFG_f04():
	FIG = demoSheetFold2_SFG_f04()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 17.8892)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -37.2765)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -81.6566)
	VFP = VR3.translate(App.Vector(146.3535, 40.5554, 209.2706))
	return VFP
subpax_demoSheetFold2_SFG_f04 = fex_subpax_demoSheetFold2_SFG_f04()

def fex_subpax_demoSheetFold2_SFG_fj00():
	FIG = demoSheetFold2_SFG_fj00()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(200.0000, 100.0000, 0.0000))
	return VFP
subpax_demoSheetFold2_SFG_fj00 = fex_subpax_demoSheetFold2_SFG_fj00()

def fex_subpax_demoSheetFold2_SFG_fj01():
	FIG = demoSheetFold2_SFG_fj01()
	VEX = FIG.extrude(App.Vector(0, 0, 141))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -17.5195)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -41.6454)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 101.8472)
	VFP = VR3.translate(App.Vector(224.3593, 100.0000, 30.6238))
	return VFP
subpax_demoSheetFold2_SFG_fj01 = fex_subpax_demoSheetFold2_SFG_fj01()

def fex_subpax_demoSheetFold2_SFG_fj02():
	FIG = demoSheetFold2_SFG_fj02()
	VEX = FIG.extrude(App.Vector(0, 0, 82))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 151.8677)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -57.2865)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -94.8667)
	VFP = VR3.translate(App.Vector(246.7884, 68.2329, 177.3788))
	return VFP
subpax_demoSheetFold2_SFG_fj02 = fex_subpax_demoSheetFold2_SFG_fj02()

def fex_subpax_demoSheetFold2_SFG_fj03():
	FIG = demoSheetFold2_SFG_fj03()
	VEX = FIG.extrude(App.Vector(0, 0, 79))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -106.2829)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -29.3343)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 117.5488)
	VFP = VR3.translate(App.Vector(224.8854, 66.3203, 204.6695))
	return VFP
subpax_demoSheetFold2_SFG_fj03 = fex_subpax_demoSheetFold2_SFG_fj03()

def fvol_pax_demoSheetFold2():
	V000 = subpax_demoSheetFold2_SFG_f00
	V001 = V000.fuse(subpax_demoSheetFold2_SFG_f01)
	V002 = V001.fuse(subpax_demoSheetFold2_SFG_f02)
	V003 = V002.fuse(subpax_demoSheetFold2_SFG_f03)
	V004 = V003.fuse(subpax_demoSheetFold2_SFG_f04)
	V005 = V004.fuse(subpax_demoSheetFold2_SFG_fj00)
	V006 = V005.fuse(subpax_demoSheetFold2_SFG_fj01)
	V007 = V006.fuse(subpax_demoSheetFold2_SFG_fj02)
	V008 = V007.fuse(subpax_demoSheetFold2_SFG_fj03)
	VFC = V008.removeSplitter()
	return VFC
pax_demoSheetFold2 = fvol_pax_demoSheetFold2()


pax_demoSheetFold2.check()
#pax_demoSheetFold2.exportBrep(f"{outFileName}.brep")
#pax_demoSheetFold2.exportIges(f"{outFileName}.igs")
#pax_demoSheetFold2.exportStep(f"{outFileName}.stp")
pax_demoSheetFold2.exportStl(f"{outFileName}.stl")

