# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "maison"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_maison_faceSide1_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(12.0000, 6.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(12.3600, 6.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(12.4350, 6.1500, 0)
	P005 = App.Vector(12.3600, 6.3000, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(11.7600, 6.4608, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(6.2000, 12.0000, 0)
	S005 = Part.LineSegment(P006, P007)
	P008 = App.Vector(5.8000, 12.0000, 0)
	S006 = Part.LineSegment(P007, P008)
	P009 = App.Vector(0.2400, 6.4608, 0)
	S007 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-0.3600, 6.3000, 0)
	S008 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-0.4350, 6.1500, 0)
	P012 = App.Vector(-0.3600, 6.0000, 0)
	S009 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(0.0000, 6.0000, 0)
	S010 = Part.LineSegment(P012, P013)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S011 = Part.LineSegment(P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_maison_faceSide1_Fa0():
	FC000 = ctr_face_maison_faceSide1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def maison_faceSide1():
	FA000 = face_maison_faceSide1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_maison_faceSide2_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(12.0000, 6.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(12.3600, 6.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(12.4350, 6.1500, 0)
	P005 = App.Vector(12.3600, 6.3000, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(11.7600, 6.4608, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(6.2000, 12.0000, 0)
	S005 = Part.LineSegment(P006, P007)
	P008 = App.Vector(5.8000, 12.0000, 0)
	S006 = Part.LineSegment(P007, P008)
	P009 = App.Vector(0.2400, 6.4608, 0)
	S007 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-0.3600, 6.3000, 0)
	S008 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-0.4350, 6.1500, 0)
	P012 = App.Vector(-0.3600, 6.0000, 0)
	S009 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(0.0000, 6.0000, 0)
	S010 = Part.LineSegment(P012, P013)
	P014 = App.Vector(0.0000, 0.0000, 0)
	S011 = Part.LineSegment(P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_maison_faceSide2_Fa0():
	FC000 = ctr_face_maison_faceSide2_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def maison_faceSide2():
	FA000 = face_maison_faceSide2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_maison_faceTop1_Fa0_Ctr0():
	P000 = App.Vector(-0.9600, 0.0000, 0)
	P001 = App.Vector(12.9600, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(12.9600, 15.6024, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.9600, 21.3682, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.9600, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_maison_faceTop1_Fa0():
	FC000 = ctr_face_maison_faceTop1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def maison_faceTop1():
	FA000 = face_maison_faceTop1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_maison_faceTop2_Fa0_Ctr0():
	P000 = App.Vector(-0.9600, -0.3976, 0)
	P001 = App.Vector(12.9600, 5.3682, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(12.9600, 20.9706, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.9600, 20.9706, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.9600, -0.3976, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_maison_faceTop2_Fa0():
	FC000 = ctr_face_maison_faceTop2_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def maison_faceTop2():
	FA000 = face_maison_faceTop2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_maison_faceChimney_Fa0_Ctr0():
	P000 = App.Vector(5.2500, 1.5000, 0)
	P001 = App.Vector(6.7500, 1.5000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(6.7500, 2.1000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(5.2500, 2.1000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(5.2500, 1.5000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_maison_faceChimney_Fa0():
	FC000 = ctr_face_maison_faceChimney_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_maison_faceChimney_Fa1_Ctr0():
	P000 = App.Vector(17.0558, 30.6018, 0)
	P001 = App.Vector(18.1165, 29.5411, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(18.5407, 29.9654, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(17.4801, 31.0260, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(17.0558, 30.6018, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_maison_faceChimney_Fa1():
	FC000 = ctr_face_maison_faceChimney_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_maison_faceChimney_Fa2_Ctr0():
	P000 = App.Vector(5.1923, 18.4951, 0)
	P001 = App.Vector(6.5781, 17.9211, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(6.8077, 18.4754, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(5.4219, 19.0495, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(5.1923, 18.4951, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_maison_faceChimney_Fa2():
	FC000 = ctr_face_maison_faceChimney_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_maison_faceChimney_Fa3_Ctr0():
	P000 = App.Vector(5.2500, 10.9353, 0)
	P001 = App.Vector(6.7500, 10.9353, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(6.7500, 11.5353, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(5.2500, 11.5353, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(5.2500, 10.9353, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_maison_faceChimney_Fa3():
	FC000 = ctr_face_maison_faceChimney_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_maison_faceChimney_Fa4_Ctr0():
	P000 = App.Vector(10.3841, 23.9300, 0)
	P001 = App.Vector(11.4447, 22.8693, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(11.8690, 23.2936, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(10.8083, 24.3543, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.3841, 23.9300, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_maison_faceChimney_Fa4():
	FC000 = ctr_face_maison_faceChimney_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def maison_faceChimney():
	FA000 = face_maison_faceChimney_Fa0()
	FA001 = face_maison_faceChimney_Fa1()
	FA002 = face_maison_faceChimney_Fa2()
	FA003 = face_maison_faceChimney_Fa3()
	FA004 = face_maison_faceChimney_Fa4()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004])
	rOneFig.check()
	return rOneFig

def fex_subpax_maison_top1():
	FIG = maison_faceTop1()
	VEX = FIG.extrude(App.Vector(0, 0, 12))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_maison_top1 = fex_subpax_maison_top1()

def fex_subpax_maison_side1():
	FIG = maison_faceSide1()
	VEX = FIG.extrude(App.Vector(0, 0, 21.36820776835531))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 21.3682, 0.0000))
	return VFP
subpax_maison_side1 = fex_subpax_maison_side1()

def fex_subpax_maison_top2():
	FIG = maison_faceTop2()
	VEX = FIG.extrude(App.Vector(0, 0, 12))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -45.0000)
	VFP = VR3.translate(App.Vector(0.0000, 20.9706, 0.0000))
	return VFP
subpax_maison_top2 = fex_subpax_maison_top2()

def fex_subpax_maison_side2():
	FIG = maison_faceSide2()
	VEX = FIG.extrude(App.Vector(0, 0, 21.36820776835531))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -45.0000)
	VFP = VR3.translate(App.Vector(14.8284, 35.7990, 0.0000))
	return VFP
subpax_maison_side2 = fex_subpax_maison_side2()

def fex_subpax_maison_chi1():
	FIG = maison_faceChimney()
	VEX = FIG.extrude(App.Vector(0, 0, 7.5))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 6.0000))
	return VFP
subpax_maison_chi1 = fex_subpax_maison_chi1()

def fvol_ipax_maison_1():
	V000 = subpax_maison_top1
	V001 = V000.common(subpax_maison_side1)
	VFC = V001.removeSplitter()
	return VFC
ipax_maison_1 = fvol_ipax_maison_1()

def fvol_ipax_maison_2():
	V000 = subpax_maison_top2
	V001 = V000.common(subpax_maison_side2)
	VFC = V001.removeSplitter()
	return VFC
ipax_maison_2 = fvol_ipax_maison_2()

def fvol_pax_maison():
	V000 = ipax_maison_1
	V001 = V000.fuse(ipax_maison_2)
	V002 = V001.fuse(subpax_maison_chi1)
	VFC = V002.removeSplitter()
	return VFC
pax_maison = fvol_pax_maison()


pax_maison.check()
#pax_maison.exportBrep(f"{outFileName}.brep")
#pax_maison.exportIges(f"{outFileName}.igs")
#pax_maison.exportStep(f"{outFileName}.stp")
pax_maison.exportStl(f"{outFileName}.stl")

