# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "cabane_plancher"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_cabane_plancher_facePlancherTop_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(800.6000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.6000, 200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 200.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa0():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa1_Ctr0():
	P000 = App.Vector(0.0000, 200.2000, 0)
	P001 = App.Vector(800.6000, 200.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.6000, 400.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 400.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 200.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa1():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa2_Ctr0():
	P000 = App.Vector(0.0000, 400.4000, 0)
	P001 = App.Vector(800.6000, 400.4000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.6000, 600.4000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 600.4000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 400.4000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa2():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa3_Ctr0():
	P000 = App.Vector(0.0000, 600.6000, 0)
	P001 = App.Vector(800.6000, 600.6000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.6000, 800.6000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 800.6000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 600.6000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa3():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa4_Ctr0():
	P000 = App.Vector(0.0000, 800.8000, 0)
	P001 = App.Vector(800.6000, 800.8000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.6000, 1000.8000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1000.8000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 800.8000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa4():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa5_Ctr0():
	P000 = App.Vector(0.0000, 1001.0000, 0)
	P001 = App.Vector(800.6000, 1001.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.6000, 1201.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1201.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 1001.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa5():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa6_Ctr0():
	P000 = App.Vector(0.0000, 1201.2000, 0)
	P001 = App.Vector(800.6000, 1201.2000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.6000, 1401.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1401.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 1201.2000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa6():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_facePlancherTop():
	FA000 = face_cabane_plancher_facePlancherTop_Fa0()
	FA001 = face_cabane_plancher_facePlancherTop_Fa1()
	FA002 = face_cabane_plancher_facePlancherTop_Fa2()
	FA003 = face_cabane_plancher_facePlancherTop_Fa3()
	FA004 = face_cabane_plancher_facePlancherTop_Fa4()
	FA005 = face_cabane_plancher_facePlancherTop_Fa5()
	FA006 = face_cabane_plancher_facePlancherTop_Fa6()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_facePlancherBottom_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 1401.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1401.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa0():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa1_Ctr0():
	P000 = App.Vector(200.2000, 0.0000, 0)
	P001 = App.Vector(400.2000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(400.2000, 1401.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(200.2000, 1401.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.2000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa1():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa2_Ctr0():
	P000 = App.Vector(400.4000, 0.0000, 0)
	P001 = App.Vector(600.4000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(600.4000, 1401.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(400.4000, 1401.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(400.4000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa2():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa3_Ctr0():
	P000 = App.Vector(600.6000, 0.0000, 0)
	P001 = App.Vector(800.6000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(800.6000, 1401.2000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(600.6000, 1401.2000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(600.6000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa3():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_facePlancherBottom():
	FA000 = face_cabane_plancher_facePlancherBottom_Fa0()
	FA001 = face_cabane_plancher_facePlancherBottom_Fa1()
	FA002 = face_cabane_plancher_facePlancherBottom_Fa2()
	FA003 = face_cabane_plancher_facePlancherBottom_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceBeam_Fa0_Ctr0():
	P000 = App.Vector(200.0000, 800.0000, 0)
	P001 = App.Vector(350.0000, 800.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(350.0000, 675.9808, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(335.0000, 650.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0000, 650.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(200.0000, 800.0000, 0)
	S004 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceBeam_Fa0():
	FC000 = ctr_face_cabane_plancher_faceBeam_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_faceBeam_Fa1_Ctr0():
	P000 = App.Vector(1201.2000, 800.0000, 0)
	P001 = App.Vector(1051.2000, 800.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1051.2000, 675.9808, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1066.2000, 650.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1201.2000, 650.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(1201.2000, 800.0000, 0)
	S004 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceBeam_Fa1():
	FC000 = ctr_face_cabane_plancher_faceBeam_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceBeam():
	FA000 = face_cabane_plancher_faceBeam_Fa0()
	FA001 = face_cabane_plancher_faceBeam_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceLeg_Fa0_Ctr0():
	P000 = App.Vector(594.8076, 800.0000, 0)
	P001 = App.Vector(421.6025, 800.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-40.2777, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(132.9274, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(594.8076, 800.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceLeg_Fa0():
	FC000 = ctr_face_cabane_plancher_faceLeg_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_faceLeg_Fa1_Ctr0():
	P000 = App.Vector(806.3924, 800.0000, 0)
	P001 = App.Vector(979.5975, 800.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1441.4777, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1268.2726, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(806.3924, 800.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceLeg_Fa1():
	FC000 = ctr_face_cabane_plancher_faceLeg_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceLeg():
	FA000 = face_cabane_plancher_faceLeg_Fa0()
	FA001 = face_cabane_plancher_faceLeg_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceButtress_Fa0_Ctr0():
	P000 = App.Vector(594.8076, 800.0000, 0)
	P001 = App.Vector(806.3924, 800.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(892.9949, 650.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(508.2051, 650.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(594.8076, 800.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceButtress_Fa0():
	FC000 = ctr_face_cabane_plancher_faceButtress_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceButtress():
	FA000 = face_cabane_plancher_faceButtress_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceSide_Fa0_Ctr0():
	P000 = App.Vector(200.0000, 0.0000, 0)
	P001 = App.Vector(300.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(300.0000, 800.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(200.0000, 800.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceSide_Fa0():
	FC000 = ctr_face_cabane_plancher_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_faceSide_Fa1_Ctr0():
	P000 = App.Vector(500.6000, 0.0000, 0)
	P001 = App.Vector(600.6000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(600.6000, 800.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(500.6000, 800.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(500.6000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceSide_Fa1():
	FC000 = ctr_face_cabane_plancher_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceSide():
	FA000 = face_cabane_plancher_faceSide_Fa0()
	FA001 = face_cabane_plancher_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_cabane_plancher_plancherTop():
	FIG = cabane_plancher_facePlancherTop()
	VEX = FIG.extrude(App.Vector(0, 0, 20))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 820.0000))
	return VFP
subpax_cabane_plancher_plancherTop = fex_subpax_cabane_plancher_plancherTop()

def fex_subpax_cabane_plancher_plancherBottom():
	FIG = cabane_plancher_facePlancherBottom()
	VEX = FIG.extrude(App.Vector(0, 0, 20))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 800.0000))
	return VFP
subpax_cabane_plancher_plancherBottom = fex_subpax_cabane_plancher_plancherBottom()

def fex_subpax_cabane_plancher_beam():
	FIG = cabane_plancher_faceBeam()
	VEX = FIG.extrude(App.Vector(0, 0, 800.6))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(800.6000, 1401.2000, 0.0000))
	return VFP
subpax_cabane_plancher_beam = fex_subpax_cabane_plancher_beam()

def fex_subpax_cabane_plancher_leg1():
	FIG = cabane_plancher_faceLeg()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(300.0000, 1401.2000, 0.0000))
	return VFP
subpax_cabane_plancher_leg1 = fex_subpax_cabane_plancher_leg1()

def fex_subpax_cabane_plancher_leg2():
	FIG = cabane_plancher_faceLeg()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(600.6000, 1401.2000, 0.0000))
	return VFP
subpax_cabane_plancher_leg2 = fex_subpax_cabane_plancher_leg2()

def fex_subpax_cabane_plancher_buttress1():
	FIG = cabane_plancher_faceButtress()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(300.0000, 1401.2000, 0.0000))
	return VFP
subpax_cabane_plancher_buttress1 = fex_subpax_cabane_plancher_buttress1()

def fex_subpax_cabane_plancher_buttress2():
	FIG = cabane_plancher_faceButtress()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(600.6000, 1401.2000, 0.0000))
	return VFP
subpax_cabane_plancher_buttress2 = fex_subpax_cabane_plancher_buttress2()

def fvol_pax_cabane_plancher():
	V000 = subpax_cabane_plancher_plancherTop
	V001 = V000.fuse(subpax_cabane_plancher_plancherBottom)
	V002 = V001.fuse(subpax_cabane_plancher_beam)
	V003 = V002.fuse(subpax_cabane_plancher_leg1)
	V004 = V003.fuse(subpax_cabane_plancher_leg2)
	V005 = V004.fuse(subpax_cabane_plancher_buttress1)
	V006 = V005.fuse(subpax_cabane_plancher_buttress2)
	VFC = V006.removeSplitter()
	return VFC
pax_cabane_plancher = fvol_pax_cabane_plancher()


pax_cabane_plancher.check()
#pax_cabane_plancher.exportBrep(f"{outFileName}.brep")
#pax_cabane_plancher.exportIges(f"{outFileName}.igs")
#pax_cabane_plancher.exportStep(f"{outFileName}.stp")
pax_cabane_plancher.exportStl(f"{outFileName}.stl")

