# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "codeExample1"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_codeExample1_faceExample1_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(40.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(50.0000, 17.3205, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(51.3803, 43.1448, 0)
	P004 = App.Vector(28.1430, 31.7946, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(27.1394, 30.2113, 0)
	P006 = App.Vector(25.2657, 30.1544, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(10.3668, 30.7155, 0)
	P008 = App.Vector(0.0000, 20.0000, 0)
	S004 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(0.0000, 0.0000, 0)
	S005 = Part.LineSegment(P008, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_codeExample1_faceExample1_Fa0():
	FC000 = ctr_face_codeExample1_faceExample1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def codeExample1_faceExample1():
	FA000 = face_codeExample1_faceExample1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_codeExample1_example1():
	FIG = codeExample1_faceExample1()
	VEX = FIG.extrude(App.Vector(0, 0, 5))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_codeExample1_example1 = fex_subpax_codeExample1_example1()

pax_codeExample1 = subpax_codeExample1_example1

pax_codeExample1.check()
#pax_codeExample1.exportBrep(f"{outFileName}.brep")
#pax_codeExample1.exportIges(f"{outFileName}.igs")
#pax_codeExample1.exportStep(f"{outFileName}.stp")
pax_codeExample1.exportStl(f"{outFileName}.stl")

