# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "sfDie"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(0.0000, -31.4159, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, -231.4159, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(200.0000, -231.4159, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0000, -31.4159, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(200.0000, 0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(231.4159, -0.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(431.4159, -0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(462.8319, -0.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(662.8319, -0.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(662.8319, 200.0000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(462.8319, 200.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(431.4159, 200.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(231.4159, 200.0000, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(200.0000, 200.0000, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(200.0000, 231.4159, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(200.0000, 431.4159, 0)
	S015 = Part.LineSegment(P015, P016)
	P017 = App.Vector(0.0000, 431.4159, 0)
	S016 = Part.LineSegment(P016, P017)
	P018 = App.Vector(0.0000, 231.4159, 0)
	S017 = Part.LineSegment(P017, P018)
	P019 = App.Vector(0.0000, 200.0000, 0)
	S018 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-31.4159, 200.0000, 0)
	S019 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-231.4159, 200.0000, 0)
	S020 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-231.4159, 0.0000, 0)
	S021 = Part.LineSegment(P021, P022)
	P023 = App.Vector(-31.4159, 0.0000, 0)
	S022 = Part.LineSegment(P022, P023)
	P024 = App.Vector(0.0000, 0.0000, 0)
	S023 = Part.LineSegment(P023, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr1():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(0.0000, -31.4159, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, -231.4159, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(200.0000, -231.4159, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0000, -31.4159, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(200.0000, 0.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(231.4159, -0.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(431.4159, -0.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(462.8319, -0.0000, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(662.8319, -0.0000, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(662.8319, 200.0000, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(462.8319, 200.0000, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(431.4159, 200.0000, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(231.4159, 200.0000, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(200.0000, 200.0000, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(200.0000, 231.4159, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(200.0000, 431.4159, 0)
	S015 = Part.LineSegment(P015, P016)
	P017 = App.Vector(0.0000, 431.4159, 0)
	S016 = Part.LineSegment(P016, P017)
	P018 = App.Vector(0.0000, 231.4159, 0)
	S017 = Part.LineSegment(P017, P018)
	P019 = App.Vector(0.0000, 200.0000, 0)
	S018 = Part.LineSegment(P018, P019)
	P020 = App.Vector(-31.4159, 200.0000, 0)
	S019 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-231.4159, 200.0000, 0)
	S020 = Part.LineSegment(P020, P021)
	P022 = App.Vector(-231.4159, 0.0000, 0)
	S021 = Part.LineSegment(P021, P022)
	P023 = App.Vector(-31.4159, 0.0000, 0)
	S022 = Part.LineSegment(P022, P023)
	P024 = App.Vector(0.0000, 0.0000, 0)
	S023 = Part.LineSegment(P023, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(100.0000, 100.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(298.0826, 66.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(364.7493, 133.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(50.0000, -181.4159, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(100.0000, -131.4159, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr7():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(150.0000, -81.4159, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr8():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(50.0000, 281.4159, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr9():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(50.0000, 381.4159, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr10():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(150.0000, 281.4159, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr11():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(150.0000, 381.4159, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr12():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(-131.4159, 100.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr13():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(-181.4159, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr14():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(-81.4159, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr15():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(-181.4159, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr16():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(-81.4159, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr17():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(612.8319, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr18():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(562.8319, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr19():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(512.8319, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr20():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(612.8319, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr21():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(562.8319, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr22():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(512.8319, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr23():
	P000 = App.Vector(99.0000, -30.4159, 0)
	P001 = App.Vector(100.0000, -31.4159, 0)
	P002 = App.Vector(101.0000, -30.4159, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(101.0000, -1.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(100.0000, 0.0000, 0)
	P005 = App.Vector(99.0000, -1.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(99.0000, -30.4159, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr24():
	P000 = App.Vector(230.4159, 99.0000, 0)
	P001 = App.Vector(231.4159, 100.0000, 0)
	P002 = App.Vector(230.4159, 101.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(201.0000, 101.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0000, 100.0000, 0)
	P005 = App.Vector(201.0000, 99.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(230.4159, 99.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr25():
	P000 = App.Vector(101.0000, 230.4159, 0)
	P001 = App.Vector(100.0000, 231.4159, 0)
	P002 = App.Vector(99.0000, 230.4159, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(99.0000, 201.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(100.0000, 200.0000, 0)
	P005 = App.Vector(101.0000, 201.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(101.0000, 230.4159, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr26():
	P000 = App.Vector(-30.4159, 101.0000, 0)
	P001 = App.Vector(-31.4159, 100.0000, 0)
	P002 = App.Vector(-30.4159, 99.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-1.0000, 99.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 100.0000, 0)
	P005 = App.Vector(-1.0000, 101.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-30.4159, 101.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_pattern_Fa0_Ctr27():
	P000 = App.Vector(461.8319, 99.0000, 0)
	P001 = App.Vector(462.8319, 100.0000, 0)
	P002 = App.Vector(461.8319, 101.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(432.4159, 101.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(431.4159, 100.0000, 0)
	P005 = App.Vector(432.4159, 99.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(461.8319, 99.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_pattern_Fa0():
	FC000 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr0()
	FC001 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr1()
	FC002 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr2()
	FC003 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr3()
	FC004 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr4()
	FC005 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr5()
	FC006 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr6()
	FC007 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr7()
	FC008 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr8()
	FC009 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr9()
	FC010 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr10()
	FC011 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr11()
	FC012 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr12()
	FC013 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr13()
	FC014 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr14()
	FC015 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr15()
	FC016 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr16()
	FC017 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr17()
	FC018 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr18()
	FC019 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr19()
	FC020 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr20()
	FC021 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr21()
	FC022 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr22()
	FC023 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr23()
	FC024 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr24()
	FC025 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr25()
	FC026 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr26()
	FC027 = ctr_face_sfDie_SFG_pattern_Fa0_Ctr27()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007, FC008, FC009, FC010, FC011, FC012, FC013, FC014, FC015, FC016, FC017, FC018, FC019, FC020, FC021, FC022, FC023, FC024, FC025, FC026, FC027])
	rOneFace.check()
	return rOneFace

def sfDie_SFG_pattern():
	FA000 = face_sfDie_SFG_pattern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_profiles_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa0():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa1_Ctr0():
	P000 = App.Vector(200.0000, 0.0000, 0)
	P001 = App.Vector(217.6777, 7.3223, 0)
	P002 = App.Vector(225.0000, 25.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(215.0000, 25.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(210.6066, 14.3934, 0)
	P005 = App.Vector(200.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(200.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa1():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa2_Ctr0():
	P000 = App.Vector(225.0000, 25.0000, 0)
	P001 = App.Vector(225.0000, 225.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(215.0000, 225.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(215.0000, 25.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(225.0000, 25.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa2():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa3_Ctr0():
	P000 = App.Vector(0.0000, 10.0000, 0)
	P001 = App.Vector(-10.6066, 14.3934, 0)
	P002 = App.Vector(-15.0000, 25.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-25.0000, 25.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-17.6777, 7.3223, 0)
	P005 = App.Vector(-0.0000, 0.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 10.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa3():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa4_Ctr0():
	P000 = App.Vector(-15.0000, 25.0000, 0)
	P001 = App.Vector(-15.0000, 225.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-25.0000, 225.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-25.0000, 25.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-15.0000, 25.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa4():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa5_Ctr0():
	P000 = App.Vector(0.0000, 300.0000, 0)
	P001 = App.Vector(200.0000, 300.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 310.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 310.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 300.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa5():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa6_Ctr0():
	P000 = App.Vector(200.0000, 300.0000, 0)
	P001 = App.Vector(217.6777, 307.3223, 0)
	P002 = App.Vector(225.0000, 325.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(215.0000, 325.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(210.6066, 314.3934, 0)
	P005 = App.Vector(200.0000, 310.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(200.0000, 300.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa6():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa7_Ctr0():
	P000 = App.Vector(225.0000, 325.0000, 0)
	P001 = App.Vector(225.0000, 525.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(215.0000, 525.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(215.0000, 325.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(225.0000, 325.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa7():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa8_Ctr0():
	P000 = App.Vector(225.0000, 525.0000, 0)
	P001 = App.Vector(217.6777, 542.6777, 0)
	P002 = App.Vector(200.0000, 550.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(200.0000, 540.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(210.6066, 535.6066, 0)
	P005 = App.Vector(215.0000, 525.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(225.0000, 525.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa8():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa9_Ctr0():
	P000 = App.Vector(200.0000, 550.0000, 0)
	P001 = App.Vector(0.0000, 550.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 540.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(200.0000, 540.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0000, 550.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa9():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa10_Ctr0():
	P000 = App.Vector(0.0000, 310.0000, 0)
	P001 = App.Vector(-10.6066, 314.3934, 0)
	P002 = App.Vector(-15.0000, 325.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-25.0000, 325.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-17.6777, 307.3223, 0)
	P005 = App.Vector(-0.0000, 300.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 310.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa10():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfDie_SFG_profiles_Fa11_Ctr0():
	P000 = App.Vector(-15.0000, 325.0000, 0)
	P001 = App.Vector(-15.0000, 525.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-25.0000, 525.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-25.0000, 325.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-15.0000, 325.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_profiles_Fa11():
	FC000 = ctr_face_sfDie_SFG_profiles_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfDie_SFG_profiles():
	FA000 = face_sfDie_SFG_profiles_Fa0()
	FA001 = face_sfDie_SFG_profiles_Fa1()
	FA002 = face_sfDie_SFG_profiles_Fa2()
	FA003 = face_sfDie_SFG_profiles_Fa3()
	FA004 = face_sfDie_SFG_profiles_Fa4()
	FA005 = face_sfDie_SFG_profiles_Fa5()
	FA006 = face_sfDie_SFG_profiles_Fa6()
	FA007 = face_sfDie_SFG_profiles_Fa7()
	FA008 = face_sfDie_SFG_profiles_Fa8()
	FA009 = face_sfDie_SFG_profiles_Fa9()
	FA010 = face_sfDie_SFG_profiles_Fa10()
	FA011 = face_sfDie_SFG_profiles_Fa11()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011])
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_f00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 200.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_f00_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(100.0000, 100.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_sfDie_SFG_f00_Fa0():
	FC000 = ctr_face_sfDie_SFG_f00_Fa0_Ctr0()
	FC001 = ctr_face_sfDie_SFG_f00_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def sfDie_SFG_f00():
	FA000 = face_sfDie_SFG_f00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_f01_Fa0_Ctr0():
	P000 = App.Vector(-0.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-0.0000, 200.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_f01_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(66.6667, 66.6667, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f01_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(133.3333, 133.3333, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_sfDie_SFG_f01_Fa0():
	FC000 = ctr_face_sfDie_SFG_f01_Fa0_Ctr0()
	FC001 = ctr_face_sfDie_SFG_f01_Fa0_Ctr1()
	FC002 = ctr_face_sfDie_SFG_f01_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def sfDie_SFG_f01():
	FA000 = face_sfDie_SFG_f01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_f02_Fa0_Ctr0():
	P000 = App.Vector(200.0000, 0.0000, 0)
	P001 = App.Vector(200.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 200.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_f02_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(150.0000, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f02_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(100.0000, 100.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f02_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(50.0000, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_sfDie_SFG_f02_Fa0():
	FC000 = ctr_face_sfDie_SFG_f02_Fa0_Ctr0()
	FC001 = ctr_face_sfDie_SFG_f02_Fa0_Ctr1()
	FC002 = ctr_face_sfDie_SFG_f02_Fa0_Ctr2()
	FC003 = ctr_face_sfDie_SFG_f02_Fa0_Ctr3()
	rOneFace = FC000.cut([FC001, FC002, FC003])
	rOneFace.check()
	return rOneFace

def sfDie_SFG_f02():
	FA000 = face_sfDie_SFG_f02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_f03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 200.0000, 0)
	P001 = App.Vector(0.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(200.0000, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(200.0000, 200.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 200.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_f03_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(50.0000, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f03_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(150.0000, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f03_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(50.0000, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f03_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(150.0000, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_sfDie_SFG_f03_Fa0():
	FC000 = ctr_face_sfDie_SFG_f03_Fa0_Ctr0()
	FC001 = ctr_face_sfDie_SFG_f03_Fa0_Ctr1()
	FC002 = ctr_face_sfDie_SFG_f03_Fa0_Ctr2()
	FC003 = ctr_face_sfDie_SFG_f03_Fa0_Ctr3()
	FC004 = ctr_face_sfDie_SFG_f03_Fa0_Ctr4()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004])
	rOneFace.check()
	return rOneFace

def sfDie_SFG_f03():
	FA000 = face_sfDie_SFG_f03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_f04_Fa0_Ctr0():
	P000 = App.Vector(200.0000, 200.0000, 0)
	P001 = App.Vector(0.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(200.0000, -0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0000, 200.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_f04_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(100.0000, 100.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f04_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(150.0000, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f04_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(50.0000, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f04_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(150.0000, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f04_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(50.0000, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_sfDie_SFG_f04_Fa0():
	FC000 = ctr_face_sfDie_SFG_f04_Fa0_Ctr0()
	FC001 = ctr_face_sfDie_SFG_f04_Fa0_Ctr1()
	FC002 = ctr_face_sfDie_SFG_f04_Fa0_Ctr2()
	FC003 = ctr_face_sfDie_SFG_f04_Fa0_Ctr3()
	FC004 = ctr_face_sfDie_SFG_f04_Fa0_Ctr4()
	FC005 = ctr_face_sfDie_SFG_f04_Fa0_Ctr5()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005])
	rOneFace.check()
	return rOneFace

def sfDie_SFG_f04():
	FA000 = face_sfDie_SFG_f04_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_f05_Fa0_Ctr0():
	P000 = App.Vector(200.0000, 200.0000, 0)
	P001 = App.Vector(0.0000, 200.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.0000, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(200.0000, -0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0000, 200.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfDie_SFG_f05_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(150.0000, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f05_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(100.0000, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f05_Fa0_Ctr3():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(50.0000, 150.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f05_Fa0_Ctr4():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(150.0000, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f05_Fa0_Ctr5():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(100.0000, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_sfDie_SFG_f05_Fa0_Ctr6():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(50.0000, 50.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_sfDie_SFG_f05_Fa0():
	FC000 = ctr_face_sfDie_SFG_f05_Fa0_Ctr0()
	FC001 = ctr_face_sfDie_SFG_f05_Fa0_Ctr1()
	FC002 = ctr_face_sfDie_SFG_f05_Fa0_Ctr2()
	FC003 = ctr_face_sfDie_SFG_f05_Fa0_Ctr3()
	FC004 = ctr_face_sfDie_SFG_f05_Fa0_Ctr4()
	FC005 = ctr_face_sfDie_SFG_f05_Fa0_Ctr5()
	FC006 = ctr_face_sfDie_SFG_f05_Fa0_Ctr6()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006])
	rOneFace.check()
	return rOneFace

def sfDie_SFG_f05():
	FA000 = face_sfDie_SFG_f05_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_fj00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(17.6777, 7.3223, 0)
	P002 = App.Vector(25.0000, 25.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(15.0000, 25.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.6066, 14.3934, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_fj00_Fa0():
	FC000 = ctr_face_sfDie_SFG_fj00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfDie_SFG_fj00():
	FA000 = face_sfDie_SFG_fj00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_fj01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(17.6777, 7.3223, 0)
	P002 = App.Vector(25.0000, 25.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(15.0000, 25.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.6066, 14.3934, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_fj01_Fa0():
	FC000 = ctr_face_sfDie_SFG_fj01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfDie_SFG_fj01():
	FA000 = face_sfDie_SFG_fj01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_fj02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(17.6777, 7.3223, 0)
	P002 = App.Vector(25.0000, 25.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(15.0000, 25.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.6066, 14.3934, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_fj02_Fa0():
	FC000 = ctr_face_sfDie_SFG_fj02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfDie_SFG_fj02():
	FA000 = face_sfDie_SFG_fj02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_fj03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(17.6777, 7.3223, 0)
	P002 = App.Vector(25.0000, 25.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(15.0000, 25.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.6066, 14.3934, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_fj03_Fa0():
	FC000 = ctr_face_sfDie_SFG_fj03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfDie_SFG_fj03():
	FA000 = face_sfDie_SFG_fj03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfDie_SFG_fj04_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(17.6777, 7.3223, 0)
	P002 = App.Vector(25.0000, 25.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(15.0000, 25.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(10.6066, 14.3934, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfDie_SFG_fj04_Fa0():
	FC000 = ctr_face_sfDie_SFG_fj04_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfDie_SFG_fj04():
	FA000 = face_sfDie_SFG_fj04_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_sfDie_SFG_f00():
	FIG = sfDie_SFG_f00()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_sfDie_SFG_f00 = fex_subpax_sfDie_SFG_f00()

def fex_subpax_sfDie_SFG_f01():
	FIG = sfDie_SFG_f01()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(225.0000, -0.0000, 25.0000))
	return VFP
subpax_sfDie_SFG_f01 = fex_subpax_sfDie_SFG_f01()

def fex_subpax_sfDie_SFG_f02():
	FIG = sfDie_SFG_f02()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -25.0000, 25.0000))
	return VFP
subpax_sfDie_SFG_f02 = fex_subpax_sfDie_SFG_f02()

def fex_subpax_sfDie_SFG_f03():
	FIG = sfDie_SFG_f03()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(200.0000, 225.0000, 25.0000))
	return VFP
subpax_sfDie_SFG_f03 = fex_subpax_sfDie_SFG_f03()

def fex_subpax_sfDie_SFG_f04():
	FIG = sfDie_SFG_f04()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -180.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-25.0000, 200.0000, 25.0000))
	return VFP
subpax_sfDie_SFG_f04 = fex_subpax_sfDie_SFG_f04()

def fex_subpax_sfDie_SFG_f05():
	FIG = sfDie_SFG_f05()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -180.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 180.0000)
	VFP = VR3.translate(App.Vector(200.0000, 0.0000, 250.0000))
	return VFP
subpax_sfDie_SFG_f05 = fex_subpax_sfDie_SFG_f05()

def fex_subpax_sfDie_SFG_fj00():
	FIG = sfDie_SFG_fj00()
	VEX = FIG.extrude(App.Vector(0, 0, 200))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90.0000)
	VFP = VR3.translate(App.Vector(200.0000, 0.0000, 0.0000))
	return VFP
subpax_sfDie_SFG_fj00 = fex_subpax_sfDie_SFG_fj00()

def fex_subpax_sfDie_SFG_fj01():
	FIG = sfDie_SFG_fj01()
	VEX = FIG.extrude(App.Vector(0, 0, 200))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(200.0000, 200.0000, 0.0000))
	return VFP
subpax_sfDie_SFG_fj01 = fex_subpax_sfDie_SFG_fj01()

def fex_subpax_sfDie_SFG_fj02():
	FIG = sfDie_SFG_fj02()
	VEX = FIG.extrude(App.Vector(0, 0, 200))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90.0000)
	VFP = VR3.translate(App.Vector(0.0000, 200.0000, 0.0000))
	return VFP
subpax_sfDie_SFG_fj02 = fex_subpax_sfDie_SFG_fj02()

def fex_subpax_sfDie_SFG_fj03():
	FIG = sfDie_SFG_fj03()
	VEX = FIG.extrude(App.Vector(0, 0, 200))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -180.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_sfDie_SFG_fj03 = fex_subpax_sfDie_SFG_fj03()

def fex_subpax_sfDie_SFG_fj04():
	FIG = sfDie_SFG_fj04()
	VEX = FIG.extrude(App.Vector(0, 0, 200))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(225.0000, 200.0000, 225.0000))
	return VFP
subpax_sfDie_SFG_fj04 = fex_subpax_sfDie_SFG_fj04()

def fvol_pax_sfDie():
	V000 = subpax_sfDie_SFG_f00
	V001 = V000.fuse(subpax_sfDie_SFG_f01)
	V002 = V001.fuse(subpax_sfDie_SFG_f02)
	V003 = V002.fuse(subpax_sfDie_SFG_f03)
	V004 = V003.fuse(subpax_sfDie_SFG_f04)
	V005 = V004.fuse(subpax_sfDie_SFG_f05)
	V006 = V005.fuse(subpax_sfDie_SFG_fj00)
	V007 = V006.fuse(subpax_sfDie_SFG_fj01)
	V008 = V007.fuse(subpax_sfDie_SFG_fj02)
	V009 = V008.fuse(subpax_sfDie_SFG_fj03)
	V010 = V009.fuse(subpax_sfDie_SFG_fj04)
	VFC = V010.removeSplitter()
	return VFC
pax_sfDie = fvol_pax_sfDie()


pax_sfDie.check()
#pax_sfDie.exportBrep(f"{outFileName}.brep")
#pax_sfDie.exportIges(f"{outFileName}.igs")
#pax_sfDie.exportStep(f"{outFileName}.stp")
pax_sfDie.exportStl(f"{outFileName}.stl")

