# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "lens_x3"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_lens_x3_faceLensSim_Fa0_Ctr0():
	P000 = App.Vector(4.0000, 0.0000, 0)
	P001 = App.Vector(3.4209, 7.5879, 0)
	P002 = App.Vector(1.6970, 15.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(1.6970, 20.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.6228, 20.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-0.6228, 15.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-3.1453, 7.6877, 0)
	P007 = App.Vector(-4.0000, 0.0000, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-3.1453, -7.6877, 0)
	P009 = App.Vector(-0.6228, -15.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-0.6228, -20.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(1.6970, -20.0000, 0)
	S007 = Part.LineSegment(P010, P011)
	P012 = App.Vector(1.6970, -15.0000, 0)
	S008 = Part.LineSegment(P011, P012)
	P013 = App.Vector(3.4209, -7.5879, 0)
	P014 = App.Vector(4.0000, 0.0000, 0)
	S009 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lens_x3_faceLensSim_Fa0():
	FC000 = ctr_face_lens_x3_faceLensSim_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_lens_x3_faceLensSim_Fa1_Ctr0():
	P000 = App.Vector(24.0000, 0.0000, 0)
	P001 = App.Vector(23.4209, 7.5879, 0)
	P002 = App.Vector(21.6970, 15.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(21.6970, 20.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(16.0000, 20.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(16.0000, 0.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(16.0000, -20.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(21.6970, -20.0000, 0)
	S005 = Part.LineSegment(P006, P007)
	P008 = App.Vector(21.6970, -15.0000, 0)
	S006 = Part.LineSegment(P007, P008)
	P009 = App.Vector(23.4209, -7.5879, 0)
	P010 = App.Vector(24.0000, 0.0000, 0)
	S007 = Part.Arc(P008, P009, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lens_x3_faceLensSim_Fa1():
	FC000 = ctr_face_lens_x3_faceLensSim_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_lens_x3_faceLensSim_Fa2_Ctr0():
	P000 = App.Vector(44.0000, 0.0000, 0)
	P001 = App.Vector(43.4209, 7.5879, 0)
	P002 = App.Vector(41.6970, 15.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(41.6970, 20.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(32.6228, 20.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(32.6228, 15.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(35.1453, 7.6877, 0)
	P007 = App.Vector(36.0000, 0.0000, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(35.1453, -7.6877, 0)
	P009 = App.Vector(32.6228, -15.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(32.6228, -20.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(41.6970, -20.0000, 0)
	S007 = Part.LineSegment(P010, P011)
	P012 = App.Vector(41.6970, -15.0000, 0)
	S008 = Part.LineSegment(P011, P012)
	P013 = App.Vector(43.4209, -7.5879, 0)
	P014 = App.Vector(44.0000, 0.0000, 0)
	S009 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lens_x3_faceLensSim_Fa2():
	FC000 = ctr_face_lens_x3_faceLensSim_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def lens_x3_faceLensSim():
	FA000 = face_lens_x3_faceLensSim_Fa0()
	FA001 = face_lens_x3_faceLensSim_Fa1()
	FA002 = face_lens_x3_faceLensSim_Fa2()
	rOneFig = FA000.fuse([FA001, FA002])
	rOneFig.check()
	return rOneFig

def ctr_face_lens_x3_faceLens1_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 4.0000, 0)
	P001 = App.Vector(-7.5879, 3.4209, 0)
	P002 = App.Vector(-15.0000, 1.6970, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-20.0000, 1.6970, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-20.0000, -0.6228, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-15.0000, -0.6228, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-7.6877, -3.1453, 0)
	P007 = App.Vector(-0.0000, -4.0000, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(0.0000, 4.0000, 0)
	S005 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lens_x3_faceLens1_Fa0():
	FC000 = ctr_face_lens_x3_faceLens1_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def lens_x3_faceLens1():
	FA000 = face_lens_x3_faceLens1_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_lens_x3_faceLens2_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 4.0000, 0)
	P001 = App.Vector(-7.5879, 3.4209, 0)
	P002 = App.Vector(-15.0000, 1.6970, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-20.0000, 1.6970, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-20.0000, -4.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-0.0000, -4.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(0.0000, 4.0000, 0)
	S004 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lens_x3_faceLens2_Fa0():
	FC000 = ctr_face_lens_x3_faceLens2_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def lens_x3_faceLens2():
	FA000 = face_lens_x3_faceLens2_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_lens_x3_faceLens3_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 4.0000, 0)
	P001 = App.Vector(-7.5879, 3.4209, 0)
	P002 = App.Vector(-15.0000, 1.6970, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-20.0000, 1.6970, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-20.0000, -7.3772, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-15.0000, -7.3772, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-7.6877, -4.8547, 0)
	P007 = App.Vector(-0.0000, -4.0000, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(0.0000, 4.0000, 0)
	S005 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lens_x3_faceLens3_Fa0():
	FC000 = ctr_face_lens_x3_faceLens3_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def lens_x3_faceLens3():
	FA000 = face_lens_x3_faceLens3_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_lens_x3_lens1():
	FIG = lens_x3_faceLens1()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_lens_x3_lens1 = fex_subpax_lens_x3_lens1()

def fex_subpax_lens_x3_lens2():
	FIG = lens_x3_faceLens2()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 20.0000))
	return VFP
subpax_lens_x3_lens2 = fex_subpax_lens_x3_lens2()

def fex_subpax_lens_x3_lens3():
	FIG = lens_x3_faceLens3()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 40.0000))
	return VFP
subpax_lens_x3_lens3 = fex_subpax_lens_x3_lens3()

def fvol_pax_lens_x3():
	V000 = subpax_lens_x3_lens1
	V001 = V000.fuse(subpax_lens_x3_lens2)
	V002 = V001.fuse(subpax_lens_x3_lens3)
	VFC = V002.removeSplitter()
	return VFC
pax_lens_x3 = fvol_pax_lens_x3()


pax_lens_x3.check()
#pax_lens_x3.exportBrep(f"{outFileName}.brep")
#pax_lens_x3.exportIges(f"{outFileName}.igs")
#pax_lens_x3.exportStep(f"{outFileName}.stp")
pax_lens_x3.exportStl(f"{outFileName}.stl")

