# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "rail"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_rail_faceRail_Fa0_Ctr0():
	P000 = App.Vector(100.0000, 3.0000, 0)
	P001 = App.Vector(100.0000, 3.2992, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(99.2296, 5.3064, 0)
	P003 = App.Vector(97.3141, 6.2827, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(7.6859, 15.7173, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(5.7704, 16.6936, 0)
	P006 = App.Vector(5.0000, 18.7008, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(5.0000, 113.5935, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(5.6599, 115.4707, 0)
	P009 = App.Vector(7.3492, 116.5220, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(47.6508, 125.4780, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(49.3401, 126.5293, 0)
	P012 = App.Vector(50.0000, 128.4065, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(50.0000, 153.9830, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(49.4830, 155.6667, 0)
	P015 = App.Vector(48.1102, 156.7701, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-0.0000, 166.0000, 0)
	P017 = App.Vector(-48.1102, 156.7701, 0)
	S010 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(-49.4830, 155.6667, 0)
	P019 = App.Vector(-50.0000, 153.9830, 0)
	S011 = Part.Arc(P017, P018, P019)
	P020 = App.Vector(-50.0000, 128.4065, 0)
	S012 = Part.LineSegment(P019, P020)
	P021 = App.Vector(-49.3401, 126.5293, 0)
	P022 = App.Vector(-47.6508, 125.4780, 0)
	S013 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-7.3492, 116.5220, 0)
	S014 = Part.LineSegment(P022, P023)
	P024 = App.Vector(-5.6599, 115.4707, 0)
	P025 = App.Vector(-5.0000, 113.5935, 0)
	S015 = Part.Arc(P023, P024, P025)
	P026 = App.Vector(-5.0000, 18.7008, 0)
	S016 = Part.LineSegment(P025, P026)
	P027 = App.Vector(-5.7704, 16.6936, 0)
	P028 = App.Vector(-7.6859, 15.7173, 0)
	S017 = Part.Arc(P026, P027, P028)
	P029 = App.Vector(-97.3141, 6.2827, 0)
	S018 = Part.LineSegment(P028, P029)
	P030 = App.Vector(-99.2296, 5.3064, 0)
	P031 = App.Vector(-100.0000, 3.2992, 0)
	S019 = Part.Arc(P029, P030, P031)
	P032 = App.Vector(-100.0000, 3.0000, 0)
	S020 = Part.LineSegment(P031, P032)
	P033 = App.Vector(-99.1213, 0.8787, 0)
	P034 = App.Vector(-97.0000, 0.0000, 0)
	S021 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(97.0000, 0.0000, 0)
	S022 = Part.LineSegment(P034, P035)
	P036 = App.Vector(99.1213, 0.8787, 0)
	P037 = App.Vector(100.0000, 3.0000, 0)
	S023 = Part.Arc(P035, P036, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rail_faceRail_Fa0():
	FC000 = ctr_face_rail_faceRail_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rail_faceRail():
	FA000 = face_rail_faceRail_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_rail():
	FIG = rail_faceRail()
	VEX = FIG.extrude(App.Vector(0, 0, 100))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rail = fex_subpax_rail()

pax_rail = subpax_rail

pax_rail.check()
#pax_rail.exportBrep(f"{outFileName}.brep")
#pax_rail.exportIges(f"{outFileName}.igs")
#pax_rail.exportStep(f"{outFileName}.stp")
pax_rail.exportStl(f"{outFileName}.stl")

