# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "sfTube"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_sfTube_SFG_pattern_Fa0_Ctr0():
	P000 = App.Vector(-125.0000, 0.0000, 0)
	P001 = App.Vector(125.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(145.8808, 0.7814, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(395.1816, 19.4658, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(415.9456, 21.8056, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(663.1527, 59.0699, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(683.6838, 62.9550, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(927.4145, 118.5907, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(947.5978, 123.9994, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(1186.4887, 197.6954, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(1206.2113, 204.5974, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(1438.9263, 295.9415, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(1458.0779, 304.2982, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(655.9711, 2142.5377, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(636.8196, 2134.1810, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(543.7336, 2097.6434, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(524.0110, 2090.7414, 0)
	S015 = Part.LineSegment(P015, P016)
	P017 = App.Vector(428.4546, 2061.2630, 0)
	S016 = Part.LineSegment(P016, P017)
	P018 = App.Vector(408.2713, 2055.8544, 0)
	S017 = Part.LineSegment(P017, P018)
	P019 = App.Vector(310.7790, 2033.6000, 0)
	S018 = Part.LineSegment(P018, P019)
	P020 = App.Vector(290.2480, 2029.7150, 0)
	S019 = Part.LineSegment(P019, P020)
	P021 = App.Vector(191.3651, 2014.8092, 0)
	S020 = Part.LineSegment(P020, P021)
	P022 = App.Vector(170.6011, 2012.4695, 0)
	S021 = Part.LineSegment(P021, P022)
	P023 = App.Vector(70.8808, 2004.9957, 0)
	S022 = Part.LineSegment(P022, P023)
	P024 = App.Vector(50.0000, 2004.2143, 0)
	S023 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-50.0000, 2004.2143, 0)
	S024 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-125.0000, 0.0000, 0)
	S025 = Part.LineSegment(P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfTube_SFG_pattern_Fa0_Ctr1():
	P000 = App.Vector(-125.0000, 0.0000, 0)
	P001 = App.Vector(125.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(145.8808, 0.7814, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(395.1816, 19.4658, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(415.9456, 21.8056, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(663.1527, 59.0699, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(683.6838, 62.9550, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(927.4145, 118.5907, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(947.5978, 123.9994, 0)
	S007 = Part.LineSegment(P007, P008)
	P009 = App.Vector(1186.4887, 197.6954, 0)
	S008 = Part.LineSegment(P008, P009)
	P010 = App.Vector(1206.2113, 204.5974, 0)
	S009 = Part.LineSegment(P009, P010)
	P011 = App.Vector(1438.9263, 295.9415, 0)
	S010 = Part.LineSegment(P010, P011)
	P012 = App.Vector(1458.0779, 304.2982, 0)
	S011 = Part.LineSegment(P011, P012)
	P013 = App.Vector(655.9711, 2142.5377, 0)
	S012 = Part.LineSegment(P012, P013)
	P014 = App.Vector(636.8196, 2134.1810, 0)
	S013 = Part.LineSegment(P013, P014)
	P015 = App.Vector(543.7336, 2097.6434, 0)
	S014 = Part.LineSegment(P014, P015)
	P016 = App.Vector(524.0110, 2090.7414, 0)
	S015 = Part.LineSegment(P015, P016)
	P017 = App.Vector(428.4546, 2061.2630, 0)
	S016 = Part.LineSegment(P016, P017)
	P018 = App.Vector(408.2713, 2055.8544, 0)
	S017 = Part.LineSegment(P017, P018)
	P019 = App.Vector(310.7790, 2033.6000, 0)
	S018 = Part.LineSegment(P018, P019)
	P020 = App.Vector(290.2480, 2029.7150, 0)
	S019 = Part.LineSegment(P019, P020)
	P021 = App.Vector(191.3651, 2014.8092, 0)
	S020 = Part.LineSegment(P020, P021)
	P022 = App.Vector(170.6011, 2012.4695, 0)
	S021 = Part.LineSegment(P021, P022)
	P023 = App.Vector(70.8808, 2004.9957, 0)
	S022 = Part.LineSegment(P022, P023)
	P024 = App.Vector(50.0000, 2004.2143, 0)
	S023 = Part.LineSegment(P023, P024)
	P025 = App.Vector(-50.0000, 2004.2143, 0)
	S024 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-125.0000, 0.0000, 0)
	S025 = Part.LineSegment(P025, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfTube_SFG_pattern_Fa0_Ctr2():
	P000 = App.Vector(107.4189, 1001.8518, 0)
	P001 = App.Vector(108.3808, 1002.8885, 0)
	P002 = App.Vector(107.3441, 1003.8504, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(88.4619, 1003.1439, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(87.5000, 1002.1072, 0)
	P005 = App.Vector(88.5367, 1001.1452, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(107.4189, 1001.8518, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfTube_SFG_pattern_Fa0_Ctr3():
	P000 = App.Vector(302.7736, 1017.2017, 0)
	P001 = App.Vector(303.6554, 1018.3074, 0)
	P002 = App.Vector(302.5497, 1019.1891, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(283.7731, 1017.0733, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(282.8914, 1015.9676, 0)
	P005 = App.Vector(283.9970, 1015.0859, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(302.7736, 1017.2017, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfTube_SFG_pattern_Fa0_Ctr4():
	P000 = App.Vector(496.4348, 1047.1090, 0)
	P001 = App.Vector(497.2314, 1048.2775, 0)
	P002 = App.Vector(496.0629, 1049.0741, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(477.4970, 1045.5609, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(476.7004, 1044.3924, 0)
	P005 = App.Vector(477.8688, 1043.5958, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(496.4348, 1047.1090, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfTube_SFG_pattern_Fa0_Ctr5():
	P000 = App.Vector(687.3191, 1091.4064, 0)
	P001 = App.Vector(688.0262, 1092.6312, 0)
	P002 = App.Vector(686.8014, 1093.3383, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(668.5500, 1088.4473, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(667.8429, 1087.2225, 0)
	P005 = App.Vector(669.0677, 1086.5155, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(687.3191, 1091.4064, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfTube_SFG_pattern_Fa0_Ctr6():
	P000 = App.Vector(874.3589, 1149.8462, 0)
	P001 = App.Vector(874.9725, 1151.1204, 0)
	P002 = App.Vector(873.6983, 1151.7340, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(855.8634, 1145.4926, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(855.2499, 1144.2184, 0)
	P005 = App.Vector(856.5240, 1143.6049, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(874.3589, 1149.8462, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_sfTube_SFG_pattern_Fa0_Ctr7():
	P000 = App.Vector(1056.5079, 1222.1015, 0)
	P001 = App.Vector(1057.0245, 1223.4180, 0)
	P002 = App.Vector(1055.7081, 1223.9346, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(1038.3896, 1216.3777, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1037.8729, 1215.0612, 0)
	P005 = App.Vector(1039.1894, 1214.5446, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(1056.5079, 1222.1015, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_pattern_Fa0():
	FC000 = ctr_face_sfTube_SFG_pattern_Fa0_Ctr0()
	FC001 = ctr_face_sfTube_SFG_pattern_Fa0_Ctr1()
	FC002 = ctr_face_sfTube_SFG_pattern_Fa0_Ctr2()
	FC003 = ctr_face_sfTube_SFG_pattern_Fa0_Ctr3()
	FC004 = ctr_face_sfTube_SFG_pattern_Fa0_Ctr4()
	FC005 = ctr_face_sfTube_SFG_pattern_Fa0_Ctr5()
	FC006 = ctr_face_sfTube_SFG_pattern_Fa0_Ctr6()
	FC007 = ctr_face_sfTube_SFG_pattern_Fa0_Ctr7()
	rOneFace = FC000.cut([FC001, FC002, FC003, FC004, FC005, FC006, FC007])
	rOneFace.check()
	return rOneFace

def sfTube_SFG_pattern():
	FA000 = face_sfTube_SFG_pattern_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_profiles_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(30.4748, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(30.4748, 10.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa0():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa1_Ctr0():
	P000 = App.Vector(30.4748, 0.0000, 0)
	P001 = App.Vector(42.9485, 3.3342, 0)
	P002 = App.Vector(52.0950, 12.4475, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(43.4469, 17.4685, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(37.9590, 12.0005, 0)
	P005 = App.Vector(30.4748, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(30.4748, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa1():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa2_Ctr0():
	P000 = App.Vector(52.0950, 12.4475, 0)
	P001 = App.Vector(67.3964, 38.8023, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(58.7483, 43.8233, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(43.4469, 17.4685, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(52.0950, 12.4475, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa2():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa3_Ctr0():
	P000 = App.Vector(67.3964, 38.8023, 0)
	P001 = App.Vector(70.7760, 51.2638, 0)
	P002 = App.Vector(67.4872, 63.7496, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(58.8028, 58.7917, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(60.7760, 51.3002, 0)
	P005 = App.Vector(58.7483, 43.8233, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(67.3964, 38.8023, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa3():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa4_Ctr0():
	P000 = App.Vector(67.4872, 63.7496, 0)
	P001 = App.Vector(52.3781, 90.2152, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(43.6937, 85.2573, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(58.8028, 58.7917, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(67.4872, 63.7496, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa4():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa5_Ctr0():
	P000 = App.Vector(52.3781, 90.2152, 0)
	P001 = App.Vector(43.2982, 99.3948, 0)
	P002 = App.Vector(30.8491, 102.8198, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(30.7763, 92.8200, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(38.2457, 90.7651, 0)
	P005 = App.Vector(43.6937, 85.2573, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(52.3781, 90.2152, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa5():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa6_Ctr0():
	P000 = App.Vector(30.8491, 102.8198, 0)
	P001 = App.Vector(0.3752, 103.0417, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(0.3023, 93.0419, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(30.7763, 92.8200, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(30.8491, 102.8198, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa6():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa7_Ctr0():
	P000 = App.Vector(0.3752, 103.0417, 0)
	P001 = App.Vector(-12.1225, 99.7984, 0)
	P002 = App.Vector(-21.3351, 90.7519, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-12.7238, 85.6681, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-7.1963, 91.0959, 0)
	P005 = App.Vector(0.3023, 93.0419, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.3752, 103.0417, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa7():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa8_Ctr0():
	P000 = App.Vector(-21.3351, 90.7519, 0)
	P001 = App.Vector(-36.8280, 64.5092, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-28.2167, 59.4253, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-12.7238, 85.6681, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-21.3351, 90.7519, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa8():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa9_Ctr0():
	P000 = App.Vector(-36.8280, 64.5092, 0)
	P001 = App.Vector(-40.2983, 52.0726, 0)
	P002 = App.Vector(-37.1005, 39.5632, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-28.3802, 44.4578, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-30.2989, 51.9634, 0)
	P005 = App.Vector(-28.2167, 59.4253, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-36.8280, 64.5092, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa9():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa10_Ctr0():
	P000 = App.Vector(-37.1005, 39.5632, 0)
	P001 = App.Vector(-22.1845, 12.9884, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-13.4642, 17.8829, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-28.3802, 44.4578, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-37.1005, 39.5632, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa10():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa11_Ctr0():
	P000 = App.Vector(0.0000, 721.8990, 0)
	P001 = App.Vector(180.4748, 721.8990, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(180.4748, 731.8990, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 731.8990, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 721.8990, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa11():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa12_Ctr0():
	P000 = App.Vector(180.4748, 721.8990, 0)
	P001 = App.Vector(192.9485, 725.2332, 0)
	P002 = App.Vector(202.0950, 734.3465, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(193.4469, 739.3675, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(187.9590, 733.8996, 0)
	P005 = App.Vector(180.4748, 731.8990, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(180.4748, 721.8990, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa12():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa12_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa13_Ctr0():
	P000 = App.Vector(202.0950, 734.3465, 0)
	P001 = App.Vector(292.7115, 890.4228, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(284.0634, 895.4438, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(193.4469, 739.3675, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(202.0950, 734.3465, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa13():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa13_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa14_Ctr0():
	P000 = App.Vector(292.7115, 890.4228, 0)
	P001 = App.Vector(296.0911, 902.8843, 0)
	P002 = App.Vector(292.8023, 915.3700, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(284.1179, 910.4121, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(286.0911, 902.9207, 0)
	P005 = App.Vector(284.0634, 895.4438, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(292.7115, 890.4228, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa14():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa14_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa15_Ctr0():
	P000 = App.Vector(292.8023, 915.3700, 0)
	P001 = App.Vector(203.3247, 1072.1019, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(194.6403, 1067.1440, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(284.1179, 910.4121, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(292.8023, 915.3700, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa15():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa15_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa16_Ctr0():
	P000 = App.Vector(203.3247, 1072.1019, 0)
	P001 = App.Vector(194.2448, 1081.2816, 0)
	P002 = App.Vector(181.7957, 1084.7065, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(181.7228, 1074.7068, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(189.1923, 1072.6518, 0)
	P005 = App.Vector(194.6403, 1067.1440, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(203.3247, 1072.1019, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa16():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa16_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa17_Ctr0():
	P000 = App.Vector(181.7957, 1084.7065, 0)
	P001 = App.Vector(1.3257, 1086.0206, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1.2529, 1076.0209, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(181.7228, 1074.7068, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(181.7957, 1084.7065, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa17():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa17_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa18_Ctr0():
	P000 = App.Vector(1.3257, 1086.0206, 0)
	P001 = App.Vector(-11.1720, 1082.7773, 0)
	P002 = App.Vector(-20.3846, 1073.7309, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-11.7733, 1068.6471, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-6.2457, 1074.0749, 0)
	P005 = App.Vector(1.2529, 1076.0209, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(1.3257, 1086.0206, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa18():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa18_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa19_Ctr0():
	P000 = App.Vector(-20.3846, 1073.7309, 0)
	P001 = App.Vector(-112.1351, 918.3186, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-103.5238, 913.2348, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-11.7733, 1068.6471, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-20.3846, 1073.7309, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa19():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa19_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa20_Ctr0():
	P000 = App.Vector(-112.1351, 918.3186, 0)
	P001 = App.Vector(-115.6054, 905.8821, 0)
	P002 = App.Vector(-112.4076, 893.3727, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-103.6873, 898.2672, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-105.6060, 905.7729, 0)
	P005 = App.Vector(-103.5238, 913.2348, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-112.1351, 918.3186, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa20():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa20_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_sfTube_SFG_profiles_Fa21_Ctr0():
	P000 = App.Vector(-112.4076, 893.3727, 0)
	P001 = App.Vector(-24.0736, 735.9934, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-15.3533, 740.8879, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-103.6873, 898.2672, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-112.4076, 893.3727, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_profiles_Fa21():
	FC000 = ctr_face_sfTube_SFG_profiles_Fa21_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_profiles():
	FA000 = face_sfTube_SFG_profiles_Fa0()
	FA001 = face_sfTube_SFG_profiles_Fa1()
	FA002 = face_sfTube_SFG_profiles_Fa2()
	FA003 = face_sfTube_SFG_profiles_Fa3()
	FA004 = face_sfTube_SFG_profiles_Fa4()
	FA005 = face_sfTube_SFG_profiles_Fa5()
	FA006 = face_sfTube_SFG_profiles_Fa6()
	FA007 = face_sfTube_SFG_profiles_Fa7()
	FA008 = face_sfTube_SFG_profiles_Fa8()
	FA009 = face_sfTube_SFG_profiles_Fa9()
	FA010 = face_sfTube_SFG_profiles_Fa10()
	FA011 = face_sfTube_SFG_profiles_Fa11()
	FA012 = face_sfTube_SFG_profiles_Fa12()
	FA013 = face_sfTube_SFG_profiles_Fa13()
	FA014 = face_sfTube_SFG_profiles_Fa14()
	FA015 = face_sfTube_SFG_profiles_Fa15()
	FA016 = face_sfTube_SFG_profiles_Fa16()
	FA017 = face_sfTube_SFG_profiles_Fa17()
	FA018 = face_sfTube_SFG_profiles_Fa18()
	FA019 = face_sfTube_SFG_profiles_Fa19()
	FA020 = face_sfTube_SFG_profiles_Fa20()
	FA021 = face_sfTube_SFG_profiles_Fa21()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011, FA012, FA013, FA014, FA015, FA016, FA017, FA018, FA019, FA020, FA021])
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_f00_Fa0_Ctr0():
	P000 = App.Vector(-125.0000, 0.0000, 0)
	P001 = App.Vector(125.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(50.0000, 2004.2143, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-50.0000, 2004.2143, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-125.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_f00_Fa0():
	FC000 = ctr_face_sfTube_SFG_f00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_f00():
	FA000 = face_sfTube_SFG_f00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_f01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(249.8251, 9.3487, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(99.9301, 2009.3566, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 2005.6171, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_f01_Fa0():
	FC000 = ctr_face_sfTube_SFG_f01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_f01():
	FA000 = face_sfTube_SFG_f01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_f02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(249.8251, 9.3487, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(99.9301, 2009.3566, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 2005.6171, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_f02_Fa0():
	FC000 = ctr_face_sfTube_SFG_f02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_f02():
	FA000 = face_sfTube_SFG_f02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_f03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(249.8251, 9.3487, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(99.9301, 2009.3566, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 2005.6171, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_f03_Fa0():
	FC000 = ctr_face_sfTube_SFG_f03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_f03():
	FA000 = face_sfTube_SFG_f03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_f04_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(249.8251, 9.3487, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(99.9301, 2009.3566, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 2005.6171, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_f04_Fa0():
	FC000 = ctr_face_sfTube_SFG_f04_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_f04():
	FA000 = face_sfTube_SFG_f04_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_f05_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(249.8251, 9.3487, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(99.9301, 2009.3566, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 2005.6171, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_f05_Fa0():
	FC000 = ctr_face_sfTube_SFG_f05_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_f05():
	FA000 = face_sfTube_SFG_f05_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_fj00_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.4737, 3.3342, 0)
	P002 = App.Vector(21.6202, 12.4475, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(12.9721, 17.4685, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(7.4842, 12.0005, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_fj00_Fa0():
	FC000 = ctr_face_sfTube_SFG_fj00_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_fj00():
	FA000 = face_sfTube_SFG_fj00_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_fj01_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.4737, 3.3342, 0)
	P002 = App.Vector(21.6202, 12.4475, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(12.9721, 17.4685, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(7.4842, 12.0005, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_fj01_Fa0():
	FC000 = ctr_face_sfTube_SFG_fj01_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_fj01():
	FA000 = face_sfTube_SFG_fj01_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_fj02_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.4737, 3.3342, 0)
	P002 = App.Vector(21.6202, 12.4475, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(12.9721, 17.4685, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(7.4842, 12.0005, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_fj02_Fa0():
	FC000 = ctr_face_sfTube_SFG_fj02_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_fj02():
	FA000 = face_sfTube_SFG_fj02_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_fj03_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.4737, 3.3342, 0)
	P002 = App.Vector(21.6202, 12.4475, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(12.9721, 17.4685, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(7.4842, 12.0005, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_fj03_Fa0():
	FC000 = ctr_face_sfTube_SFG_fj03_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_fj03():
	FA000 = face_sfTube_SFG_fj03_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_fj04_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.4737, 3.3342, 0)
	P002 = App.Vector(21.6202, 12.4475, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(12.9721, 17.4685, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(7.4842, 12.0005, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_fj04_Fa0():
	FC000 = ctr_face_sfTube_SFG_fj04_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_fj04():
	FA000 = face_sfTube_SFG_fj04_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_sfTube_SFG_fj05_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(12.4737, 3.3342, 0)
	P002 = App.Vector(21.6202, 12.4475, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(12.9721, 17.4685, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(7.4842, 12.0005, 0)
	P005 = App.Vector(0.0000, 10.0000, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_sfTube_SFG_fj05_Fa0():
	FC000 = ctr_face_sfTube_SFG_fj05_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def sfTube_SFG_fj05():
	FA000 = face_sfTube_SFG_fj05_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_sfTube_SFG_f00():
	FIG = sfTube_SFG_f00()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_sfTube_SFG_f00 = fex_subpax_sfTube_SFG_f00()

def fex_subpax_sfTube_SFG_f01():
	FIG = sfTube_SFG_f01()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -59.8609)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 2.1431)
	VFP = VR3.translate(App.Vector(146.6051, 0.8085, 12.4475))
	return VFP
subpax_sfTube_SFG_f01 = fex_subpax_sfTube_SFG_f01()

def fex_subpax_sfTube_SFG_f02():
	FIG = sfTube_SFG_f02()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -172.5414)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -60.1381)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 177.8208)
	VFP = VR3.translate(App.Vector(271.6051, 16.4584, 253.3936))
	return VFP
subpax_sfTube_SFG_f02 = fex_subpax_sfTube_SFG_f02()

def fex_subpax_sfTube_SFG_f03():
	FIG = sfTube_SFG_f03()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -172.5726)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -0.2772)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -177.8749)
	VFP = VR3.translate(App.Vector(125.0000, 31.2998, 481.8921))
	return VFP
subpax_sfTube_SFG_f03 = fex_subpax_sfTube_SFG_f03()

def fex_subpax_sfTube_SFG_f04():
	FIG = sfTube_SFG_f04()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -165.3273)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 59.3134)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -169.4715)
	VFP = VR3.translate(App.Vector(-146.6051, 30.4913, 469.4447))
	return VFP
subpax_sfTube_SFG_f04 = fex_subpax_sfTube_SFG_f04()

def fex_subpax_sfTube_SFG_f05():
	FIG = sfTube_SFG_f05()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -7.3352)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 59.5861)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -10.6328)
	VFP = VR3.translate(App.Vector(-271.6051, 14.8414, 228.4986))
	return VFP
subpax_sfTube_SFG_f05 = fex_subpax_sfTube_SFG_f05()

def fex_subpax_sfTube_SFG_fj00():
	FIG = sfTube_SFG_fj00()
	VEX = FIG.extrude(App.Vector(0, 0, 2005.6171120131578))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 2.1431)
	VFP = VR3.translate(App.Vector(50.0000, 2004.2143, 0.0000))
	return VFP
subpax_sfTube_SFG_fj00 = fex_subpax_sfTube_SFG_fj00()

def fex_subpax_sfTube_SFG_fj01():
	FIG = sfTube_SFG_fj01()
	VEX = FIG.extrude(App.Vector(0, 0, 2005.6171120131578))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 82.6648)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -59.5861)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 10.6328)
	VFP = VR3.translate(App.Vector(121.6051, 2010.6360, 98.8679))
	return VFP
subpax_sfTube_SFG_fj01 = fex_subpax_sfTube_SFG_fj01()

def fex_subpax_sfTube_SFG_fj02():
	FIG = sfTube_SFG_fj02()
	VEX = FIG.extrude(App.Vector(0, 0, 2005.6171120131578))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -75.3273)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -59.3134)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 169.4715)
	VFP = VR3.translate(App.Vector(71.6051, 2017.8661, 210.1833))
	return VFP
subpax_sfTube_SFG_fj02 = fex_subpax_sfTube_SFG_fj02()

def fex_subpax_sfTube_SFG_fj03():
	FIG = sfTube_SFG_fj03()
	VEX = FIG.extrude(App.Vector(0, 0, 2005.6171120131578))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -82.5726)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.2772)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 177.8749)
	VFP = VR3.translate(App.Vector(-50.0000, 2018.6746, 222.6308))
	return VFP
subpax_sfTube_SFG_fj03 = fex_subpax_sfTube_SFG_fj03()

def fex_subpax_sfTube_SFG_fj04():
	FIG = sfTube_SFG_fj04()
	VEX = FIG.extrude(App.Vector(0, 0, 2005.6171120131578))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), -82.5414)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 60.1381)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -177.8208)
	VFP = VR3.translate(App.Vector(-121.6051, 2012.2529, 123.7629))
	return VFP
subpax_sfTube_SFG_fj04 = fex_subpax_sfTube_SFG_fj04()

def fex_subpax_sfTube_SFG_fj05():
	FIG = sfTube_SFG_fj05()
	VEX = FIG.extrude(App.Vector(0, 0, 2005.6171120131578))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 59.8609)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -2.1431)
	VFP = VR3.translate(App.Vector(-71.6051, 2005.0228, 12.4475))
	return VFP
subpax_sfTube_SFG_fj05 = fex_subpax_sfTube_SFG_fj05()

def fvol_pax_sfTube():
	V000 = subpax_sfTube_SFG_f00
	V001 = V000.fuse(subpax_sfTube_SFG_f01)
	V002 = V001.fuse(subpax_sfTube_SFG_f02)
	V003 = V002.fuse(subpax_sfTube_SFG_f03)
	V004 = V003.fuse(subpax_sfTube_SFG_f04)
	V005 = V004.fuse(subpax_sfTube_SFG_f05)
	V006 = V005.fuse(subpax_sfTube_SFG_fj00)
	V007 = V006.fuse(subpax_sfTube_SFG_fj01)
	V008 = V007.fuse(subpax_sfTube_SFG_fj02)
	V009 = V008.fuse(subpax_sfTube_SFG_fj03)
	V010 = V009.fuse(subpax_sfTube_SFG_fj04)
	V011 = V010.fuse(subpax_sfTube_SFG_fj05)
	VFC = V011.removeSplitter()
	return VFC
pax_sfTube = fvol_pax_sfTube()


pax_sfTube.check()
#pax_sfTube.exportBrep(f"{outFileName}.brep")
#pax_sfTube.exportIges(f"{outFileName}.igs")
#pax_sfTube.exportStep(f"{outFileName}.stp")
pax_sfTube.exportStl(f"{outFileName}.stl")

