# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "lens_x1"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_lens_x1_faceLensSim_Fa0_Ctr0():
	P000 = App.Vector(4.0000, 0.0000, 0)
	P001 = App.Vector(3.4209, 7.5879, 0)
	P002 = App.Vector(1.6970, 15.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(1.6970, 20.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-0.6228, 20.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-0.6228, 15.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-3.1453, 7.6877, 0)
	P007 = App.Vector(-4.0000, 0.0000, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(-3.1453, -7.6877, 0)
	P009 = App.Vector(-0.6228, -15.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(-0.6228, -20.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(1.6970, -20.0000, 0)
	S007 = Part.LineSegment(P010, P011)
	P012 = App.Vector(1.6970, -15.0000, 0)
	S008 = Part.LineSegment(P011, P012)
	P013 = App.Vector(3.4209, -7.5879, 0)
	P014 = App.Vector(4.0000, 0.0000, 0)
	S009 = Part.Arc(P012, P013, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lens_x1_faceLensSim_Fa0():
	FC000 = ctr_face_lens_x1_faceLensSim_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def lens_x1_faceLensSim():
	FA000 = face_lens_x1_faceLensSim_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_lens_x1_faceLens3D_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 4.0000, 0)
	P001 = App.Vector(-7.5879, 3.4209, 0)
	P002 = App.Vector(-15.0000, 1.6970, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-20.0000, 1.6970, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-20.0000, -0.6228, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-15.0000, -0.6228, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-7.6877, -3.1453, 0)
	P007 = App.Vector(-0.0000, -4.0000, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(0.0000, 4.0000, 0)
	S005 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_lens_x1_faceLens3D_Fa0():
	FC000 = ctr_face_lens_x1_faceLens3D_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def lens_x1_faceLens3D():
	FA000 = face_lens_x1_faceLens3D_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_lens_x1():
	FIG = lens_x1_faceLens3D()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_lens_x1 = fex_subpax_lens_x1()

pax_lens_x1 = subpax_lens_x1

pax_lens_x1.check()
#pax_lens_x1.exportBrep(f"{outFileName}.brep")
#pax_lens_x1.exportIges(f"{outFileName}.igs")
#pax_lens_x1.exportStep(f"{outFileName}.stp")
pax_lens_x1.exportStl(f"{outFileName}.stl")

